### ISSUE TITLE
Search does not show any results

### ISSUE THREAD

**Issue by diimaan** [Goldenfreddy0703/Otaku#101]
When I try to search for any Shows, it does not show any results. But I can find the shows from top 100 Anime list. Shows searched, Naruto, Naruto Shippuden, Death Note!

Let me know if you need a log to look into!

Kodi Nexus 20.0 on Macbook Air M1 and Otaku version 0.3.49

**Comment by diimaan** [comment]
Yes! I did clear caches and rebuild database!

**Comment by Goldenfreddy0703** [comment]
Ok in addon settings did you accidentally enable mature search on?

**Comment by diimaan** [comment]
Ohh Yes! That I did! Does that interfere with normal searches by any chance?

**Comment by Gujal00** [comment]
> Ohh Yes! That I did! Does that interfere with normal searches by any chance?

Yes, it is `search mature titles only` if you enable that option. That option is provided for some titles like `Redo of the Healer` that do not show on a normal search

For normal use that option must be set OFF

**Comment by diimaan** [comment]
My bad! I thought it’s like Fen search mature titles as well! Good to know. Now it works as expected so I’m closing this issue!

**Comment by Goldenfreddy0703** [comment]
Oh now, i wanted it to be like Fen search mature titles as well but it just didn't feel like a good idea combine adult titles and regular titles together which is why the setting it called search mature titles only. Its cool tho.
