### ISSUE TITLE
Torrenting

### ISSUE THREAD

**Issue by HughMungis** [Goldenfreddy0703/Otaku#102]
I know there are some torrent sites that get checked but I don't know what the intended functionality is. Is the idea supposed to be that with a high enough number of seeders that you can functionally stream media? I remember trying to select a torrent source to do this in Kaito, but it never worked.

If the intended functionality is to be able to torrent a show, watch it through Otaku, and have the progress automatically tracked on MAL (which would be awesome!), then I'm not seeing any settings for it.

Not sure if this is turning into a feature request or a "help" issue. Either way, thanks.

**Comment by Goldenfreddy0703** [comment]
ummm not really sure what your asking but im sure @Gujal00 will answer for you.

**Comment by Gujal00** [comment]
You are asking two things here
1. Watchlist updates
Yes if you Mal/Anilist/Kitsu account and authorised it in Otaku settings and selected update watchlist, then yes as you keep watching episodes that will be synced to Mal/Anilist/Kitsu

2. Torrents
If you have realdebrid/premiumize/alldebrid/debrid-link account authorised in otaku, then when looking for sources along with embeds, it also looks for magnets from nyaa. If magnets are found it then checks with debrid provider if any of them is in their cache and lists those cached magnets as part of the sources. Debrid cache is accessed by https and you are not torrenting from your machine

**Comment by Goldenfreddy0703** [comment]
Thank you, I'm going to be closing this issue now.
