### ISSUE TITLE
German Dub Anime Sources

### ISSUE THREAD

**Issue by snoweuph** [Goldenfreddy0703/Otaku#103]
I Love this addon and I watch a lot in English, but I got some Friends and some of them arent good enough with their english to watch in english.
I really hate manually downloading anime on mypc and putting them on the pi.
For German Anime source I can suggest using: https://www.animetoast.cc/

**Comment by Goldenfreddy0703** [comment]
Ok i wish i could add that but consumet does not support that site. What you can do tho is make zoro your only provider and you can get german subtitles through zoro. In the future, i will have a way where multisubtitles will be on the top for torrent files in the near future.

**Comment by snoweuph** [comment]
So, If I add supportto consument for some german sources, it should work?

**Comment by Goldenfreddy0703** [comment]
maybe but not too sure
