### ISSUE TITLE
Can’t Install from repo

### ISSUE THREAD

**Issue by TwilightMercy** [Goldenfreddy0703/Otaku#105]
Hi,

kodi 20.1
repo is installed. Can’t install Otaku. 
first two - unavailable 

![image](https://user-images.githubusercontent.com/29895680/227035757-661d390c-7235-471c-988c-f2a97573a251.png)

**Comment by Goldenfreddy0703** [comment]
Hey there sorry i never got back to you, thats weird, It works for me when i do a fresh kodi install. Could you possibly have the kodi repo disabled maybe?

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this issue but if you still can't install from repo, you may wanna do a fresh install or something.
