### ISSUE TITLE
Rescrape item returns missing torrent results

### ISSUE THREAD

**Issue by SlimJim192** [Goldenfreddy0703/Otaku#107]
I'm having a weird issue on a shield and also my firestick.

I've done clean install, disabled ipv6

Some shows work fine and show many torrent results.

Boruto Naruto next generations for example shows no torrent results (set to prefer dub) only embeds. 

Sometimes I can see that it found torrent results but they don't show..

And finally I realised if I do rescrape item, I only get torrent results and I can see the items that don't show in the usual source select.

Once in a blue moon it might work properly and show these torrent results in the normal source select.

Why is it inconsistent and why do the results differ for rescrape item and source select.

Obviously id like the torrent results to show consistently.

I've tried clearing cache etc and the behaviour is very consistent for that particular show.

Many thanks.

**Comment by Gujal00** [comment]
Remove the dub only filter when searching for torrents as sub or dub is a guesswork made from the title of the torrent file. Finding torrent results and then not showing is expected as you have set to dub only, so any torrents that are deemed non dub would be removed when showing results and for latest shows would be blank screen as dub may not exist for the recent episodes

Dub filter is accurate when searching for embeds

**Comment by SlimJim192** [comment]
I see that makes sense although I'm sure I also tried with the filters off with a tertiary dub sort. But certain links weren't showing. I will try again.

But i don't understand the difference between source select and rescrape item.

There seem to be results that will show when I do rescrape item that will not show when I simply do source select.

Is there a difference in how the scrape happens for each of these options that could cause it to find the torrent more reliably?

**Comment by Gujal00** [comment]
rescrape is some old function just for scraping season packs
`query = '%s "Batch"|"Complete Series"' % (show)` is all it does, so unless you are looking for a completed anime season pack it is plain useless

**Comment by Goldenfreddy0703** [comment]
Hey so very good news @SlimJim192 , Nyaa will be very consistent in the future and we are adding a new torrent scraper called Anime Tosho. We are not sure when to release cause we got a bunch of new settings to add but hope this fixes your issue very soon.

**Comment by SlimJim192** [comment]
Thanks for all the great work. Working well for me here!

Feel like this plugin has come along way since I posted this! Or at least thats my experience using it!
