### ISSUE TITLE
Zoro bug issue

### ISSUE THREAD

**Issue by Thor4201** [Goldenfreddy0703/Otaku#108]
Hey there I'm currently running kodi 19 on windows, zoro doesn't return any links,  at the beginning it provided sources for that provider then it stopped retrieving sources from zoro. 
I did some edits in the consumet.py which seemed to fix it went to bed last night and zoro again isn't displaying sources today. 
Is there a bug somewhere causing this? I've cleared everything out and did tests re installed everything and it's not retrieving anything from zoro.

**Comment by Goldenfreddy0703** [comment]
Hey, we released an update yesterday that properly fixed the Enime Fallback, does this bug of zoro still occurring or is it fixed for you?

If it is still occurring, is it on a specific anime or multiple?

If it's on a specific anime, mind telling me which anime?

**Comment by Thor4201** [comment]
Hey sorry for delayed reply I'm still having this issue, currently on boruto it was working for about 30 episodes then it just doesn't return anything for zoro, the first time I noticed it was Naruto shippuden, it also did it with the movies, I tried Dr stone and a couple others as well same thing, I watched most of Naruto shippuden without issue with zoro for many episodes but now it just half works.

**Comment by Goldenfreddy0703** [comment]
Hey so we pushed a release and tried fixing zoro but reason why some stuff in zoro is not working is cause of the cunsumet api that provides us the episode Id's for zoro, without those Id's, we would not be able to stream the embeds and all. Sometimes zoro works, other times it doesn't work, it's just a mystery but consumet is working constantly and we may have 2 new embeds in the future. 

I'm going to go ahead and close this issue but if you have any other problems, feel free to ask and join our team if you like sense you code. We would love to have you on our team to help us improve consumet.

**Comment by Thor4201** [comment]
Hey thanks buddy I'll have a look at some things when I can get a chance. 
maybe I can work out something in it to get that one working fully. Appreciate your replies and your offer, I may take that up I'll definitely see if there is anything I can offer you guys code wise.
