### ISSUE TITLE
Error popping up during playback for subtitles 

### ISSUE THREAD

**Issue by 43v3rLoCo** [Goldenfreddy0703/Otaku#109]
Log - https://paste.kodi.tv/mofogudeci.kodi

Causes subs to be disabled and I have to manually turn them on while playing and choose english. The issue might be popping up because the languages for the subtitles all start with unknown - e.g. Unknown - English

The anime that it's happening with is Tensei Shitara Ken Deshita (Reincarnated as a Sword)

**Comment by Goldenfreddy0703** [comment]
Ok weird, from my understanding, it could be caused by kodi nerds which could be a bit buggy or could be a specific torrent or embed file you looked for. 

Did you pick a specific embed or torrent, if so, could you tell me which source you selected and what the name of it is.

**Comment by 43v3rLoCo** [comment]
I have it on autoplay so it's choosing the first one. Had to check and I think I know why now. The source is "NC-Raws /Tensei shitara Ken Deshita - 04 (B-Global 3840x2160 HEVC AAC MKV) Real debrid Provider NYAA

So it might be b/c that source is listed as raw, but still has subs in it which are named differently? I just tried a different source and the error didn't pop up and subs worked from the start. The subs were also named correctly as English - English

**Comment by Goldenfreddy0703** [comment]
Ok weird, ok I will check it our tomorrow then.


Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so i kinda fixed the bug but not really but in the future, im going to work on this again. Apparently the guy who made the torrent file made subtitles a mess which is kinda a mess so what i did was disable subtitles that don't support the standard subtitle languages. 

Thank you for pointing this out.

**Comment by 43v3rLoCo** [comment]
Nice! Haven't ran into that problem with any other series. That was the only series that had that same torrent for every episode. 

Thanks again for the work you do. Really enjoying the addon.
