### ISSUE TITLE
Subtitles  none - Defaul english

### ISSUE THREAD

**Issue by AlexGonzCan** [Goldenfreddy0703/Otaku#110]
It is not allowed to change the subtitles, none always appears. or not allows you to change to another language.

**Comment by Gujal00** [comment]
Embeds (except Zoro) have burnt in English subtitles, so will always show as `None`
You can change language only when external subtitles are available as part of torrents or Zoro embeds

**Comment by Goldenfreddy0703** [comment]
Hey so im going to go ahead and close this but if you were encountering subtitle issues with zoro, @Gujal00 fixed that yesterday.
