### ISSUE TITLE
Case closed series can't play

### ISSUE THREAD

**Issue by Darkrepo23** [Goldenfreddy0703/Otaku#111]
I'm trying to watch detective Conan series but it can't play. I hope it fix thanks

**Comment by Goldenfreddy0703** [comment]
What's happening? Any errors and would you mind sharing a log?

**Comment by Darkrepo23** [comment]
Where can i find the log?

**Comment by Darkrepo23** [comment]
https://paste.kodi.tv/ikukoveloh

**Comment by Darkrepo23** [comment]
And the nyaa torrent can't scrape any video

**Comment by Goldenfreddy0703** [comment]
Hey sorry I never got back to you. Ok so I found the problem with that anime, turns out to be a kitsu airdate problem. Consumet will be making a release hopefully tomorrow. 


For nyaa, it's a bit buggy for huge anime series with seasons. It's best to use embeds with it.
