### ISSUE TITLE
Playback/metadata scraping from local library

### ISSUE THREAD

**Issue by TheColorman** [Goldenfreddy0703/Otaku#112]
Are there any plans on supporting a local library? I have all of my files downloaded to network storage and would like to play off of those.
E.g. I would basically want Otaku to function as a scraper for my existing files, while also updating my watchlist, as there aren't really any good anime scrapers out there.  
(Another facet of this is that I'd like to be able to see anime in the "TV Shows" section (Kodi and Yatse) with all the features that comes with that, such as downloads)

**Comment by Goldenfreddy0703** [comment]
I'm not too sure cause I don't think Seren has that either but if I'm correct, once we get a Otaku player for tmdb helper, it's possible to scrap from tmdb helper I think and you could be able to choose a player of your choice to play your library stuff. Hopefully that answers what you were asking.

**Comment by Goldenfreddy0703** [comment]
Hey im going to go ahead and close this issue but hopefully in the future, we can get a tmdb helper player working in the coming weeks.
