### ISSUE TITLE
playback error/ meta issue

### ISSUE THREAD

**Issue by Thor4201** [Goldenfreddy0703/Otaku#114]
hey there so I've been having a play around with stuff and ran into this issue, anime is " Is It Wrong to Try to Pick Up Girls in a Dungeon? II"
season 1 displays correct, season 2 does as well except for zoro won't play it nor does the next up function properly, and no information for the episodes, season 4 part 1 displays episodes numbers but no names or meta. I also noticed the zoro playback issue on  "Hells paradise". error in log below im not sure where to start or I'd dive in more. This is the zoro playback error, it only does it on certain shows, otherwise it's my go to for anything. 
Error Contents: cannot use a string pattern on a bytes-like object
                                                   Traceback (most recent call last):
                                                     File "\addons\plugin.video.otaku\default.py", line 21, in <module>
                                                       main.Main()
                                                     File "\addons\plugin.video.otaku\resources\lib\main.py", line 1858, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "\addons\plugin.video.otaku\resources\lib\main.py", line 1715, in PLAY
                                                       player.play_source(link,
                                                     File "\addons\plugin.video.otaku\resources\lib\ui\player.py", line 494, in play_source
                                                       subtitles.append(utils.get_sub(sub_url, sub_lang))
                                                     File "\addons\plugin.video.otaku\resources\lib\ui\utils.py", line 48, in get_sub
                                                       replacement = re.sub(r'([\d]+)\.([\d]+)', r'\1,\2', content)
                                                     File "Kodi19\system\python\Lib\re.py", line 210, in sub
                                                       return _compile(pattern, flags).sub(repl, string, count)
                                                   TypeError: cannot use a string pattern on a bytes-like object
                                                   -->End of Python script error report<--

**Comment by Thor4201** [comment]
Ahh I see a Zorro fix recently I'll update and see if that's what it is, after reading the logs and everything like I probably should have to begin with... I think you guys might of fixed the zoro issue? 
- The rest isn't really much to worry about.

**Comment by Goldenfreddy0703** [comment]
Hey sorry i never released an update yesterday, reason why i never pushed this release was cause in the coming months, consumet will be shutting down very soon. We are working to add zoro from enime api in the future which will help alot of users. Some episode meta for animes may not show due to release or broken episode meta, hopefully consumet can fix that but im not sure at the moment. I might release tomorrow maybe so hopefully this will fix your issue. 

Btw, sometimes zoro works, other times zoro can sometimes not work for some odd reason.

**Comment by Goldenfreddy0703** [comment]
Hey so glad this fixed your issue but if you have debrid and run into some scrapping problems where seasons or parts of an anime are not correct in a list. Make sure to enable a few priority settings that will resolve scrapping for torrents. Im going to to go ahead and close this issue but if you have any other questions, feel free to ask.
