### ISSUE TITLE
Zoro bug

### ISSUE THREAD

**Issue by Thor4201** [Goldenfreddy0703/Otaku#115]
Not sure if aware or to-do with something else.. before I updated my local consumet and the latest files for Otaku I was getting zoro links for pretty much every episode of a series. most zoro links will only display the first episode of a show now, after updating stuff. tried spy x family no dub links beyond episode 1, vermeil in gold no zoro links today was getting them the day before for this show,.

**Comment by Goldenfreddy0703** [comment]
Hey so if your a dub person and not hosting consumet yourself, dub links for zoro will sadly not work for you cause we added only sub embeds from enime. One suggestion I suggest is hosting consumet. To host consumet go to addon settings and go to the maintenance catagory and there should be a setting for it and some instructions as well as long as you have a local pc with windows, you should be good.

**Comment by Goldenfreddy0703** [comment]
Btw consumet shutdown sadly due to api cost and all. It's sad but there are always alternatives and stuff.

**Comment by Thor4201** [comment]
Hey I'm already hosting consumet, dub links still aren't working properly for zoro. Eg first episode of spy x family episode 1 is the only episode that shows dub zoro links, another example is vermeil in gold episode 1 is the only episode that shows a zoro link

**Comment by Thor4201** [comment]
Hey I'm hosting consumet myself and zoro links still not showing up eg first episode of spy x family is the only episode that'll show a zoro link episode 2 and down doesn't show any zoro links, another example is vermeil in gold episode 1 displas a zoro link then episode 2 on doesn't display zoro

**Comment by Thor4201** [comment]
Ok figured it out, It's a consumet bug from their recent update to their consumet files, I'm going to look over their stuff and see. Thankful for keeping copies on my desktop.
