### ISSUE TITLE
Kodi Omega Alpha 1 playback issue

### ISSUE THREAD

**Issue by OdinIsLord** [Goldenfreddy0703/Otaku#119]
Otaku finds sources through Real Debrid but when you click on a source it just does nothing and falls back to episode browsing. Fen or Seren play Real Debrid sources without issues.

**Comment by OdinIsLord** [comment]
Sorry if I opened a false issue btw. The first week of the alpha release, I tried it and no add-on was resolving links including Otaku, but today I tried again and everything on my build worked and was much faster than Nexus. InputStream adaptive Omega update a couple days ago was the icing on the cake. I'll rollback to 20.1 and get back to the waiting room.

**Comment by Goldenfreddy0703** [comment]
Oh it's ok, you didn't really open a false issue cause technically you are right sense I tried this with latest build as well, my guess would be that it could have something to do with inputstream adaptive so hopefully they will fix that in the future. I may wanna keep this issue open for a bit longer cause I wanna do some testing with it in the future.

**Comment by Gujal00** [comment]
Kodi Omega Alpha 1 snapshot had a bug where it wouldnt play when you select an item, you had to select context menu and select play for it to work
This was fixed a week later in the nightlies and the current 21 nightlies are fine. I would either run 19 or 21, Kodi 20 is too buggy for my tastes

**Comment by OdinIsLord** [comment]
> Kodi Omega Alpha 1 snapshot had a bug where it wouldnt play when you select an item, you had to select context menu and select play for it to work This was fixed a week later in the nightlies and the current 21 nightlies are fine. I would either run 19 or 21, Kodi 20 is too buggy for my tastes My daily driver is CoreElec 21 nightly (based off Kodi 21 nightly) and has been fantastic

I didn't know the Master folder had Omega nighties in it. Latest nighty runs Otaku without issues.  Thanks for the reply.
