### ISSUE TITLE
Language and Sub/Dub filtering

### ISSUE THREAD

**Issue by snoweuph** [Goldenfreddy0703/Otaku#12]
I would love to have a way of Filtering for Language and Sub/Dub.

I personally speak German and English and Prefer Sub.
Sadly for me some Animes have Languages I can't use. One example is "Domestic no Kanjo", which for me only is there in Spanish Sub. On the other side I've got "Hunter x Hunter" with only Japanese Dub.

I use Debrid and GoGo Sources.

Some way of Filtering these out would be quite helpful to find Something that I want to watch and actually can understand.

If this is a problem with the sources Debrid uses and it's not in the power of this addon to do something about it, I would love a way of Marking them Myself/Hiding specific ones.

**Comment by Goldenfreddy0703** [comment]
Hey there, I kinda don't understand what you mean with the Sub/Dub filtering but if it helps, There are a few things you could try that could help you get the right sources and subtitles when you need them. 
**Option 1**
For Audio, i recommend doing this:
![image](https://user-images.githubusercontent.com/62456796/190516419-43079c67-2c76-469b-8fc0-f321141778ff.png)
Ok so for Playback, I also like to make my audio stream Japan, if you are looking for Dub audio sources, change that from jpn to eng and that should help you
![image](https://user-images.githubusercontent.com/62456796/190516837-903c1949-75bf-4c4b-8d0b-0fa27ce5b6d2.png)
For Sort & Filter, i like to filter out Hide Dub Sources which only looks for Dub sources, if you are looking for Dub sources, uncheck this option
**Option 2**
For Subtitles and also Audio 
![image](https://user-images.githubusercontent.com/62456796/190517327-7c137f3b-4928-4f9f-82ac-af0a29c31ae9.png)
In your kodi Player Settings in your Language Category, you have these options where you change your audio or subtitles language to whatever you like. This should help you alot and should probably also fix your issue. 

Configure both of those options i mentioned and tell me if that helps you out.

**Comment by snoweuph** [comment]
The fix was actually quite easy: switch from Debrid sources to gogo. Now everything is fine

**Comment by Goldenfreddy0703** [comment]
Ahh ok, if you have any other questions, pls feel free to ask.

**Comment by snoweuph** [comment]
Actually there is one: does this addon support hanime as source?

**Comment by Goldenfreddy0703** [comment]
Sadly i don't think so but there is a hanime addon for that. In the or in a couple of days, we are going to add more gogo streams and animixplay as well as well at some other features we are preparing.

**Comment by snoweuph** [comment]
Nice, thx for the information :)
