### ISSUE TITLE
dont load  episode list

### ISSUE THREAD

**Issue by zambux** [Goldenfreddy0703/Otaku#120]
https://paste.kodi.tv/ululowuqok.kodi

guive this erros in some animes

**Comment by Goldenfreddy0703** [comment]
Hey sorry i was busy but from looking at your log, it looks like one of the api's could be down in your country or something. Try going to these website and tell me if you got a response from all of them. 

https://api.consumet.org/
https://api.enime.moe/
https://anilist.co/home

Ok are you able to access these three websites?

**Comment by zambux** [comment]
Yes i Ken enter in the three websites, the animes that make This erro are chinise anime, bot some other chinise anime work ok.

**Comment by zambux** [comment]
Some off animes that are making This erro hare.
Kao Ni La! Zhanshen Xitong, Dawang Raoming, Xian Wang De Richang Shenghuo, Yingxiong Zailin

**Comment by Gujal00** [comment]
I dont think enime or consumet cover Donghua

**Comment by Goldenfreddy0703** [comment]
ahh, that could explain alot sense Donghua is Chinese Anime but i tried Simkl and all the animes mentioned above shows on Simkl except Yingxiong Zailin.

**Comment by zambux** [comment]
tanks

**Comment by zambux** [comment]
working just fine whit last version, what a notice is that zoro scraper isn't getting sub.

**Comment by Goldenfreddy0703** [comment]
> working just fine whit last version, what a notice is that zoro scraper isn't getting sub.

That's cause with Chinese Anime you don't really get any embeds except if its from the gogo or animepeha sources. If you have a debrid account, you should be able to scrap them with nyaa to help you.

Btw im closing this issue sense its been resolved but glad we could fix your issue.
