### ISSUE TITLE
Ranma 1/2 gives error when loading series

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#121]
Ranma 1/2 full series won't load and gives an error.
https://anilist.co/anime/149939/Ranma--1989/
![otaku error](https://github.com/Goldenfreddy0703/Otaku/assets/43726430/7a7cf0a7-d563-446b-b380-77cba99220a9)

**Comment by Goldenfreddy0703** [comment]
Ok well this is surprising interesting, do you use anilist, mal, or kitsu for your watchlist?

**Comment by Liquidrag** [comment]
Anilist. It was working before but for some reason anilist removed the listing and my watched status and now the series is back but my watched is gone.

**Comment by Gujal00** [comment]
Anilist removed the series and readded with resequenced episodes and shows. Try rebuild database and see if it fixes the issue. Watched markers come from anilist, if they have changed the id/shows then they are lost, cant do anything in the addon about ut.

**Comment by Liquidrag** [comment]
How do I know when the database has rebuilt? I clicked it and it doesn’t look like it’s doing anything

**Comment by Gujal00** [comment]
database rebuild was silent, have added notification now. Also coded around this troublesome anime, so should show episode lists in the next release

**Comment by Goldenfreddy0703** [comment]
Hey so release should be out so give it a test and tell us if its working and we will close this issue. Big Thanks for @Gujal00 for fixing this issue!!!

**Comment by Liquidrag** [comment]
Thank you. Yes, it shows now but nothing scrapes/plays in it. Is that something you can fix or is it probably a file naming issue?

**Comment by Liquidrag** [comment]
Thank you. Must be something in my filters. We can close this issue
