### ISSUE TITLE
Next video and subtitles issue 

### ISSUE THREAD

**Issue by unicornsandcandies** [Goldenfreddy0703/Otaku#126]
From some time now (probably recent updates, not sure if it's the newest one fault), after one episode of anime ends and the next starts subtitles just disappear. 

Currently I see this on Stop! Hibari-chan, source picked from my debrid cloud (embeds aren't loading for me). Not sure if I can post torrents here so I'll just say that it's the most seeded one on nyaa.

Behaviour:
1. Start anime
2. Wait till the episode ends
3. It's scraping all over again for the next episode
4. Episode plays with no subtitles and it seems like they're being forced off (both yatse and kore say they're disabled and when I pick one, it's disabling itself)

Possible add-ons on my build that could interfere with subtitles (I highly doubt that's it, but telling just to help):
a4ksubtiles

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at this anime, this anime is pretty old and i cannot find any torrents for it, It could be a cloud source issue sense we have not messed with cloud sources in a long time. Luckily i managed to find a workaround, if you enable GogoHD Provider you should be able to get the embeds from there as well as the subtitles for every episode. Hope this helps but i will still look onto this issue. 

Real quick could you also try another anime that is new and see if the cloud does the same as well? If you could that would be great. Oh and could you also provide a log as well?

Oh btw a4ksubtiles does not interfere cause i use a4ksubtiles as well.

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this issue but in the future, we will take a closer look with cloud sources someday and hopefully they can do well in the future. If this issue still persist, pls feel free to reply again and i can open this issue back up.
Thank you
