### ISSUE TITLE
Anilist Language

### ISSUE THREAD

**Issue by Guacan0le** [Goldenfreddy0703/Otaku#13]
I have the title language set to English in both the addon and on Anilist itself, but when the addon pulls my list it’s in Romaji. The rest of the addon works as it should. Is there a way for me to get the pulled lists from Anilist to be English as well?

**Comment by Goldenfreddy0703** [comment]
Hey there, by anychance did you go to the tools menu and clear cache, clear torrents, and rebuild database?

**Comment by Guacan0le** [comment]
I have tried those steps.

**Comment by Goldenfreddy0703** [comment]
Oh I see what you mean, about that. @Gujal00 probably may have a fix for that soon maybe. Thank you for pointing that out to us.

**Comment by Guacan0le** [comment]
For sure. Thank you for all you do.

**Comment by Goldenfreddy0703** [comment]
Hey @Guacan0le, when your available go ahead and test our newest version and tell us if that fixed your issue.

**Comment by Guacan0le** [comment]
@Goldenfreddy0703 Looks to be working perfectly. Thank you!

**Comment by Goldenfreddy0703** [comment]
Hey anytime but this is all thanks to @Gujal00 for fixing this issue.
