### ISSUE TITLE
Zoro domain acquired and moved

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#130]
Zoro.to was acquired and moved to Aniwatch.to. I am assuming this is why no Zoro links are showing up for me?:

https://torrentfreak.com/zoro-to-worlds-largest-pirate-site-suddenly-acquired-rebranded-230704/

**Comment by Goldenfreddy0703** [comment]
heyyyyy so we are already aware of that and were just talking about that yesterday. We will add zoro or aniwatch soon hopefully in the future. Im going to close this but thanks for pointing this out.

**Comment by meesterexx** [comment]
Thanks!!
