### ISSUE TITLE
Zoro/aniwatch no playback and crash windows 10/11

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#131]
I know you guys just recently did fixes for this, On my phone I dont have an issue that I've noticed anyway, but on my computer {windows} they either don't play or it crashes Kodi altogether, tried multiple different titles and I'll either get a pop up unable to resolve, a crash, or it tries to load then it stops with no pop up. I cleared everything as well and tried with the same results. If anyone on the team thinks I could try something else to test it let me know.

**Comment by Goldenfreddy0703** [comment]
Ok yeah, we should have mentioned thise. UK has some geolocation thing prevents UK users to use zoro sadly. Sorry I didn't mention this in our latest release, I honestly thought people would disable zoro.

**Comment by theasguard** [comment]
I'm not located in the UK, I'm Canadian. I'll figure it out myself since it works fine on my phones kodi.

**Comment by Goldenfreddy0703** [comment]
Oh I thought Canada was in the UK, my bad. Ok well sense it works fine on your phone, it's possible that you used your phone mobile data to see if there working. Did you test that or used the wif?

**Comment by theasguard** [comment]
Hey no problem, lots of similar names throughout the world.
yea they both work, mobile and WiFi, only thing that's different is on my phone it's running kodi 20.2 newer version than my computer is on. I'm going to try out a latest kodi version on my computer and see if thatll solve it. Thanks for replying on a weekday

**Comment by Goldenfreddy0703** [comment]
Interesting tell me if the latest 20.2 versions works for you. We assumed it was a geo location problem but it might not.

**Comment by theasguard** [comment]
Hey so I upgraded kodi on my computer to 20.2 and all plays well again with zoro/aniwatch
Looks like the lower kodi versions can't resolve them properly.

**Comment by Goldenfreddy0703** [comment]
> Hey so I upgraded kodi on my computer to 20.2 and all plays well again with zoro/aniwatch Looks like the lower kodi versions can't resolve them properly.

Ok very interesting, this must have been the problem @Gujal00 was having or it is was a geo location issue, @Gujal00 you should test this just incase cause im very curious.

**Comment by Gujal00** [comment]
@Goldenfreddy0703 My dev machine is running Kodi 21Alpha2 and doesnt play, so definitely geo issue as I can see the website on the browser provides different streams to what the zoro resolver provides

**Comment by Goldenfreddy0703** [comment]
> @Goldenfreddy0703 My dev machine is running Kodi 21Alpha2 and doesnt play, so definitely geo issue as I can see the website on the browser provides different streams to what the zoro resolver provides

Dang it, ok well it was a good try. Only question is why older versions of kodi world have playback issues with Zoro unless its just a really old kodi version like matrix or something then yeah makes sense. Ok well seems like this issue is resolved and i will be closing this now.

If issues related to this still persist, will open it back up. 
Thank you
