### ISSUE TITLE
[Request] Auto scroll links longer than the available box space

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#133]
Hey, I know the links auto scroll when using Jurial skins such as the Arctic Horizon series, etc. However, if you're for example using Esturay. When the link info exceeds the available box space in the Source Select UI, the info remains static and you cannot make up for the remaining text. 

Is it possible to implement some sort of auto scroll for when the link naming exceeds the limit of the available box space within the Source Select skin UI. Something more of universal meaning, it doesn't matter which Kodi skin you're using and the links will auto scroll automatically showing the remaining info.

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/cebaff73-0a1f-4579-9b3f-6ea567d6c88c)

This is what I mean, as you see in the screenshot with the arrow pointing. The remaining text from the link stays hidden and no auto scroll when using Estuary Kodi or FENtastic skin, which is a MOD version of Estuary with some minor visual changes but still Estary at it's core.

**Comment by Goldenfreddy0703** [comment]
Possibly, I will look into it soon

**Comment by Nuklear92** [comment]
Thanks!

**Comment by Goldenfreddy0703** [comment]
Hey @Nuklear92 we fixed the autoscroll but and we added new feature where you can hide spoilers and stuff so yeah. Release should be out in a few min. 

Im going to go ahead and close this but if you run into problem, feel free to reply. 
Big Thanks to @joezito129

**Comment by Nuklear92** [comment]
Awesome! Thanks @joezito129 @Goldenfreddy0703 for the quick fix, appreciate it. 💙😃
