### ISSUE TITLE
"Otaku error check the log for more information"

### ISSUE THREAD

**Issue by Alex12345678jour** [Goldenfreddy0703/Otaku#134]
It was working fine when suddenly while switching episodes, the addon gave me the error above and will no longer work. I can't clear the cache or anything it will only show this error. I tried re-installing the addon and still get this error. The log doesn't show any issue when checked. Any advice?
![ErrorMessage22](https://github.com/Goldenfreddy0703/Otaku/assets/46139469/8933f5c6-cacb-4210-b8e7-9e6ebb5cceab)

**Comment by Alex12345678jour** [comment]
Update, after play around with a few settings, BE ON THE LATEST VERSION OF KODI THAT YOU POSSIBLY CAN BE and then force refreshes on everything! Problem solved :)

**Comment by Goldenfreddy0703** [comment]
Glad to hear that, it was probably a database issue or something.
