### ISSUE TITLE
no Nyaa results without vpn connection  

### ISSUE THREAD

**Issue by d7mi91** [Goldenfreddy0703/Otaku#135]
i know it seems that my ISP blocked https://nyaa.si/ but that not actually true because i can access the website via browser without vpn turn on and downloads torrents and used them with no problem  

i try:
-nyaa alt
-Troubleshooting Tips
-uninstall addon @ new clean install 
- new ip from isp internet 
 
 nothing worked for me without vpn connection  

log file https://paste.kodi.tv/edukuvekuf

log file with vpn on & debug logging https://paste.kodi.tv/odupeticej

**Comment by Goldenfreddy0703** [comment]
Mmm that is odd and your using windows.

- Turn off your vpn, open Otaku, authenticate your debrid and try it again and see if that works.

**Comment by d7mi91** [comment]
already did 1 & 2 so i jumped to 3 with some help from google how to  Disable ipv6 on win11 and its works!
 thanks a lot man i appreciate

**Comment by Goldenfreddy0703** [comment]
Anytime
