### ISSUE TITLE
Favorites not updating on new episode 

### ISSUE THREAD

**Issue by Tony322** [Goldenfreddy0703/Otaku#137]
If I have an otaku anime added to favorites, and a new episode comes out. If I open the anime via default Kodi favorites, the new episodes are missing. Seem to be a cache issue. Not sure if addon or kodi issue tho. Whenever I open the anime in my favorites via the addon, and not the Kodi favorites, I can see the new episodes. Is the addon at fault or kodi? What can I do to prevent this? Best anime addon ever btw. I will donate :)

**Comment by Goldenfreddy0703** [comment]
Not too sure but new episodes from Otaku do take time to update cause some animes have missing airdates for episodes and hopefully there will be a better solution for that soon. For Kodi favorites, if you looked on favorites and left your kodi on for awhile and check your favorites again, that could probably be the reason favorites did not update.

**Comment by Tony322** [comment]
I shutdown Kodi and my Nvidia shield daily. And yet episodes are missing. If I enter otaku addon and enter my favorites manually the new episodes show up. As I said, it might be Kodi issue, not an addon issue. I just don't know. I felt that addon support is faster and more probable than Kodi. But I am fully aware it might be a Kodi issue. In any case. Addon or kodi issue. Is there any way to force reload ly favorites when I load em?

**Comment by Tony322** [comment]
I've almost quit many animes since I thought they died. Until i noticed new episodes don't show up when i open them from default Kodi favorites

**Comment by Tony322** [comment]
Recent example is jujutsu kaisen. I saw hidden inventory episodes 1-2 when I found the anime via the addon. Added to favorites. Weeks later the same two episodes appear. Then I go through top or popular anime via the addon, enter from there, only to see two more episodes. Hidden inventory 3-4.

**Comment by Goldenfreddy0703** [comment]
Hey sorry I was afk but interesting. Ok maybe I can look into this more, my main guess is that it could mostly be an Otaku issue. Reason why I don't think it's a kodi issue is cause seren does not have this issue when new episodes come out.

From your example and stuff. One small workaround for now is to rebuild database if you find an anime that has not populated new episodes yet.

**Comment by Gujal00** [comment]
Not an addonissue, When you add something to Kodi Favourites it adds the endpoint at that point in time and will not be updated. The addon itself will be updating episodes as it will be pulling whenever it is run

**Comment by Goldenfreddy0703** [comment]
Oh I thought it was an addon issue cause I originally thought favorites was like an addon shortcut to the movie or tv show. 

Thank you

**Comment by Tony322** [comment]
Thanks for the amazingly quick replies!

> Not an addonissue, When you add something to Kodi Favourites it adds the endpoint at that point in time and will not be updated. The addon itself will be updating episodes as it will be pulling whenever it is run

I see. That explains the issue I'm having then. Now the question remains. Is there a workaround for this? If not, you may close this. As it seems not to be a bug in the addon itself. 10/10 support btw :)

**Comment by joezito129** [comment]
I believe this is an addon issue, the database for the show should be cleared (every so many days) when clicking on a show to re-fetch new episodes .

**Comment by Goldenfreddy0703** [comment]
Hey @Tony322 , in the future we will be adding a new system in the future that helps update episode meta whenever new episodes come out and all. Will take some time tho but we will have it added eventually. 

Huge thanks to @joezito129 for teaching me alot of stuff and for showing me the features you have added.

**Comment by Gujal00** [comment]
> I believe this is an addon issue, the database for the show should be cleared (every so many days) when clicking on a show to re-fetch new episodes .

Correct, noticed it after testing without a watchlist account setup and indeed it does not refresh for animes without airdates provided by consumet.

If you have a watchlist account and favourite from inside the watchlist menu next-up then it always gets the next episode if aired

**Comment by Goldenfreddy0703** [comment]
> So, yes it is an error with the addon but cant be fixed when the metadata provider (consumet) does not provide airdates

That is true but it can be fixed even if our metadata provider does not provide airdates. joezito has this idea and has code where if the episode length does not match the one from the database, it will clear the database for that anime. If the episode length does match the one from the database, it will not clear the database and will pull it up from the cache.

**Comment by Goldenfreddy0703** [comment]
Hey @Tony322 good news, this took a bit long to code but we finally got it where database should update whenever a new episode comes out. Test our latest release for a few days and see if its working. If not, pls feel free to contact us in the issue and we will find other ways. 

Im going to go ahead and close this but im glad this issue was fixed. Thank you

**Comment by Tony322** [comment]
> Hey @Tony322 good news, this took a bit long to code but we finally got it where database should update whenever a new episode comes out. Test our latest release for a few days and see if its working. If not, pls feel free to contact us in the issue and we will find other ways.
> 
> Im going to go ahead and close this but im glad this issue was fixed. Thank you

Absolutely fantastic! You guys are great! Thanks for everything. Will be testing it out asap :)
