### ISSUE TITLE
Scraping not recognizing Season 2 of a particular TV show

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#139]
Scraping a TV Show like; 

**Malevolent Spirits: Mononogatari Cour 2** 

Which is the Season 2 of **Malevolent Spirits: Mononogatari** as a separate title if you search in Otaku. The scrapping won't return anything from Nyaa, AnimeTosho as it thinks it's the Season 1 since it's a separate title and first episode is named as Season 1, Episode 1. But in reality is Season 2, Episode 1.

Here are some screenshots with proof;

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/f7da3123-a313-4db3-9db3-6f396d7a9d0c)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/c1bd2807-273f-4d76-9cc4-3be56cd3c096)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/24189665-4be9-4a7c-83a4-20465f54421e)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/7070bf96-9c38-4d57-9bb7-87535620cd0b)

The 4th screenshot is a search I performed in AnimeTosho website to confirm there are the episodes of Season 2 available. Again, Otaku and the scraping is recognizing the Season 2 as Season 1 and getting confused with returning the right episodes. As you also see in the scraping results, it does return the embed and other sources episodes correctly but not the torrent sources.

This is mainly happening if the title of a separate season is marking the episodes as S01,E01. For example other titles that have each season as a separate title, like **My Hero Academia** season 2 which in otaku shows as **My Hero Academia Season 2** the episodes are marked correctly as Season 2, Episode 1, etc. Therefore the scraping doesn't get confused and returns the results for the torrent sources correctly. 

The only issue so far that I have found is with this tv show Malevolent Spirits which the Season 2 as you see therefore not returning torrent results correctly. Is there any potential fixes for something like this? 🤔

**Comment by Goldenfreddy0703** [comment]
Wait a sec, that is really weird especially in the first image you sent. The title says cour 2 which means part 2 but the description says season 2 which is very weird. Is it a continuation of a season or is it season two like I'm confused? This isn't like a torrent scrapping error, more like a title and description issue from anilist. I will try to look into it tho and see if there is a way where I can make an option for the user to specify the part or season of an anime. 

Thanks for pointing this out.

**Comment by Nuklear92** [comment]
I believe it's a continuation, because the first episode is literally right the events of the last episode of season 1. 

Also, I've noticed that the results are still leaking wrong episodes on some titles and specific seasons. For example **My Hero Academia Season 3**. If you search for it and scrape any of the episodes, you still get a bunch of random episodes in the mix of the results. Hopefully you can double check in your end and see if you're getting the same results. 🤷‍♂️

**Comment by Goldenfreddy0703** [comment]
Hey weird question but what version of Otaku are you on? 
Just tried it and thought it didn't work but its somehow getting recognized as season 2 for me and you may have to rebuild database.

**Comment by Goldenfreddy0703** [comment]
> Also, I've noticed that the results are still leaking wrong episodes on some titles and specific seasons. For example **My Hero Academia Season 3**. If you search for it and scrape any of the episodes, you still get a bunch of random episodes in the mix of the results. Hopefully you can double check in your end and see if you're getting the same results. 🤷‍♂️

Hey so from looking at this anime, reason why your getting mixed results are due to how long that anime has been going on for. This anime is like one piece for example which is why you see other episodes such as 59,60,61, ect but you still get some torrents that have 3rd season 01 - 25. 

Best thing i recommend if you are getting the wrong episodes is by going into the prioritizing settings and selecting Prioritize By Season and setting that to 3 for MHA. That will help you get the correct torrents easily.

**Comment by joezito129** [comment]
I will take a look at improving the scrapping this weekend, you can always add the sources to your debrid account and it should be able to find it in cloud sources until the scrapping is improved.

**Comment by Nuklear92** [comment]
> Hey weird question but what version of Otaku are you on? 
> 
> Just tried it and thought it didn't work but its somehow getting recognized as season 2 for me and you may have to rebuild database. 
> 
> 
> 
> ![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/a8439498-67dd-40a3-82fc-0aa0f3730fb0)
> 
> 
> 
> Edit: Actually i may have found the problem and it has something todo with our enime provider. 

I'm actually using the latest Otaku. I always update as soon as you release a new version. I also just tried rebuilding database and still getting the same results. 🤔

**Comment by Nuklear92** [comment]
> I will take a look at improving the scrapping this weekend, you can always add the sources to your debrid account and it should be able to find it in cloud sources until the scrapping is improved.

Hey, thanks! I appreciate all the work you had been putting into making the scraping more accurate and better. 💙😃

**Comment by Goldenfreddy0703** [comment]
Hey @Nuklear92 good news, we fixed Season Guessing and now it should pull up the correct season for this anime and the correct torrent results. We also fixed the Animetosho scrapping. Huge thanks to @Gujal00 for fixing this and will close this issue. 

If you have any more problems relating to this issue, feel free to reply back and we will look further into it. 
Thank you

**Comment by Nuklear92** [comment]
Just updated the addon with the fixes and indeed it's working flawlessly now, results are showing correctly! 

Appreciate all the work you and the contributors are doing for this addon. ❤️😃

**Comment by Nuklear92** [comment]
@Goldenfreddy0703 hey, seems like Bleach: Sennen Kessen-hen aka Thousand-Year Blood Part 2, that's currently being released weekly. 

Seems to be having the same issue, results only pull two sources from torrents which both have Chinese subtitles instead of English. 

There seems to be quite a few links available when you search manually by visiting either AnimeTosho or Nyaa website. And cached into the debrid service, however not being shown in the results after the scraping is completed. Here are some example screenshots, hopefully you can double check in your end and see if you're getting the same results.

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/291fce79-9d1e-4bb7-a1d5-d95a16374b14)

As you see there's plenty of links from the latest Episode 5. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/00ff7692-2bbf-4513-94d9-96e6d37fec82)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/bb780b86-6606-4ec8-b764-19c8c21a90e8)

I already manually cached one of the links in my debrid cloud in the meantime. But, this is happening to every episode so far from Episode 1 through the recent one 5th. Every episode only pulls those two same links which has Chinese subtitles. And none of the English sub links that you see are available for each episode when manually searched via the torrent websites.

**Comment by Goldenfreddy0703** [comment]
Hey so from doing some research on this anime. This anime is the 17th season and we have no way detecting that in the titles nor the Synonyms. Your may wanna use embeds for this one cause embeds are very accurate then torrents. We do see that you have webresults and we also found that nyaa can find this then animetosho but animetosho does not have good title matches. In the future, we may improve scrapping involving titles but for now, just use embeds or nyaa and you should be good. 

Btw reason why it says Season instead of Part 2 is cause our Get Season function tries to find season or part or cour in the title but for Synonyms, we have it look for season but we don't have it look for part or cour in the synonyms.

**Comment by Nuklear92** [comment]
I see, I mean I can deal with caching the link manually in the debrid cloud. Just that I wanted to point it out as it seems the root cause for this seems to be as you said that the scraping doesn't look for Part or Cour instead a Season. The Bleach: Thousand-Year Blood that's currently airing is the Part 2 or continuation of the first Season of it which I don't get why they wanna divide these shows in parts instead of just going straight in numbers like; if the first season had 13, episodes. Then just go on for "Part 2" and start Ep.14 and on. 🤷‍♂️

**Comment by Goldenfreddy0703** [comment]
Hey @Nuklear92 good news, Our team was able to improve Anime Tosho scrapping and get you alot of great results and it turns out Season was not needed as much as i thought. Huge thanks to @Gujal00 and @joezito129 for working on this issue and improving scrapping. 

Thank you.
