### ISSUE TITLE
Would be great to see some seren/fen style scraping features.

### ISSUE THREAD

**Issue by SlimJim192** [Goldenfreddy0703/Otaku#140]
I think it would be great to see some scraping improvements/options particularly from episode to episode scrapes. Something like Seren or Fen.

One of them does a kind of pre-emptive background scrape towards the end of an episode, and I think the other just spits out the same results as last time (no rescrape). Sorry I cant recall which does which ha.

Personally I think I preferred the cached scrape, most of us are skipping outro anyway, so notmuch time for a pre-emptive scraping -- perhaps with a button to do the proper scrape if you are suddenly jumping into another season and actually need to, although I often see many links from other seasons in the original scrape anyway, I dont think I'd need to rescrape 99% of the time if I was just shown the same options again.

Another idea is maybe the option to favourite a particular source, so that its at the top of the list on the next episode. I think this would be particularly useful when I'm seeing lots of batch/box links, or simply if I like the files by a particular uploader. I know which one I want for the next 50 episodes or so.. And then I could star the next one when the time comes.

Or even more automated would be to just stick to the previous RD source until we no longer find the episode (skip selection/scraping altogether until it fails).

Another (potentially easier to achieve) angle on this is pre-emptive termination. I.e terminate scraping if RD cloud file is found (I think RD cloud files are scraped first). I could mostly solve the above issue(s) (lots of batch sources and long scrape) by adding the source I want to my RD Cloud, and adding the next one when/if I need to. I'm pretty sure this is also done by Seren/Fen too. 

Many thanks.

Appreciate all the work your doing!

**Comment by joezito129** [comment]
Definitely will add a terminate on cloud sources. So otaku automatically adds your shows to your account but automatically deletes it when it starts playing. Maybe have a way to chose a specific source not to delete it from your cloud. Defintly will look into this.

**Comment by SlimJim192** [comment]
That sounds great, how about long press a source->add to cloud (and also an option to remove if its already in cloud?).

Maybe a button to redo full scrape if its ever needed, sometimes maybe one episode might have an issue with a source (bad file name or something) but not often.

I dont mind it not being completely automated, sometimes human intervention is necessary (moving to the next batch or a bad filename). And I guess fully automatic could be tricky knowing when to delete and when not to delete etc.


I'd be super happy with just the early termination initially.

I really dont mind going on nyaa and adding to my cloud myself if its going to save me scrape and source selection time for the next 50 episodes.

Of course if it can all be done in the addon that would be awesome.

But I already do this if my preferred source is particularly far down the list, not always in a consistent position etc. It's my current "hack" to favourite a source.

**Comment by Goldenfreddy0703** [comment]
Hey so me and @joezito129 thought about this and i think we basically completed everything these features has to offer. About the pre-emptive termination, we basically have a system for that where it would scrap and play the same batch or embed or cloud. Sure it would go thought a quick scrapping screen but its only for a second and thats not too bad. 

We are gonna go ahead and close this but if you have any issues, concerns with these features, please feel free to reply and we will open this back up.

Thank you
