### ISSUE TITLE
custom sites ?

### ISSUE THREAD

**Issue by Urbexed** [Goldenfreddy0703/Otaku#142]
It would be nice to be able to add anime streaming sites of our own so that we could watch anime in languages other than English, for example.

**Comment by Gujal00** [comment]
Rather you could contribute to the code here, so that everyone benefits

**Comment by icarok99** [comment]
If one day this is added I will be able to watch anime dubbed in Portuguese😍.

**Comment by Urbexed** [comment]
> Vous pourriez plutôt contribuer au code ici, afin que tout le monde en profite

I don't do coding.

**Comment by Goldenfreddy0703** [comment]
Hey sorry i never replied but about the custom sites. We do not plan to let the user add the custom sites cause adding custom sites would be really hard to add cause you would have to do some things and all and sites have different ways for encryption and there is a cloudflare too so yeah. You can make a request for a site tho and we could possibly add it but it would take time to add and stuff. 

Im going to go ahead and close this cause we don't plan on making a way for people to add there custom sites. 

If you would like to request a site tho, put it in this discussion tab and i will look through them and see if they are worth adding or not. 
https://github.com/Goldenfreddy0703/Otaku/discussions/141
