### ISSUE TITLE
All Previous Favorites Error Out

### ISSUE THREAD

**Issue by dootsie5times** [Goldenfreddy0703/Otaku#145]
Newest Otaku version installed on CoreElec 20.
All previous Otaku anime favorites error out when clicked on.
Any new favorites added through Otaku work fine.

I didn't have this problem a few days ago.

**Comment by dootsie5times** [comment]
[kodi.log](https://github.com/Goldenfreddy0703/Otaku/files/12330887/kodi.log)

**Comment by joezito129** [comment]
I see the issue will send a fix soon

**Comment by Goldenfreddy0703** [comment]
Heyyyyy so we seemed to have made a small error during our testing but @joezito129 has fixed your issue and hopefully it should work out for. 

Im going to be closing this but if you encounter any more issues, pls feel free to contact us in this issue. 

Thank you
