### ISSUE TITLE
Error when trying to play an episode

### ISSUE THREAD

**Issue by Guacan0le** [Goldenfreddy0703/Otaku#146]
I am getting this error pop up every time I try and start scraping. I have tried clearing the cache, local torrent cache, rebuilt the database, and reinstalled the addon. Any help would be appreciated. 

![IMG_2674](https://github.com/Goldenfreddy0703/Otaku/assets/102869797/63bdf320-04f6-4f1b-b8c1-063dea305c6b)
![IMG_2675](https://github.com/Goldenfreddy0703/Otaku/assets/102869797/bf645291-08e5-45c3-91f5-5cd408fc2cd1)

**Comment by Goldenfreddy0703** [comment]
Hey so this is interesting, we didn't think an error like this that involves duration would slip through. What version of kodi and what android device?

**Comment by Guacan0le** [comment]
Kodi is v. 20.2
I’m using a Shield TV Pro

**Comment by Goldenfreddy0703** [comment]
> It doesnt have anything to do with the kodi version, It is a key error you may need to use get function instead of passing in the key. What show is this happening on.

Ahh I thought it may have something to do with the device sense we had problems with most nvidia shields in the past due to Kodi's Python Version

**Comment by Guacan0le** [comment]
> It doesnt have anything to do with the kodi version, It is a key error you may need to use get function instead of passing in the key. What show is this happening on.

Reign of the Seven Spellblades, but I’ve randomly tried some others with the same result.

**Comment by joezito129** [comment]
is this problem only on your Shield TV Pro, do you have the same problem on other devices

**Comment by Guacan0le** [comment]
I’ve only ever used Kodi on the Shield. I don’t have Kodi on any other devices.

**Comment by joezito129** [comment]
Ok, i think we found the issue, in the meantime in your settings turn on source filtering by size on and let me know if you are able to scrape.

**Comment by joezito129** [comment]
set it to hard limit

**Comment by Goldenfreddy0703** [comment]
Hey so when you reinstalled the addon, did you clear your settings? If not, try doing this cause most problems get fixed when doing that. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/36abe30e-eab6-489a-a8c5-ab27a000745d)

**Comment by Guacan0le** [comment]
> Hey so when you reinstalled the addon, did you clear your settings? If not, try doing this cause most problems get fixed when doing that.
> 
> ![image](https://user-images.githubusercontent.com/62456796/261462474-36abe30e-eab6-489a-a8c5-ab27a000745d.png)

I did a fresh install after wiping settings and everything now seems to be working! Sorry for the late reply.

**Comment by Goldenfreddy0703** [comment]
> I did a fresh install after wiping settings and everything now seems to be working! Sorry for the late reply.

No your fine, i just knew you had to wipe your settings and all in order to have everything working. That's like the one solution what works most of the time. 

Alright im gonna close this but if you run into more issues, will open this back up and we can figure it out. Glad its fixed for you.
