### ISSUE TITLE
Disable Subtitles

### ISSUE THREAD

**Issue by Urbexed** [Goldenfreddy0703/Otaku#147]
is it possible to disable subtitles?

I mean not downloading subtitles from the various anime sources.

I ask because I use autosubs to download subtitles automatically and it doesn't download anything if it detects that there are already subtitles.

(even if it's not in the language I set for autosubs)

**Comment by Goldenfreddy0703** [comment]
Not at the moment no unless you enable kodi language settings in Otaku so that it overrides the Otaku audio and subtitle category. 

I will probably add "None" as an option in the Preffered Subtitle Language setting so that you can use your autosubs with the addon. 

Thank you for pointing that out

**Comment by Goldenfreddy0703** [comment]
Hey @Urbexed , been doing alot of testing lately but manage to add the option None for the Preferred Subtitle Language setting so now you should be able to use your autosubs addon with it. Just made a release so go ahead and test it and if everything goes fine for you, thats good. 

Im going to go ahead and close this but if you do run into problem, feel free to message in here and we can look into this more.

**Comment by Urbexed** [comment]
> Hey @Urbexed , been doing alot of testing lately but manage to add the option None for the Preferred Subtitle Language setting so now you should be able to use your autosubs addon with it. Just made a release so go ahead and test it and if everything goes fine for you, thats good.
> 
> Im going to go ahead and close this but if you do run into problem, feel free to message in here and we can look into this more.

>hey thanks for your quick reply but there's a problem

>Since I set it to <<none>> it excludes all videos with subtitles. 

>Actually what I wanted is that for videos that are not in hardsubs that it just loads the video without the subtitle files, but here it searches for videos that do not contain any subtitles and then only finds videos that are in hardsubs.

**Comment by Goldenfreddy0703** [comment]
Oh I think I see what you mean. Maybe tonight or tomorrow, I can work on it and see if I can make torrent files don't get the subtitles or something like that. Will look into it soon.

**Comment by Urbexed** [comment]
> Oh I think I see what you mean. Maybe tonight or tomorrow, I can work on it and see if I can make torrent files don't get the subtitles or something like that. Will look into it soon.

okay, thanks a lot

**Comment by Goldenfreddy0703** [comment]
> Actually what I wanted is that for videos that are not in hardsubs that it just loads the video without the subtitle files, but here it searches for videos that do not contain any subtitles and then only finds videos that are in hardsubs.
> 
> Edit : I think it would be nice to have an option to exclude hardsubs videos in the results.

Hey so about what you said today, turns out its not possible sadly. Torrents are mkv files and subtitles are inside them in which we do not have control over. There is no kodi documentation on looking inside mkv files so sorry about that. 

One of our contributors @Gujal00 does have suggestion or idea on what you can do. You can set Kodi's Preferred subtitle language to forced only and maybe that will help in Kodi Player settings -> Language -> Preferred subtitle language -> forced only

Hope that helps.

**Comment by Urbexed** [comment]
> > Actually what I wanted is that for videos that are not in hardsubs that it just loads the video without the subtitle files, but here it searches for videos that do not contain any subtitles and then only finds videos that are in hardsubs.
> > Edit : I think it would be nice to have an option to exclude hardsubs videos in the results.
> 
> Hey so about what you said today, turns out its not possible sadly. Torrents are mkv files and subtitles are inside them in which we do not have control over. There is no kodi documentation on looking inside mkv files so sorry about that.
> 
> One of our contributors @Gujal00 does have suggestion or idea on what you can do. You can set Kodi's Preferred subtitle language to forced only and maybe that will help in Kodi Player settings -> Language -> Preferred subtitle language -> forced only
> 
> Hope that helps.

Ok thanks, What about excluding hardsubs?

**Comment by Goldenfreddy0703** [comment]
Wait I thought I already explained that it was not possible, actually I should have asked this first but what do you mean by hardsubs again?

**Comment by Urbexed** [comment]
> Wait I thought I already explained that it was not possible, actually I should have asked this first but what do you mean by hardsubs again?

What I call hardsubs are videos with subtitles embedded in the video, these are those whose subtitles cannot be dissociated from the video not being srt files

**Comment by Gujal00** [comment]
Then turn off all embed sites and just have nyaa, animetosho and aniwatch enabled

All the embed sites by nature have hard subs

**Comment by Goldenfreddy0703** [comment]
> What I call hardsubs are videos with subtitles embedded in the video, these are those whose subtitles cannot be dissociated from the video not being srt files

Ohhhh ok I see what you mean now, ok well hardsub embeds cannot be disabled sadly but the only embed that will help you is Aniwatch sense the subtitles are not hardsubed for that embed. The only providers that are not hardsubed is Nyaa, Animetosho, and Aniwatch.

**Comment by Urbexed** [comment]
> > Ce que j'appelle les hardsubs sont des vidéos avec des sous-titres intégrés dans la vidéo, ce sont celles dont les sous-titres sont indissociables de la vidéo n'étant pas des fichiers srt
> 
> Ohhhh ok je vois ce que vous voulez dire maintenant, ok eh bien les intégrations hardsub ne peuvent malheureusement pas être désactivées mais la seule intégration qui vous aidera est Aniwatch sens que les sous-titres ne sont pas hardsubed pour cette intégration. Les seuls fournisseurs qui ne sont pas sous-titrés sont Nyaa, Animetosho et Aniwatch.

I meant disable them in the results

**Comment by Goldenfreddy0703** [comment]
uhhhh I mean you are able to disable them in the provider category if that helps, the three embeds i mentioned above is ones you should keep enabled and you can disable the others in order to disable them in the results if that's what you mean. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/67b856b4-7861-4024-a537-b78a42de8211)
