### ISSUE TITLE
English audio no longer automatically selected on dual audio sources since recent updates.

### ISSUE THREAD

**Issue by SlimJim192** [Goldenfreddy0703/Otaku#148]
Hi all,

Since today the add-on seems to not be selecting English audio automatically on dual audio sources.

I have tried both manually selecting English resaving, and also tried the use Kodi preferred language settings. Cleared cache both times, also tried quitting/restarting.

Many thanks

**Comment by joezito129** [comment]
![Screenshot_20230819_165323_Kodi](https://github.com/Goldenfreddy0703/Otaku/assets/60677138/acf030d0-b895-4659-a88c-84e275539bd9)
Change the kodi setting to english as seen above.

**Comment by icarok99** [comment]
Leave it that way it will give priority to the dubbed anime.

![Screenshot_2023-08-19-18-23-58-377_org xbmc kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/66a63691-088d-4f45-a596-1100529a763c)

**Comment by Goldenfreddy0703** [comment]
Hey sorry i was busy, that could have been mys fault due to working on adding a "none" option for the subtitles, i will look into this today and see if i can fix it. Again, really sorry but will have it fixed. 

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey @SlimJim192 real quick, can you answer few questions for me. 
Whats you version of Kodi?
What device are you using?
Could you tell me what animes you tried this on?
Lastly what does you kodi language settings look like? This is how i have mine. 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/c394487b-737d-468a-ab5e-701ec51dc166)

**Comment by Goldenfreddy0703** [comment]
Hey @SlimJim192 , so funny story, turns out i forgot to add an important line of code 😅
Anyway release should be out but would like you to test whenever you have time. Hopefully this should fix it. Btw forget about all those questions.

**Comment by Goldenfreddy0703** [comment]
Heyyy @SlimJim192 im gonna go ahead and close this issue but hopefully your issue has been fixed. A re code was required yesterday and i've been doing alot of testing so looks like everything is good so far. If you have any issues, pls feel free to respond and we can open this issue again thank you. 

Btw @joezito129 sorry for pinging in here but if you could help me with aniskip tonight, that would be great. Thank you

**Comment by SlimJim192** [comment]
@Goldenfreddy0703 

Sorry I went MIA,  thanks for getting this sorted!
