### ISSUE TITLE
Show unaired episodes 

### ISSUE THREAD

**Issue by guenguer** [Goldenfreddy0703/Otaku#150]
Pleas give us an option to show unaired episodes, because air dates are off sometimes (mostly tmdbs fault). So the episodes are out but we can't see them.

Or did I just miss that option somewhere?

**Comment by Goldenfreddy0703** [comment]
Ok odd, we just recently fixed it where if episode length does not match, it will check database for new episodes. Which anime is it?

**Comment by Goldenfreddy0703** [comment]
Hey so it's been around a week sense you responded to this issue so I'm probably going to close this but if it helps. We get our episode meta from either simkl or enime and sometimes episodes do get update early on there database so hopefully by the time your reading this, the unaired episodes should be updated by episode length.

Hope this helps, I'm going to close this issue but if you have any concerns or questions or would like to open this issue again. Reply here and I will respond.

Thank you
