### ISSUE TITLE
Sync/show watched indicators anilist

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#152]
Hi again! I've searched but did not see any posts so sorry if it has been asked before. I sync with anilist and I know there's a "completed" section but when I go into a series, there's no check marks to indicate I've seen that series/season. I'm hoping if you guys could add watched indicators to already watched series/seasons. Thank you. 

Toradora is completed on anilist
<img width="246" alt="Screen Shot 2023-09-12 at 8 42 36 AM" src="https://github.com/Goldenfreddy0703/Otaku/assets/43726430/b47e041a-31ef-48ec-bd62-a989fca76868">

No watched indicators on the season
<img width="2560" alt="Screen Shot 2023-09-12 at 8 56 16 AM" src="https://github.com/Goldenfreddy0703/Otaku/assets/43726430/7a3932c7-9219-4808-8745-d7fb507fa80d">

But there IS watched indicators within the season
<img width="2560" alt="Screen Shot 2023-09-12 at 9 03 03 AM" src="https://github.com/Goldenfreddy0703/Otaku/assets/43726430/72e21649-c5b5-4f93-b31f-e8bef38416da">

**Comment by Goldenfreddy0703** [comment]
Hey sorry I did not get back to you sooner, I'm not sure why either tbh but hopefully the watchlist recode should fix that soon hopefully.

**Comment by joezito129** [comment]
I can add watched indicators on the season if you have watched all episodes in your watchlist. It is very easy to implement.

**Comment by Goldenfreddy0703** [comment]
> I can add watched indicators on the season if you have watched all episodes in your watchlist. It is very easy to implement.

Oh that would be awesome, thank you very much!!!

**Comment by Liquidrag** [comment]
> I can add watched indicators on the season if you have watched all episodes in your watchlist. It is very easy to implement.

Awesome! Thanks!

**Comment by Goldenfreddy0703** [comment]
Hey so good news, in our watchlist recode, We have added watched indicators on the season if you have watched all episodes in your watchlist. Huge thanks to @joezito129 . Watchlist recode will probably be released around 20 - 22. 

When it gets release, we will close this issue but if you do run into problems, feel free to open this issue back up and we will look into it.

**Comment by Goldenfreddy0703** [comment]
Hey so good news, Major Watchlist Update should fix this issue and should be out, just make sure to rebuild database. If problems still occur please feel free to open this issue and we can look through it.
