### ISSUE TITLE
Genre Widget Menu Bug

### ISSUE THREAD

**Issue by Demonseed-jpg** [Goldenfreddy0703/Otaku#153]
Hello

I recently picked up Kodi again and ran into an issue adding the Genre section of the add on to a skin’s Home Screen as a shortcut (Arctic Horizon 2). It works the first time, but caches the result and subsequent clicks into the Genre button will bring up the previous results (when accessed from the shortcut).

I have solved this before in a different addon (I think Kaito? It has been a while) by appending an action to the shortcut that clears the cache of the addon. This was pretty tricky to figure out and I am more than willing to try again if needed, but

I was wondering if it would be possible to solve this at the addon level? Or if possible have a button that can clear the cache of just the genres and tags section if integrating this further isn’t possible. 

Thanks and I appreciate the amazing addon!

**Comment by Goldenfreddy0703** [comment]
Weird you should be able to just add the genres shortcut as a submenu or something and should pull up the genres. Let me take a look and see what's going on. 

Mind showing me how you reproduced the steps? I think I know what you did but I just wanna make sure.

**Comment by Goldenfreddy0703** [comment]
Hey so nevermind about reproducing the steps, apparently I see what's going on due to how our genre menu is made. It's not like tmdb helper or seren genres due to the fact that anime has so many genres. I will see if I can look into it and see what I could do. I'm sure one of our contributors already has a solution to this so we will get that worked on. 

For a small workaround for now, I think there is an addon called Autowidget where you can make shortcuts and menus for other addons and give them icons and artwork and stuff. Give that addon a try and see if that may help with genres just as a workaround for now.

**Comment by Demonseed-jpg** [comment]
Hi, thanks very much! I appreciate you taking the time to work on this. 

I’ll check AutoWidget out, thanks for the recommendation!

**Comment by Goldenfreddy0703** [comment]
Hey so good news, i have made some new genre menus in the watchlist recode branch, I just got to add icons and your issue should be resolved when the watchlist recode releases around 20-22

**Comment by Goldenfreddy0703** [comment]
Heyyy so icons are added and they look sickkkkkk!!!!!!!!
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/b9e22c7e-5858-4d48-b7f0-d6b7caf8d29e)
But yeah can't wait for watchlist recode to be released very soon.

**Comment by Demonseed-jpg** [comment]
Nice!! These look amazing! I haven’t had a chance to test this out but it looks like it’ll work great!

**Comment by Goldenfreddy0703** [comment]
Hey so good news, Major Watchlist Update should fix this issue and should be out, just make sure to rebuild database. If problems still occur please feel free to open this issue and we can look through it. 

Btw you may need to re add the genres widget menu again.

**Comment by Demonseed-jpg** [comment]
Awesome, that’s great to hear! I’m currently moving so it might be a moment before I check it out but I’ll let you know!
