### ISSUE TITLE
Otaku Episode Meta Error

### ISSUE THREAD

**Issue by jaimsitecom** [Goldenfreddy0703/Otaku#155]
Since i’ve just updated to 0.4.25, Otaku won’t open my shows anymore. Whenever i open any show it says Otaku Error - check log.  I cleared cache, rebuilt database, still gives error. The last 2 updates broke Otaku for me. 

Am using kodi 20.2 on android box. 

Here is my log:
https://mega.nz/file/NRQGkbTK#46oL5tXL5gv2-z-9fllU4ivaJYe-RqzBH6VKZ37TL5M

Hoping my favorite addon gets fixed soon. Ty in advance. 

Ps. Is there a way to obtain past versions so i can downgrade to the version that worked for me?

**Comment by Goldenfreddy0703** [comment]
Hey sorry, due to our season code for episode meta, we didn't catch this error, will be fixed very soon.

**Comment by Goldenfreddy0703** [comment]
Hey so actually it was due to an api key failing on us. We will restore episode meta very soon.

**Comment by theasguard** [comment]
In indexers/simkl line 76 
Season = result.get('season')
Log issue says it's something with the  .get in that line unless I'm the only one getting this error I do tend to tweak stuff and for some reason kodi is more finicky now a days.

**Comment by Goldenfreddy0703** [comment]
Thats what i thought too and then i tried previous versions and then realized our api key exceeded surprisingly and we were not aware. New version should be released but the new api key will not last for so long so use it when you need to.

**Comment by jaimsitecom** [comment]
Yay! Fixed now with update 0.4.26. Back to normal again. Thanks so much.

**Comment by Goldenfreddy0703** [comment]
Anytime but this bug will happen again in a few hours

**Comment by Goldenfreddy0703** [comment]
Im going to reopen this cause people may report this again.

**Comment by Goldenfreddy0703** [comment]
Ok i should be good to close now cause we have a permanent fix now.
