### ISSUE TITLE
[Feature] A setting to disable Unaird Episodes

### ISSUE THREAD

**Issue by jaimsitecom** [Goldenfreddy0703/Otaku#156]
Hi again. Is it just me who has unaired episodes showing up or is there a settings option in the new version to hide unaired episodes?

I noticed this also after the recent version updates. I guess since 2-3 vesions ago. It used to be only what has been aired that shows up in the list. 

TIA

**Comment by Goldenfreddy0703** [comment]
Hey there, when we were improving episode meta for Otaku, we used simkl for episode meta which is why you see unaired episodes as well.

**Comment by jaimsitecom** [comment]
Oh ok. So this is a permanent issue now?

**Comment by jaimsitecom** [comment]
I guess nothin we can do about. As long as otaku can play available episodes, i’m ok. Thanks for the explanation.

**Comment by Goldenfreddy0703** [comment]
> I guess nothin we can do about. As long as otaku can play available episodes, i’m ok. Thanks for the explanation. 

Well we could probably do something about it cause our episode meta has airdates and all and we can try to make it where if it reaches that specific airdate then the episode will show. 

We could probably make a setting for it and all, it will take time tho.

**Comment by jaimsitecom** [comment]
Cool! Thanks again for all you guys are doing to maintain this great addon.

**Comment by Goldenfreddy0703** [comment]
Hey so good news, next release will have an option called "Hide Unaired Episodes" in the General Category of the addon settings. When it releases, enabled the setting and rebuild database and see if that fixes it and then we can close this issue.

**Comment by Goldenfreddy0703** [comment]
Hey release should be out in a min so im going to go ahead and close this issue but if problems do occur, pls feel free to open this issue and tell me if it worked for you. 

Thank you

**Comment by jaimsitecom** [comment]
Woohoo! Great news indeed. Thanks so much.

**Comment by jaimsitecom** [comment]
> Hey release should be out in a min so im going to go ahead and close this issue but if problems do occur, pls feel free to open this issue and tell me if it worked for you.
> 
> Thank you

reporting a bug. After using the on/off feature showing unaired episodes, some shows show up as blank. As in no episodes showing up even if the episode was aired. For my case, jujutsu kaisen, rurouni kenshin, undead murder farce showed up blank when the ‘hide unaired episodes’ button is enabled. When i turn it on and rebuild the database, it goes back to normal and shows up all episodes (including unaired eps of course).

**Comment by jaimsitecom** [comment]
May i know if you guys in a middle of updating/fixing metas for anime shows?  Some shows will show up their episodes but most would not when the ‘Hide unaired eps’ is turned on. 

So i confirm that turning on the ‘HIDE UNAIRED EPISODES’ will also hide other episodes both aired and unaired, most shows will show up blank actually. I tried turning off my Watchlist in settings, no effect. Shows don’t show the aired and unaired episodes. When i turn off ‘hide unaired eps’, the shows will populated the episodes - including unaired episodes. 

So i guess i have to TURN OFF the hide feature and accept that unaired episodes will stay for now. 😁

anyways, thank you again!

**Comment by Goldenfreddy0703** [comment]
Ahhh I might have forgotten to implant a feature where it if the next episode releases or if it reaches that specific airdate, it should populate. Hopefully I can work on that soon. 

Now about your first question, we have not worked on that unfortunately. We been busy thought the week and yeah, hopefully we can get to that soon.

**Comment by jaimsitecom** [comment]
> Ahhh I might have forgotten to implant a feature where it if the next episode releases or if it reaches that specific airdate, it should populate. Hopefully I can work on that soon.
> 
> Now about your first question, we have not worked on that unfortunately. We been busy thought the week and yeah, hopefully we can get to that soon.

No rush. Take your time. Otaku works fine now that i turned off ‘hide unaired eps’. As long as i get to watch my shows now, i’m good!

thanks so much!

**Comment by jaimsitecom** [comment]
Well, i tried to check if this feature is working again. Unfortunately not. 😀 when the switch is on, all my favorite shows became blank. No episodes show up anymore. Whether aired or unaired, they don’t show up anymore. 

I will have to live and accept unaired episodes showing up for now. You can remove the switch for now i guess. Ty anyways for trying. 

Thanks!

**Comment by Goldenfreddy0703** [comment]
Ahhh sorry I forgot to work on this, hopefully will try to look into it today.

**Comment by jaimsitecom** [comment]
> Ahhh sorry I forgot to work on this, hopefully will try to look into it today.

Thanks a lot! If it’s too much of a hassle, it’s ok to remove it permanently. Not really a problem anyway. 😀

**Comment by Goldenfreddy0703** [comment]
Hey @jaimsitecom, good news, we fixed it and also added a new setting as well. Im going to close this issue but release should be out so feel free to test it and if you encounter any more problem related to this, we will open this issue again and all. 

Thank you

**Comment by jaimsitecom** [comment]
Works great now! All my shows showing up all aired episodes and hides future unaired episodes.   So far so good. Thank you!

**Comment by DaisyF8** [comment]
Sorry to nag. I have hide unaired enabled but for example unaired episode for Berserk of Gluttony is showing in Next Up in MyAnilelist.

**Comment by Goldenfreddy0703** [comment]
Ahh well we only made that option just for episode meta but not next up sense next up is very buggy. Me and my team will try to look into it.

Thank you

**Comment by Gujal00** [comment]
> Sorry to nag. I have hide unaired enabled but for example unaired episode for Berserk of Gluttony or Shangri-La Frontier is showing in Next Up in MyAnilelist.
Next-UP comes straing from myanimelist api call `watching?next_up=true`, if myanimelist is showing unaired episodes, it is the api issue, nothing can be done inside Otaku

**Comment by Goldenfreddy0703** [comment]
Oh....i didn't actually think it was an api issue with Mal sense Next up is basically when you play a show, it will automatically play the episode from the episode meta and create a playlist and all.

**Comment by Gujal00** [comment]
Watchlist Next UP is not the same as playlist Next up popup towards the end.
Watchlist Next up shows what are the next watchable episodes from all the shows you are currently watching

**Comment by DaisyF8** [comment]
Thx for explaining. And also : WOW with all the recent progress. I really like Otaku as TMDBhelper player.
