### ISSUE TITLE
Otaku error after upfate

### ISSUE THREAD

**Issue by Bazuf** [Goldenfreddy0703/Otaku#157]
After the add-on update I started getting an error right after clicking on an anime..
The episode list does not appear and it says "Otaku error, see log for more info"

I've cleared the cache, rebuild database, wiped add-on data, uninstalled it and everything and I'm still getting the error.

What should I do?
Here's the log file: https://pastebin.ubuntu.com/p/Vs3FvvdyPj/

**Comment by theasguard** [comment]
Yea I get the same this is where the error comes from 
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 76, in _process_episode_view
                                                       season = result.get('season')
                                                                ^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
Same error I'm getting and you can't revert to an older version like some addons so it's a little irritating.

**Comment by Bazuf** [comment]
I just updated the add-on and it seems to be working perfectly now.
Thanks for getting this solved so quickly!!

**Comment by Goldenfreddy0703** [comment]
Hey anytime, there was some big updates that recently happened with episode meta but we have a permanent fix so everything should be good now.
