### ISSUE TITLE
Meta data for next up

### ISSUE THREAD

**Issue by TheWizard67** [Goldenfreddy0703/Otaku#158]
After the latest update, if you use Next Up it will show the correct meta data. 
However, it only works of you have opened each individual show under, for example "Currently Watching" if you havnet opened the shows first, it will only show the poster of the anime and the general meta data for the show. Instead of the episode.

Repeatability just rebuild database and open next up.

**Comment by Goldenfreddy0703** [comment]
Ok artwork is still bugged and it may need a recode on it soon. It was due to the simkl recode and all and it's quite a mess, hopefully we will fix that soon.

**Comment by Goldenfreddy0703** [comment]
Hey @TheWizard67 so recently, we just fixed an artwork bug with episode thumbnails so it doesn't show posters. Is this issue fixed for you by anychance?

**Comment by Goldenfreddy0703** [comment]
Hey so im going to consider this fixed and im going to close this issue but if you still have any problems or issues related to this, feel free to tell me and i will open this issue back up and we can look into it. 

Thank you

**Comment by TheWizard67** [comment]
> Hey so im going to consider this fixed and im going to close this issue but if you still have any problems or issues related to this, feel free to tell me and i will open this issue back up and we can look into it.
> 
> Thank you

Sorry sir, i wasnt quick enough to respond. I just checked and its still the poster that loads on Next Up. Episode art starts turning up once shows have been opened in Currently Watching. If it makes a difference the tracking service i use is MAL.

**Comment by Goldenfreddy0703** [comment]
Oh no your fine, I thought it was fixed, will look more into it.
