### ISSUE TITLE
Auto Play the last selected release with Source Select or filter option for Auto Play

### ISSUE THREAD

**Issue by jonathanluepfert** [Goldenfreddy0703/Otaku#159]
When I use Source Select to play my preferred release of an episode I want the next episode that Auto Plays to play from that same batch torrent that I chose for the previous episode. Currently it will always choose the first one in the list that shows when I go to source select presumably based on file size. An option to filter what Auto Plays would also be great so it would Auto Play only episodes by certain release groups or 10bit releases for example. That could be implemented with a simple option to filter by searching for certain keywords in the title.

**Comment by Goldenfreddy0703** [comment]
Hey @jonathanluepfert great news, we have made a release that should Auto Play the last selected batch torrent so that way you can watch a whole series with the same batch torrent. 

Huge thanks to @joezito129 for making this possible.
