### ISSUE TITLE
9Anime now AniWave

### ISSUE THREAD

**Issue by bigwolvie** [Goldenfreddy0703/Otaku#161]
Can the 9Anime source be updated to reflect their rebranding to Aniwave and their move to aniwave.to based url paths?

**Comment by Goldenfreddy0703** [comment]
Sure, maybe tomorrow, I will update the rebranding.

**Comment by Goldenfreddy0703** [comment]
Ok 9anime should be changed to Aniwave, If you have any issues or wanna open this back up, please feel free message in here and we will look further into this. 

Thank you
