### ISSUE TITLE
Request to change the otaku animess source to the anime vision source.

### ISSUE THREAD

**Issue by icarok99** [Goldenfreddy0703/Otaku#162]
I am making this request because the source otaku animess There are several animes with low resolution for those who watch on a device with a larger screen, it's bad.

https://animes.vision/

**Comment by Goldenfreddy0703** [comment]
Put this in the Source Suggestions in #144 and we will think about adding it soon it soon.

**Comment by icarok99** [comment]
@Gujal00 The person responsible for the website otaku animess made some changes and there is no way to get the video URL anymore, now the video is redirected to another URL.

**Comment by icarok99** [comment]
> @Gujal00 The person responsible for the website otaku animess made some changes and there is no way to get the video URL anymore, now the video is redirected to another URL.

Fixed

**Comment by icarok99** [comment]
Secondary source the first one is asking for login 

`https://tanoshi.digital/`

**Comment by icarok99** [comment]
@Goldenfreddy0703 Any news about the source french  `https://ani-zone.net`?

**Comment by Goldenfreddy0703** [comment]
Not sure, that's up to @Gujal00 if it's compatible to add and all.

**Comment by icarok99** [comment]
> I'm making this request because the otaku animess source has several animes with low resolution for those who watch it on a device with a larger screen, it's bad.
> 
> `https://animes.vision/`

The font a animes vision It is compatible  gujal00?

**Comment by icarok99** [comment]
@Goldenfreddy0703 Do you have plans to add language option from addon?

**Comment by icarok99** [comment]
If so, I can help with the language pt-br.

**Comment by Goldenfreddy0703** [comment]
When you say language option, do you mean like changing the addon language or subtitle language?

**Comment by icarok99** [comment]
### 

> When you say language option, do you mean like changing the addon language or subtitle language?

Add-on language

**Comment by Goldenfreddy0703** [comment]
Oh, well not really unless someone gives us a converted strings file

**Comment by icarok99** [comment]
> Oh, well not really unless someone gives us a converted strings file

I think I've already completed about 80% when I'm done I'll send it.

**Comment by Goldenfreddy0703** [comment]
Oh, wait have you been converting them manually cause i think there is this strings converter you can do.

**Comment by icarok99** [comment]
> Oh, wait have you been converting them manually cause i think there is this strings converter you can do. Forgot what it was called tho.

I use a file manager that recognizes the file type and allows me to edit without having to convert.

**Comment by icarok99** [comment]
@Goldenfreddy0703 create a branch with name resource.language.pt_br, I create one strings.po tomorrow.

**Comment by Goldenfreddy0703** [comment]
Oh, wait have you been converting them manually cause i think there is this strings converter you can do. Hey so can't create a branch at the moment but will have one created tomorrow once I get on my computer

**Comment by icarok99** [comment]
I edited without needing to convert.

**Comment by icarok99** [comment]
> @Goldenfreddy0703 Any news about the source french `https://ani-zone.net`?

@Gujal00 Is this French font compatible?

**Comment by Goldenfreddy0703** [comment]
> That tool is for converting a language file in xml format to the .po format as required by Kodi16+ Its got nothing to do with translations and those are always done manually. @icarok99 as long as you took the en_gb strings.po and populated the `msgstr` in pt_br for each of the `msgid` it is correct

Ahh makes sense thank you but @icarok99 sorry i took forever but i went ahead and made a branch for you.

**Comment by icarok99** [comment]
@Goldenfreddy0703 
![Screenshot_2023-12-09-19-58-17-738_org xbmc kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/2b79dd3a-3272-4c2d-87e2-c63293c76657)
![Screenshot_2023-12-09-19-58-24-757_org xbmc kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/d23b5f77-dca0-4af6-9ad6-af62e590fd63)

**Comment by Goldenfreddy0703** [comment]
Wait that wasn't merged into main was it and I don't remember updating the change log but language is working tho which is good

**Comment by icarok99** [comment]
> Wait that wasn't merged into main was it and I don't remember updating the change log but language is working tho which is good.
> 
> Edit: My bad, it wasn't but It will be merged soon, just been lazy these past few days.

This is just a test to see if everything was going well.

**Comment by icarok99** [comment]
@Goldenfreddy0703 Change the changelog, you wrote the name of the skin with z

**Comment by Goldenfreddy0703** [comment]
Oh dang it, I thought it was a z, will change it on next release, thanks

**Comment by icarok99** [comment]
> Oh dang it, I thought it was a z, will change it on next release, thanks

Merge the pt-br translation into the main branch, you will not need to create an option to change language in the add-on.

**Comment by icarok99** [comment]
Translation will work like the skin will automatically recognize the Kodi language.

**Comment by icarok99** [comment]
@Goldenfreddy0703 What source does the addon use to get anime fanart?

**Comment by Goldenfreddy0703** [comment]
I doubt it but ask @Gujal00 about that. For me in the past, I could find anime just fine in most cases through nyaa or animetosho
