### ISSUE TITLE
Addon for stremio

### ISSUE THREAD

**Issue by zaraki75** [Goldenfreddy0703/Otaku#163]
Please make an addon for stremio

**Comment by Goldenfreddy0703** [comment]
Sorry to say this but no way.

Reason why is cause stremio is very limited when it comes to functionality and addon configuration and its Javascript. You don't have to ability to decide for sub or dub, your unable to tell if the anime has dub, you can't customize your sources, idk how watchlist work with stremio. You can only configure the addon into a web page which is kinda dumb. Trakt scrobbler would not scrobble well with anime. Everything is limited when it comes to Sources, Mappings, Configuration, Sub or Dub, Subtitles, ect.

But yeah again, there is no way we are making a stremio addon, I will contribute in someone's stremio anime addon if they need help but I will not make one. Too much work.
