### ISSUE TITLE
Bug Error while playback  (doesnt affect anything that i notice) 

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#164]
Line 281 I believe results = json.loads(r)['my_list_status'] is where the error came from was watching parallel pharmacy episode 1 about 4 mins from the end, I tried another show but didn't notice the error so maybe it's a issue with some stuff on mal, I'll reinstall and start fresh just to make sure.

**Comment by Goldenfreddy0703** [comment]
Weird, I will look into that just incase as well

**Comment by Goldenfreddy0703** [comment]
Hey so looked into it and did not get the error on my end. Its probably either due to updates or you might have to reauthenticate mal maybe but im not too sure. Out of curiosity what version of Kodi are you using and did a reinstall or fresh start fix the issue?

**Comment by theasguard** [comment]
> Hey so looked into it and did not get the error on my end. Its probably either due to updates or you might have to reauthenticate mal maybe but im not too sure. Out of curiosity what version of Kodi are you using and did a reinstall or fresh start fix the issue?

Hey so I noticed earlier mal went into a maintenance, I believe that's what caused the error, but I did reset everything and start fresh and it's working a treat as usual. Thank you and sorry for late response and being g a pain haha.

**Comment by Goldenfreddy0703** [comment]
Hey anytime and no worries, your not being a pain at all. If you ever have any questions or concerns, pls feel free to message us. 

Thank you
