### ISSUE TITLE
RD cloud scraping replaying current file when new file from RD cloud is selected.

### ISSUE THREAD

**Issue by Xyl-AU** [Goldenfreddy0703/Otaku#165]
1. Enable RD cloud scraping in Otaku.
2. Import a torrent into your RD cloud. In this instance, I am using [Vodes] Hunter x Hunter (2011) (v2) [BD 1080p 10bit x264 FLAC Dual-Audio], as it is not found by the torrent scraper.
3. Source select episode 1, select the RD cloud source of that torrent.
4. Go back out of the video player to the episode selection screen (without stopping the episode, pausing is fine, but the media should still be loaded in the background).
5. Source select episode 2, select the RD cloud source of that torrent.
6. Instead of the expected behaviour of playing episode 2's file, it instead restarts episode 1.

**Comment by Goldenfreddy0703** [comment]
Question, does this happen only using source select in the context menu?

**Comment by Goldenfreddy0703** [comment]
Ok good to know it's just a context menu bug with select source. Hopefully we can get either @Gujal00 or @joezito129 to fix this soon. Thank you

**Comment by Goldenfreddy0703** [comment]
Heyyy @Xyl-AU , we hope this fixed your issue but if you don't mind, we would like you to test to confirm before closing so whenever you have time, pls feel free to test our release whenever. 

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey @Xyl-AU , we are going to assume that this issue is fixed so we will go ahead and close this issue but if you still encounter these problems, feel free to reply here and we can open this back up and look into it more. 

Thank you
