### ISSUE TITLE
Plan to watch sort issue with simkl

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#166]
On my watchlist in Otaku when I add a series to my plan to watch for Simkl, the item added gets put right at the very bottom of the list so I have to scroll all the way to it, short story it doesn't sort it as last updated properly, it does but in reverse I guess, on plan to watch is the only one I noticed it on.

**Comment by Goldenfreddy0703** [comment]
Oh we didn't really take this into count, Simkl watchlist is kinda weird where you have to watch an episode in order to be on the top, it's weird and I'm not sure if there is a way to fix that.

**Comment by theasguard** [comment]
> Oh we didn't really take this into count, Simkl watchlist is kinda weird where you have to watch an episode in order to be on the top, it's weird and I'm not sure if there is a way to fix that.

Hey no worries if that's how it is with them then thats how it is a guy will have to just deal haha, thanks for replying so quickly man. And yea I noticed their site is ehh behind lots of pay walls haha

**Comment by Goldenfreddy0703** [comment]
Well actually, plan to watch is an impotent menu item that I use daily and it would not make sense to have an anime at the bottom. I will look Into it soon or this weekend and see if there is anything I can do, if not then I will figure out something.

**Comment by theasguard** [comment]
> Well actually, plan to watch is an impotent menu item that I use daily and it would not make sense to have an anime at the bottom. I will look Into it soon or this weekend and see if there is anything I can do, if not then I will figure out something.

Yea that's the same for me 😅 I was using mal before but they go in and out of maintenance a lot lately so I switched it up for now

**Comment by Goldenfreddy0703** [comment]
> Yea that's the same for me 😅 I was using mal before but they go in and out of maintenance a lot lately so I switched it up for now
> Thank you for looking into this by the way, you're awesome

Hey anytime, btw if it helps, Anilist is basically the most stable watchlist to use, it never goes down, been super great, have not had any issues with, its Otaku's Main Detabase. If you ever wanna try anilist, give it a try someday, it's great.

**Comment by theasguard** [comment]
> > Yea that's the same for me 😅 I was using mal before but they go in and out of maintenance a lot lately so I switched it up for now
> > Thank you for looking into this by the way, you're awesome
> 
> Hey anytime, btw if it helps, Anilist is basically the most stable watchlist to use, it never goes down, been super great, have not had any issues with, its Otaku's Main Detabase. If you ever wanna try anilist, give it a try someday, it's great.

I may do that, thanks.. I hope you have a good weekend.

**Comment by Goldenfreddy0703** [comment]
Hey @theasguard , sorry this took forever but i finally figured out how to fix simkl watchlist and it took me forever but got in reach with simkl devs and they are awesome. 

Ok so your going to go to Otaku settings and change the Simkl sort order to "Last Added" and that should fix your issue. 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/c326055a-1c7f-4523-ae4f-37e0aa8a0c66)

Ok im going to go ahead and close this but if you have any questions, please feel free to ask in here and if you run into issues, we will open this back up again. Glad to have figured this out. 

Thank you
