### ISSUE TITLE
This screen keeps appearing 

### ISSUE THREAD

**Issue by rahaaatul** [Goldenfreddy0703/Otaku#167]
![image](https://github.com/Goldenfreddy0703/Otaku/assets/86149861/c0df1e39-952f-4828-99b1-6666c39d551f)

I'm using Arctic Fuse skin. I don't even do anything and it just appears. How do I disable this screen from appearing out of nowhere?

**Comment by Goldenfreddy0703** [comment]
Ok that's weird.

1. What device are using?
2. What version of Kodi?
3. Did you Rebuild Database, Clear Cache, Clear Torrent Cache?
4. Is it possible that you accidently set a widget or submenu of the anime calender menu by anychance? (That most likely could be the culpret sense you using Arctic Fuze Skin)

**Comment by rahaaatul** [comment]
> What device are using?

**Windows 11**

> What version of Kodi?

**Kodi 20.2**

> Did you Rebuild Database, Clear Cache, Clear Torrent Cache?

**I clear cache after every startup automatically with open wizard plugin. Is this the cause?**

> Is it possible that you accidently set a widget or submenu of the anime calender menu by anychance? (That most likely could be the culpret sense you using Arctic Fuze Skin)

**No, but I set submenu to dynamic with all options in Otaku. I had the same thought, so I deleted the submenu and tested it again but the screen appeared again.**

**Comment by Goldenfreddy0703** [comment]
> No, but I set submenu to dynamic with all options in Otaku. I had the same thought, so I deleted the submenu and tested it again but the screen appeared again.

Ok try switching to the default skin and see if the screen appears.

**Comment by rahaaatul** [comment]
> Ok try switching to the default skin and see if the screen appears.

I roamed around in Kodi using default skin for 5 minutes but screen did not appear.

**Comment by rahaaatul** [comment]
I think it's the dynamic list that's causing this issue...

**Comment by rahaaatul** [comment]
I moved to static, now the screen doesn't appear anymore.

I have a request for you, outside of Otaku. May I? @Goldenfreddy0703

**Comment by Goldenfreddy0703** [comment]
Hey sorry I was afk but interesting so it did have something to do with the skin. 

What's the request you would like to ask about?

**Comment by rahaaatul** [comment]
> So, it did have something to do with the skin.

Yes. I think it's calling content from every submenu because I set it as dynamic submenu list. So, when it calls the calendar menu, it triggers the screen. I think that is the logical explanation for this issue.

> What's the request you would like to ask about?

I don't know if you would accept it or not, but I want to give it a shot. 
I'd like you to help in the [Dramacool](https://github.com/groggyegg/plugin.video.dramacool) repo. It's like otaku but for Asian dramas. But **it lacks TMDB Helper integration and TMDB Helper player**. It's a single source, but I think if you pick this and add more sources, add TMDB integration and player just like you did with Otaku it'd help vast Asian drama watchers like me. 
I hope you'll consider this if you have some free time. Thank you.

**Comment by Goldenfreddy0703** [comment]
Ok so about TMDB Helper integration, we don't even have that in Otaku yet. I want either Gujal00 or joezito129 to add it and I have a way to add it but neither of them do not know how tmdb helper works unfortunately and yeah, that's why we don't have tmdb helper integration yet.

**Comment by rahaaatul** [comment]
> Ok so about TMDB Helper integration, we don't even have that in Otaku yet.

Oh no! That means I was wrong the whole time, because I saw otaku scraping hd background, description and other stuff. That led me to believe, that it has tmdb integration. 

Sorry for my misinformed presumption.

**Comment by Goldenfreddy0703** [comment]
Oh no your fine, we do have it on our road map, I just need either Gujal00 or joezito129 to add it very soon.

**Comment by rahaaatul** [comment]
> Oh no your fine, we do have it on our road map, I just need either Gujal00 or joezito129 to add it very soon.

That's awesome!

Do you think you could pull request in that repo to at least create a player for it? I maintain [Trending Drama This Week](https://trakt.tv/lists/25470741) and [Top Drama All Time](https://trakt.tv/lists/25507271) list in trakt. And I think with your help we could make this work in Kodi, if adding tmdb integration is too much for your team. @mrgsi hosts wide variety of players, he can host that, he told me.
