### ISSUE TITLE
Can't add Accounts / username doesn't show up

### ISSUE THREAD

**Issue by ChakraFusion** [Goldenfreddy0703/Otaku#168]
I am new to Otaku and yesterday I tried to add my real debrid account as well as MAL.
The whole process is successful, but the username never shows up in the settings of Otaku. It seems like Otaku simply doesn't save the tokens / login information.
I have this issue with all accounts. MAL, Anilist and Real Debrid.
This morning somehow my real debrid username showed up in the settings after I tried to add my MAL Account. But the issue still persists for MAL and Anilist. 
Maybe this is a general problem with the closing settings and the pop-up nature of the "insert your MAL link here" message.

My process:
1. Click authenticate in the Otaku settings for any account 
2. Otaku settings automatically close after clicking the button
3. (Sometimes a change log message pops up after the settings close)
4. Popup with the verification link pops up
5. I open the link, login to the Account in my phone browser
7. Successful 
8. I copy the Link / Token
9. I close the link message on my TV with clicking next to the message window
10. The "insert http link / insert token" message appears on TV screen
11. I insert the link / token via the Kore remote app
12. Link / token message automatically closes on TV
13. TV says "Success"
14. I click ok on the Success message
15. I am still looking at the Otaku Add-on menu because the Otaku settings closed themselves earlier (step 2)
16. I open the Otaku configuration from the menu
17. I see that the account username is still missing
. End of process

What am I doing wrong?

I am using Kodi on my LG G2 TV, if this is important.

**Comment by Gujal00** [comment]
Easiest way is to do the setup on a windows machine with MAL and RD authorised, check everything is working and then copy the `C:\Users\htpc\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.otaku\settings.xml` file across to the other device/TV, similar location

**Comment by Goldenfreddy0703** [comment]
Hey sorry i never responded and thank you @Gujal00 for a solution but if it helps sometimes when you authenticate something on Otaku, you, may wanna restart kodi so that Otaku shows your username. Some skins have this bug where usernames don't display correctly in settings but it will be authenticated, you could also try clear cache, rebuild database, restart kodi and see if that works.

**Comment by ChakraFusion** [comment]
Thank you both for your replies. I tried to setup otaku on my pc and there I have exactly the same problems. All accounts I add aren't saved into the settings.xml. I also tried clearing the cache, rebuilding the database, restarting kodi and everything together, but it didn't change anything.
I looked into the settings.xml file and the entries for MAL, Anilist and RD were empty. Only on the settings.xml on my TV I could see my username for real debrid saved in there. (which is the only thing that actually works. But I can't reproduce the successful login now)
I tried to manually add the missing information to the settings.xml. The information also showed up in the otaku menu, but this just resulted in me getting network errors when trying to access the MAL / Anilist data inside otaku.

So all around I have identical problems on my tv and on my PC. Can I manually add the token data into the settings.xml as a workaround?

**Comment by ChakraFusion** [comment]
sorry, I did not want to close just now. I pressed enter too quickly

**Comment by Goldenfreddy0703** [comment]
No problem, sense you are getting errors on both PC and TV, best suggestion is to disable ipv6 and restarting your router, most people have issues with Otaku which mostly resulted into restarting there router or reinstalling the addon. Hopefully this should fix your issue.

**Comment by ChakraFusion** [comment]
So I tried that. I couldn't disable ipv6 in my router, because it simply reenabled itself after the reboot. Maybe because I am on a cable connection. Instead I disabled ipv6 in my windows network adapter settings on my pc. I confirmed that only ipv4 is used on the website myip.is. 
Then I redid the whole authentification with MAL and Anilist in otaku. Still the same problem. The Account data changes simply aren't written into the settings.xml.

It is weird that only I seem to have these problems.

**Comment by Goldenfreddy0703** [comment]
It is, it has to be something due to your network, you have rebooted your router by unplugging it and plugging it back in right? Try one last time atleast and see if anything changes.

**Comment by ChakraFusion** [comment]
I have a Fritzbox 6660 Cable as router. I can uncheck the ipv6 connection in the webinterface. After I do that nothing in my network is working anymore. Then I reboot the router via the web interface and after the reboot ipv6 reenables itself.
But as I said earlier, I could successfully disable ipv6 on my pc, just for testing. And even there the ipv4 didn't solve my Account problems with otaku. It's exactly the same as with ipv6 enabled.

I don't have any problems with other kodi addons. Seren and Fen are working perfectly fine and there were no issues at all with authenticating Trakt.tv or Debrid for example.

**Comment by ChakraFusion** [comment]
Can't I manually add my Anilist token into the settings.xml?

It has to go somewhere here right?:
<setting id="anilist.enabled" default="true">false</setting>
    <setting id="anilist.username" default="true" />
    <setting id="anilist.token" default="true" />
    <setting id="anilist.login" default="true" />

**Comment by Goldenfreddy0703** [comment]
I mean i guess you could try that but i have one more idea so we know its actually network and not the device itself. Make sure your phone is on mobile data, turn on your hotspot and make sure your not connected to your home wifi, after that try testing Otaku one last time and see if it somehow works with that mobile hotstpot from your phone.

**Comment by ChakraFusion** [comment]
I did the test with the mobile phone hotspot. I even cleared the cache, rebuild database, restarted Kodi. Still no changes. I really don't think this is a network issue.

**Comment by ChakraFusion** [comment]
If I manually edit the settings.xml. Which entries do I need to fill out? Only anilist.username and anilist.token? What is 'anilist.login' for? And which entries do I need to edit for MAL?

**Comment by Gujal00** [comment]
for anilist, replace user with your user name and the long token with your token
```xml
    <setting id="anilist.enabled">true</setting>
    <setting id="anilist.username">user</setting>
    <setting id="anilist.token">eyJ0eXAiOiJKV1QiLCJhbGciOiJ</setting>
```
Mal is more involved, you cant manually add as there are multiple things it pulls refresh token, authvar, access token etc.

**Comment by Goldenfreddy0703** [comment]
Hey @ChakraFusion, @joezito129 said it could have something to do with Language Invoker. If Language Invoker is enabled, try disabling it and try again and see if the issue still persist. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/c94e7e52-c4b2-42e0-9d08-674720cd45f7)

**Comment by ChakraFusion** [comment]
THank YOu!!
THis was exactly it. The language invoker was disabled for me and after enabling it everythink worked out. I don't know what this setting normally is for, but enabling it magically solved all the account data saving problems. I still had to log into MAL before Anilist for some reason, but it all worked out. I instantly saw that new data was written into the settings.xml. All the accounts are registered correctly now and everything is working as intended.

Thank you for your time and for your help. I appreciate it very much

**Comment by Goldenfreddy0703** [comment]
> THank YOu!!
> THis was exactly it. The language invoker was disabled for me and after enabling it everythink worked out. I don't know what this setting normally is for, but enabling it magically solved all the account data saving problems. I still had to log into MAL before Anilist for some reason, but it all worked out. I instantly saw that new data was written into the settings.xml. All the accounts are registered correctly now and everything is working as intended.
> 
> Thank you for your time and for your help. I appreciate it very much

..........how????

Like I'm glad you found a solution and it had something to do with languageinvoker even though it was disabled for a number of reasons but like how???? 😂

@joezito129 you should look into that more, I'm more surprised that it actually somehow solved his issue.

**Comment by Goldenfreddy0703** [comment]
Now just know that when languageinvoker is enabled, you may get stuck when backing out of certain menus like settings for example which is why it's expiremental.
