### ISSUE TITLE
Watchlist Not Working

### ISSUE THREAD

**Issue by Shadowstrife** [Goldenfreddy0703/Otaku#170]
Recently started having an issue where whenever I try to open the watchlist it just throws this error
![image](https://github.com/Goldenfreddy0703/Otaku/assets/149613180/b32903dd-5502-4b96-918f-bf8409a2b63b)

**Comment by Goldenfreddy0703** [comment]
Did you try reauthenticating the watchlist?

**Comment by Sickhead01** [comment]
Same here

**Comment by Shadowstrife** [comment]
> Did you try reauthenticating the watchlist?

This worked thanks.

**Comment by Goldenfreddy0703** [comment]
ahh anytime, surprised to hear that actually worked lol.
