### ISSUE TITLE
Episodes buffer/reload after about 20 minutes in

### ISSUE THREAD

**Issue by MohnJadden** [Goldenfreddy0703/Otaku#173]
I'm running Otaku on a new Kodi build.  I'm not using any debrid service; the only change I've made is to enable the Verizon alt for Nyaa.  About 20 minutes into an episode of any given anime, the playback pauses and seems to reload.  I get the spinning progress bar, it loads from 0 to 100, I get another 5-10 seconds of playback, and it repeats for the rest of the episode. 

If I go to the next episode, it plays normally until around the 20ish minute mark, then the issue repeats.  

Is there a setting somewhere I need to change?

**Comment by Goldenfreddy0703** [comment]
Hey there, you must be the same guy on reddit, sorry i did not respond earlier but did resetting your router help you out or resolve your issue your having?

**Comment by Gujal00** [comment]
Once playback starts, Otaku is out of the picture, it is all Kodi and its ffmpeg based videoplayer. Nothing to set in Otaku.
You can try increasing the network buffer in sdvancedsettings.xml
The Value `629145600` is for systems with 4GB RAM. you should halve it if your device has only 2GB RAM
```xml
<advancedsettings version="1.0">
    <cache>
        <buffermode>1</buffermode>
        <memorysize>629145600</memorysize>
        <readfactor>8</readfactor>
    </cache>
    <network>
        <disablehttp2>true</disablehttp2> 
    </network>
</advancedsettings>
```

**Comment by icarok99** [comment]
For 2GB RAM

<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>157286400</memorysize>
        <readfactor>10</readfactor>
    </cache>
</advancedsettings>

For 4GB RAM

<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>314572800</memorysize>
        <readfactor>15</readfactor>
    </cache>
</advancedsettings>

**Comment by icarok99** [comment]
For 2GB RAM

`<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>157286400</memorysize>
        <readfactor>10</readfactor>
    </cache>
</advancedsettings>`

For 4GB RAM

`<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>314572800</memorysize>
        <readfactor>15</readfactor>
    </cache>
</advancedsettings>`

**Comment by icarok99** [comment]
```
For 2GB RAM

<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>157286400</memorysize>
        <readfactor>10</readfactor>
    </cache>
</advancedsettings>

For 4GB RAM

<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>314572800</memorysize>
        <readfactor>15</readfactor>
    </cache>
</advancedsettings>

**Comment by Goldenfreddy0703** [comment]
Hey so sense there has not been a response for the last 3 weeks, im going to go ahead and close this issue but @MohnJadden , if you still have any issues with Episodes buffering, refer to the methods above and if they don't work, i can try to look into your connection on this further. 

Thank you
