### ISSUE TITLE
Anilist Failing to Open

### ISSUE THREAD

**Issue by ek19q** [Goldenfreddy0703/Otaku#174]
Anilist won't open when I click on any status directory (plan to watch, current, etc.)

I have tried re-authorizing anilist, clearing Otaku and Kodi caches, rebuilding metadata, etc. 

Switched to MyAnimeList and it is working fine, however I wanted to bring this issue to the devs attention because I prefer using Anilist as my watchlist and I hope this can get fixed. 

Using Kodi 19.3 on Firestick

Kodi Logfile: https://paste.kodi.tv/rijajepira

Let me know if any more info is needed.

**Comment by Goldenfreddy0703** [comment]
Kodi 19.3 is kinda old and i think it could be a kodi bug sense your using an older version of Otaku. @Gujal00 do you have any idea why his error is failing to convert a string?

**Comment by Gujal00** [comment]
From the log
`INFO <general>: CAddonMgr::FindAddons: plugin.video.otaku v0.4.28 installed`

Isnt that like 3 months old?

**Comment by ek19q** [comment]
Interesting. I didn't realize that my version of Otaku was out of date. I have it set to auto update and that usually works fine. 

I also have it set to show the changelog whenever I open Otaku so I didn't realize that anything had changed. 

I just manually went in to view the changelog to verify things and it updated. 

Not sure what caused this behavior, maybe like @Goldenfreddy0703 said it is my older version of Kodi? Or maybe this was just a transient issue. 

Feel free to mark this issue closed since things are working now.

**Comment by Goldenfreddy0703** [comment]
Wait seriously, things are working for you now. Maybe it did have something to do with armkai then. Interesting.
