### ISSUE TITLE
Watchlist tracker Updates 

### ISSUE THREAD

**Issue by Amateur-God** [Goldenfreddy0703/Otaku#175]
Would it be possible to add an option to push watch status updates to all authenticated watchlists not just one? 

For example I use both SIMKL and Anilist, and I have both authenticated in otaku, however when I watch stuff via otaku I can only have it push that ive watched to one of them, not both. 

Ideally I would like for it to push my watch status to all authenticated trackers

**Comment by Goldenfreddy0703** [comment]
Hey so we did consider this in the past and I would have loved to have all watchlist update as well but we had trouble getting all the watchlist to update in the past sadly. Also if we were to have all watchlist to update, Watchlist Manager context menu would have alot of trouble. 

One workaround you may wanna try is download the mal-sync extension on your browser and sign in to both Anilist and Simkl and turn on there sync feature which should sync and update both watchlist for you automatically. Hope this helps but very sorry we cannot add this feature.
