### ISSUE TITLE
Watchlist not updating

### ISSUE THREAD

**Issue by AvidDriver** [Goldenfreddy0703/Otaku#176]
Anytime I watch an episode, or a movie, it fails to update it on MAL. I have tried to reauth multiple times, ensured the correct watchlist is chose on the settings, rebuilt database, but nothing seems to work. 

Also, just to note my MAL does sort of work, as in it does show my plan to watch, and stuff like that, but it wont update any in progress anime.

**Comment by Goldenfreddy0703** [comment]
Odd mind sending me a log. Mal usually has the most trouble in the past but I will look into it tonight.

**Comment by AvidDriver** [comment]
Sorry, how do I provide a log?

**Comment by Goldenfreddy0703** [comment]
https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

Just install this and you will have the option to upload a log, once its uploaded, just send me the link to the log and all.

**Comment by AvidDriver** [comment]
Thank you, I will do as soon as possible.

**Comment by AvidDriver** [comment]
https://paste.kodi.tv/uqivapokep

Log doesn't seem to say anything about Otaku.

**Comment by Goldenfreddy0703** [comment]
Oh you may have to turn on debug logging, my bad 

https://kodi.wiki/view/Settings/System/Logging#Debug

**Comment by AvidDriver** [comment]
https://paste.kodi.tv/igikajazof

That should be better.

**Comment by Goldenfreddy0703** [comment]
Hey i just noticed something in your log, were you using tmdbhelper to play Otaku stuff? Using tmdbhelper to play Otaku stuff will not update your watchlist sadly due to the episode numbering and that Otaku uses a different database then tmdb.

**Comment by AvidDriver** [comment]
That's what I thought, but I have otoku and TMDBhelper on separate tabs on Arctic Horizon 2.

**Comment by Goldenfreddy0703** [comment]
oh ok so you were using Otaku then. Ok weird, i cannot find the issue on why your Mal is not updated. My guess is that its either due to connections issue where you may have to restart your computer or router or it could just be an issue with the addon itself where you may have to uninstall the addon and clear the appdata of it and start fresh maybe. 

Have you tried Clear Cache and Rebuilding Database and re authenticating Mal and see if that works maybe and is your Watchlist to update set to Mal?

**Comment by AvidDriver** [comment]
Yes to all of that, but I'll try out reinstalling the addon. I mean Otaku worked before with updating MAL, but after some issues with my pc and a fresh windows install, I had to reinstall Kodi. For some reason it just doesn't work now. I'll try reinstalling and seeing what happens, thank you for all of the help!

**Comment by Goldenfreddy0703** [comment]
Anytime but sorry I could figure out the issue. Hopefully reinstalling would work. If not try restarting your PC and router maybe.

**Comment by AvidDriver** [comment]
No worries, and I reinstalled, but it's weird. As in it seems to update the watchlist, but only from the client side? So if I watch the same anime again, it does give an option to resume where I left off from, but it doesn't update it on MAL. Not sure why it's doing this and how it can do it, only from the client side.

**Comment by Goldenfreddy0703** [comment]
Ok very weird, ok the only thing that could be causing this is the skin. Usually skins are weird with updating and usually they aren't. Try switching to the default skins and give Otaku a try and see if it's doing the same thing.

**Comment by AvidDriver** [comment]
I'll do so now, and I thought it could be the skin too, so I just ended up checking MAL from a browser, but it didn't update on there.

**Comment by AvidDriver** [comment]
Tried with default skin, same issue. Going to try to auth MAL again.

**Comment by Goldenfreddy0703** [comment]
Ok, at this point. It maybe best to switch to anilist sense anilist is basically our database for Otaku and all. We will try to look into it tonight tho. 

@Gujal00 sorry to bother you but do you have any ideas what's going on with Mal watchlist. It's a bit weird for this user and I'm not sure why. 

OS: Windows
Kodi: 20.2
Otaku: 0.4.45

**Comment by AvidDriver** [comment]
No worries, I appreciate the time you took to help. It's all good, I'll probably end up waiting for a fix since it doesn't matter that much to me about watchlist, just kinda annoying that's all. Hopefully you guys can figure it out!

**Comment by AvidDriver** [comment]
Quickly want to add, it does say what my last watched is correctly, but it just won't update the watchlist.

**Comment by Goldenfreddy0703** [comment]
> Quickly want to add, it does say what my last watched is correctly, but it just won't update the watchlist.

Ahh last watch does not affect watchlist at all, just affects history of the show you watched.

**Comment by Gujal00** [comment]
playing from tmdbhelper or Otaku should not affect watchlist update as tmdbhelper just calls a route in Otaku and then we do the tmdb2anilist conversion and play. The only thing I would suggest is to check your settings to see if you have update watchlist enabled, this is completely separate from authorising watchlist. See the settings entries below marked with yellow arrow
![screenshot00000](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/4a3f34f3-bc39-4449-af4e-b1dc38a65379)

**Comment by AvidDriver** [comment]
Yes I have those settings enabled. Any idea what it could be?

**Comment by Gujal00** [comment]
Looks like a bug, have to look at the code to see why MAL update is broken in the current release.

**Comment by Gujal00** [comment]
Nah, it works correctly on my Windows dev PC. Just tested with SpyxFamily Season 2 Episode 7 and it updated my MAL list and shows up as I just watched that episode
once 80% of the episode is watched it correctly makes a call `https://api.myanimelist.net/v2/anime/53887/my_list_status` and MAL responds with 
```json
{"status":"watching","score":0,"num_episodes_watched":7,"is_rewatching":false,"updated_at":"2023-11-21T04:37:37+00:00","start_date":"2023-10-08","priority":0,"num_times_rewatched":0,"rewatch_value":0,"tags":[],"comments":""}
```

**Comment by AvidDriver** [comment]
It’s so weird, was working fine with my other windows install so idk what the issue is here. Maybe i need to check if it is able to make a call to the api, and isn’t getting blocked by any firewall. Although if that were the case, then surely kodi just wouldn’t work with video and real-debrid? 

I’ll try to look for something, but yeah I have no idea where to start lol.

**Comment by Goldenfreddy0703** [comment]
Ok that is super odd, I tested as well and works fine for me but a while back, I did hear people have problems with mostly mal watchlist in the past. It's weird. One thing you could probably do is disable ipv6 or do a fresh kodi install maybe cause im not sure why.

**Comment by AvidDriver** [comment]
I was thinking it could be to do with the fact that MAL was authorised previously, and now because I installed Otaku again, it wanted me to authenticate MAL again. But because of that, maybe something weird with MAL not authenticating properly with the api? But if that was the case then I wouldn’t be able to see my lists.

Out of ideas tbh, maybe I’ll give it time but I wanted to see if there was a way I could remove the authentication on MAL side, but I have searched and can’t really find anything.

**Comment by Goldenfreddy0703** [comment]
Ok I also have one last suggestion. On Otaku, watch an episode of anything then when the episode finish, upload one more debug log so we can see what's happening when it's playing the episode.

**Comment by AvidDriver** [comment]
No worries, I’ll have to try in the morning now.

Hugely appreciate you guys for the quick replies and the support.

**Comment by Gujal00** [comment]
Close Kodi
you can edit the settings.xml file in `C:\Users\gujal\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.otaku` replace `gujal` with your username
Delete all the lines starting with `<setting id="mal.` and then start Kodi again

**Comment by Goldenfreddy0703** [comment]
@AvidDriver been a few weeks sense we talked about your issue with Watchlist not updating, how is the status with Mal Watchlist going for you. Is it still not updating?

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this, most people have not had any issues with mal in these past 2 weeks and i think it should be okay to close. We have improved watchlist significantly so we should be good hopefully. If you have any more questions or concerns, pls feel free to reply in here and we will get to you shortly. 

Thank you.
