### ISSUE TITLE
[Suggestion] Intro Skip Times from Anilibria API

### ISSUE THREAD

**Issue by C0nvert** [Goldenfreddy0703/Otaku#177]
Hi, @Goldenfreddy0703 about your API for Intro Skip times.
As a suggestion you can use the anilibria (a russian Anime only Website) API for exact Skip Times.
They provide almost for all Anime Series Skip Times.
Animes are not cut or altered with Ads , so the timings should be the same
As an Example: https://api.anilibria.tv/v3/title?code=jujutsu-kaisen
Under "opening":[,], you will see the Skip Times in seconds.

Should work better than aniskip.

And maybe someone wants to add Anilibria as an Indexer too.

**Comment by Goldenfreddy0703** [comment]
Danggggg, it even gives the Russian streams as well. 

Ok question, I know you said Animes are not cut or altered but does it reach the 22 - 24min mark by anychance like for example spy x family?

One other question, does it use mappings from somewhere by anychance? Example: Anilist, Anidb, Mal, Kitsu, Simkl, ect

**Comment by Goldenfreddy0703** [comment]
@Gujal00 If you don't mind, please add Anilibria as one of our embeds sense he provided an api of the skip times and m3u8 streams.

**Comment by Goldenfreddy0703** [comment]
> But it should nevertheless work if you use the data from anidb like title and ID, create a request with the API (use only title), get the Shows Title and ID and replace then the anidb ID with the anilibria one.

That could work sense the site says ani in it, it's probably or mostly gathering data from anidb so we could just copy the title.

Thank you. We will definitely add this someday.

**Comment by Goldenfreddy0703** [comment]
@joezito129 if you don't mind, I may need you to help with the skip intro and outro in the future when you are back from your hiatus.

**Comment by C0nvert** [comment]
This is the official API: https://github.com/anilibria/docs/blob/master/api_v3.md
If you need help in translating things you can ask me. 
Can help you with German and Russian.

**Comment by Goldenfreddy0703** [comment]
> This is the official API: https://github.com/anilibria/docs/blob/master/api_v3.md If you need help in translating fell free to ask me. Can help you with German and Russian.

Awesome thank you, i should have good translate installed so it should not be a problem.

**Comment by Goldenfreddy0703** [comment]
> what format is the code title? where can I get the code title?

Hey @joezito129 ,Glad you could join us!!!!! If your referring to the title of the anime in the api he provided, its either from anilist or anidb from what i could tell.

**Comment by C0nvert** [comment]
You can, you use the names from anidb for the code titles, but for second cour anime seasons like spy x family it appears to not fully work.
https://api.anilibria.tv/v3/title?code=spy-x-family

It's better if you use a lazy search instead like this (I used a filter, so it shows only the name and ID):
https://api.anilibria.tv/v3/title/search?search=spy%20x%20family%20cour%202&filter=id,names
(decoded string)
https://api.anilibria.tv/v3/title/search?search=spy x family cour 2&filter=id,names


With this API Request, one can you use Keywords. 
e.g. it don't matter if the season on anilibria is called "Spy x Family 2nd Cour" or like on anilist.co "SPY x FAMILY Cour 2"
![image](https://github.com/Goldenfreddy0703/Otaku/assets/16489340/b2492cf4-3263-4d20-bf69-2a0a9ca38964).
It will find the Anime.

You can use the Filter, if you're not sure that the lazy search will output only one hit. Compare the Names and use the ID in the next step to get your links and opening skips:
https://api.anilibria.tv/v3/title?id=9259

**Comment by Gujal00** [comment]
We can already get intro and outro skip times from Anify api if needed.
We can easily add the api call into the exisitng anify provider in Otaku if it is absolutely necessary to move away from aniskip. So far aniskip has been fine.
No point adding a new provider which does not use either anilist or mal id and have their own id and slug with no mapping available.

**Comment by Goldenfreddy0703** [comment]
Hey so i thought about this more and its great but i think we gonna stick with what we have at the moment on the skip times. I like our aniskip and i hope to improve it in the future someday. If you don't mind, please add Anilibria Api to #144 so we can have Russian embeds.

Im gonna go ahead and close this but if you have any questions or concerns, pls feel free to reply in here and we will get them answered. 

Thank you

**Comment by Goldenfreddy0703** [comment]
Omg @C0nvert I completely forgot about you. 😂 I'm jk but kinda almost did.

Ok so good news, me and gujal managed to find better skip times but only for aniwatch and aniwave so you either of those embeds and you will have the best skip times ever, they are amazing.

**Comment by futzumi** [comment]
im currently working on a project. I'm curious about ending times. I've looked at a few animes but there are no ending time stamps in any of the episode ending arrays. One of the animes being [Akame Ga Kill!](https://api.anilibria.tv/v3/title/search?search=akame%20ga%20kill&filter=player)

Is this api only useful for openings? I was looking for an alternative to aniskip and was not expecting to find such an underground api

**Comment by Goldenfreddy0703** [comment]
Actually, we recently updated are skip times to support aniwave or h!anime, enable the h!anime provider sense aniwave is broken and you should be able to have intro and outro skip times for torrents, hope this helps.

**Comment by C0nvert** [comment]
> Omg @C0nvert I completely forgot about you. 😂 I'm jk but kinda almost did.
> 
> Ok so good news, me and gujal managed to find better skip times but only for aniwatch and aniwave so you either of those embeds and you will have the best skip times ever, they are amazing.

Allright 
Saw your answer just now 
Ty for your work !!!  :)
