### ISSUE TITLE
String Translations

### ISSUE THREAD

**Issue by icarok99** [Goldenfreddy0703/Otaku#180]
Looking for help translating the addon into the following languages.
- [x] Arabic
- [x] French
- [x] Portuguese
- [x] Italian
- [x] Turkish
- [x] German

https://github.com/icarok99/Otaku/tree/New-languages/plugin.video.otaku/resources/language

**Comment by Goldenfreddy0703** [comment]
Wow you made so many. Now I feel that it will be hard to add more addon settings lol

**Comment by icarok99** [comment]
> Uau, você fez tantos. Agora sinto que será difícil adicionar mais configurações de addon haha

No need to add

**Comment by icarok99** [comment]
Addon automatically recognizes Kodi language.

**Comment by Goldenfreddy0703** [comment]
Awww hey, I was still interested in this, just been lazy throughout this Christmas, mind if we keep this open so we can add it soon. I just need to do more research on this.

**Comment by Goldenfreddy0703** [comment]
Hey so I'm going to open this and work on it.

**Comment by icarok99** [comment]
@Goldenfreddy0703 I don't talk about you, It's just that no one translated the other languages.

**Comment by Goldenfreddy0703** [comment]
Oh yeah I understand but I still wanna keep this open so I can do some translations.

**Comment by Goldenfreddy0703** [comment]
Hey @icarok99 great news. I have add the rest of the translations so we should be finished.
Added Italian Translations
Added Turkish Translations
Added German Translations 

They are fully finished but i translated every id so im going to have to go back and fix a few that cannot be translated or [@icarok99](https://github.com/icarok99) can.

Im going to go ahead and close this sense they are almost completed. We just need to add finishing touches and we should be good.

**Comment by icarok99** [comment]
@Goldenfreddy0703 I fixed it and opened a pull request.

**Comment by Goldenfreddy0703** [comment]
ehhh unfortunately i did some fixes and other fixes as well. Sorry about that 😅

**Comment by Goldenfreddy0703** [comment]
Hey great news, we have just released so now we should have all the rest of the translations. Thank you for starting on this and showing me how to work on Translations. If we have any issues with translation, we can always make a pr to fix that. 

Thank you
