### ISSUE TITLE
Simkl Watch List Opening 

### ISSUE THREAD

**Issue by shaktoo1** [Goldenfreddy0703/Otaku#183]
Thanks @Goldenfreddy0703  for the best Anime Addon .
I have a suggestion 
when I open my currently watching using simkl it defaults to the first episode and NOT the last watched.
Recently watched shows the already watched episode and does not show the next one.
We need to have the " Next up " option like other addons have for trakt  OR make the default setting of the currently watching to default to last watched & not the frst episode.

**Comment by Goldenfreddy0703** [comment]
Oh we should already have a next up for simkl, it's probably either bugged or simkl is. We will take a look at it soon.

Thank you

**Comment by Gujal00** [comment]
I dont have simkl account, it was joezito who added this, he may be able to comment on it if it is feasible

**Comment by Goldenfreddy0703** [comment]
> I dont have simkl account, it was joezito who added this, he may be able to comment on it if it is feasible

Ahh makes sense, we will get Joezito to look into this soon.

Thank you

**Comment by joezito129** [comment]
Next up is already added for Simkl I did find a small bug (will fix soon), but it should still work as long as the show is added in your database.
For the currently watching to default to last watched & not the first episode, have you tried enabling Smart Episode Scrolling, unfortunately this setting only works in list views so if you are using a nonlist view in kodi this setting will not work. Im not sure any other way to make kodi start in the middle of the list (ie. current episode) but maybe someone else may know.

**Comment by shaktoo1** [comment]
The Currently watching has been fixed and it opens to the last watched ! Thanks you guys! 👍 
However there are 2 Bugs 1- Next Up does not work. After watching an episode it should go to the next one but it shows the last watched hence of no use. 2- Metadata not being fetched. No metadata = Names of episodes etc is being fetched. Only for the watched episodes ? 
From Episode 245 onwards of One piece the opening introduces first a recap & then the opening intro... so skipping the intro isn't working as such  .. maybe if there is a user defined time skips introduced as in seren  & one for Outro as well if possible.
👍

**Comment by shaktoo1** [comment]
I had the smart episode scrolling clicked but its  only last few days it jumps to the last watched & never used to di it before

**Comment by Goldenfreddy0703** [comment]
Hey so we have improved simkl recently so im going to go ahead and close this sense we fixed you main issue but about the 2 bugs, i may have answers for them.

1. Next Up kinda works, its kinda a mystery with it but @joezito129 should probably have that fixed so we should be good but if not, we will take a look at it. 
2. Episode meta is sometimes a hit or miss when it comes to artwork or meta but thats cause we use Simkl episode meta and thats the only episode meta thats out there. 

Im going to go ahead and close this issue but if you have any questions or concerns, please feel free to reply here and if something is not working related to your issue, we will open this back up and look into it more.
