### ISSUE TITLE
MAL Watchlist - Next up filter out non aired shows

### ISSUE THREAD

**Issue by avallete** [Goldenfreddy0703/Otaku#184]
Hey there !

Right now, I do use Otaku with MAL watchlist and progress tracker. It work like a charm.

One annoying thing that I noticed tough is that when I choose the "Next Up" option, I get all the animes in my "watching" list.
Even if for some of them, the next episode hasn't been aired yet (therefore can't be watched). 

It would be great if when the only remaining "to watch" episodes of a show are unaired ones, the show disappear from the list, until this episode is actually available for watching.

**Comment by Gujal00** [comment]
Seems to be an issue on MAL side. It was working correctly earlier but now no difference between `Next Up` and `Currently Watching` now
The api call is `watching?next_up=true` for next up and `watching` for currently watching. The response from MAL is identical for both calls now, so cant do much unfortunately

**Comment by Gujal00** [comment]
MAL api does not have a `Next Up` endpoint. We were making the list by using a simple logic of the current episodes watched versus the num_episodes in that series. Earlier MAL used to return only the number of aired episodes and the above logic worked correctly. However it looks like they are now returning total episodes instead of aired episodes, so the above logic fails. Can't do much for now. Have to figure out a way to see if MAL can return number of aired episodes as before

**Comment by avallete** [comment]
Thanks for your quick response ! Indeed I had a look to MAL api reference It looks like there is no easy way to get this info. I'll attempt a request over their discord in the future asking if the api team could add this field in the responses objects.

In the meantime I tried to fall back to anilist, by importing my watchlist in it. But I get an error whenever I attempt to authenticate in the extension "username or password invalid".

I've tried to re-auth multiple times, clean the extension cache, revoke the app on my anilist account and re-authorize it. Use my actual username or my account email. Every time I ensure I properly copy the token. Always get the same error across attempts. So I wanted to report it, see if someone can reproduce. 

BTW took a look at the logs, did not see anything standing out, seems like it's a handled error that does not produce logs. But maybe there is some debug mode to activate ?

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this sense mal does not have a next up, mal is kinda a pain when it comes to there api and there is really no easy way to get this info. One suggestion that might help is doing research on the Jikan Rest api and see if there is a unofficial mal next up on there but i doubt it.

If you have any questions of concerns, please feel free to reply in here and we will answer or look into to this depending on what we do.
