### ISSUE TITLE
TMDB Player no play HEVC.265 sources

### ISSUE THREAD

**Issue by Teddy503-anon** [Goldenfreddy0703/Otaku#186]
Hey man,

Let me start off by thanking you and your team for giving us Otaku. Best anime add-on I've ever used.

I'm seeking help man. After the latest update enabling the TMDB player support, none of my HEVC 265 sources will play. All other non HEVC sources play fine.

My logs say something like "Playlist Player: skipping unplayable item: 0, path [...]

Anyways hope to hear from you man, but if not that's okay too.

Thanks again! Cheers!

**Comment by Gujal00** [comment]
Enable debug logging in kodi setinngs, restart kodi,  and run through all the steps to replicate the issue, disable debnug logging and then upload the log using kodi logfile uploader and provide the shortlink that the uploader provides here

**Comment by Teddy503-anon** [comment]
Hey Gujal,

Here is the URL:
https://paste.kodi.tv/iniburadex

**Comment by Gujal00** [comment]
From the log you are trying to Play Episode 25 of Jujutsu Kaisen, and there is no such episode
That series had only 24 episodes
https://anilist.co/anime/113415/Jujutsu-Kaisen/

This is the issue with tmdbplayer as it follows tmdb numbering, and some times TMDB are pretty silly about numbering anime episodes. They treat the show as a single season of 47 episodes so far which is incorrect.

Play it from within Otaku and it will find the episode you are trying to play as https://anilist.co/anime/145064/Jujutsu-Kaisen-2nd-Season/  Episode 1

**Comment by Teddy503-anon** [comment]
You are absolutely right, there's only 24 episodes in S1. I played the same episode but in S2, it worked flawlessly. Thank you so much and Merry Christmas 🎄!
