### ISSUE TITLE
Real-debrid NYAA scrape results.

### ISSUE THREAD

**Issue by zacstonephoto** [Goldenfreddy0703/Otaku#189]
I’m using real-debrid and since the v52 update half the time the wrong episodes play even though it appears to be the correct episode. Usually it will play an episode from another season or the episode that was just watched again. When I ‘rescrape’ the episodes I then get different sources that work better. It also goes from 14 to 16 torrent sources returned upon a rescrape.

I have to now rescrape every time to get stable and correct links. It seems to be the NYAA results that differ. Even when providers are set to only NYAA, it still won’t show me certain sources until I specifically select to rescrape. Is there a source limit that’s overridden when you rescrape or some other setting I’m unaware of to change? Thanks in advance.

**Comment by Gujal00** [comment]
rescrape adds this additional term `"Batch"|"Complete Series"` to the search query.
nyaa search is by title matching and is always a hit or miss. the v52 update has nothing to do with this, nyaa has always been like this.
Which anime are you searching for and which season and episode?

**Comment by Goldenfreddy0703** [comment]
Heyyyy @zacstonephoto , sorry its been a few months but recently, we just made a release that adds a new setting called "Scrape Torrents Consistently", what it will do is find the right season and part numbers and have them go to the top of the list and you should be able to find the right sources when finding episodes of a season or part of an anime. 

Im gonna go ahead and close this but if you have any questions or issues or concerns, feel free to reply in here and we will get back to you and open this back up.
Thank you
