### ISSUE TITLE
Add option to hide next page button on widget view

### ISSUE THREAD

**Issue by OdinIsLord** [Goldenfreddy0703/Otaku#191]
Hi, next page button can ruin your view on the Spotlight. An option to hide it would be nice.

![ApplicationFrameHost_18veTnl7W1](https://github.com/Goldenfreddy0703/Otaku/assets/97923430/f290d34a-d7af-4368-868a-184abb434836)

**Comment by Goldenfreddy0703** [comment]
Question, does seren have this option?

**Comment by OdinIsLord** [comment]
Didn't use Seren in ages but I just installed it to check and it does have the option.

![kodi_MMuKatcsER](https://github.com/Goldenfreddy0703/Otaku/assets/97923430/e51f4b81-b63c-4ba2-8834-70eb8ff6e52b)

**Comment by Goldenfreddy0703** [comment]
Ok great, will see how serens option works and will try to make an option on Otaku for it.

Thank you

**Comment by TwilightMercy** [comment]
Also available in Fen

**Comment by Goldenfreddy0703** [comment]
Hey so funny story, i looked at Serens code and my mind went blank due to how the widget detection works so this may take longer to add then i thought. Hopefully either @joezito129 or @Gujal00 can do this one.

**Comment by OdinIsLord** [comment]
@Goldenfreddy0703 I will go ahead and close this as not planned with your consent?

**Comment by Goldenfreddy0703** [comment]
Heyy @OdinIsLord , this is still planned however, our contributors don't really use kodi skins and I'm still unsure on how widgets can be coded and all. If we could get help or if somebody can show me some documentation, I definitely will add this future.

**Comment by OdinIsLord** [comment]
> Heyy @OdinIsLord , this is still planned however, our contributors don't really use kodi skins and I'm still unsure on how widgets can be coded and all. If we could get help or if somebody can show me some documentation, I definitely will add this future.

Good to hear. Wish I could help.

**Comment by OdinIsLord** [comment]
![kodi_MCvKayvxS4](https://github.com/Goldenfreddy0703/Otaku/assets/97923430/899e331b-be10-41d4-aff7-46f4a29cc550)
![kodi_cwLsqw2EFC](https://github.com/Goldenfreddy0703/Otaku/assets/97923430/4b06ff91-4644-4e65-be4d-2d7bac06c87d)
![kodi_LmvQIlXaoM](https://github.com/Goldenfreddy0703/Otaku/assets/97923430/85ea260c-179b-46b3-a972-7572d9671fc2)
![kodi_5rapI6px8y](https://github.com/Goldenfreddy0703/Otaku/assets/97923430/8afbd8d1-ecde-4cd3-9ba0-68bd90b6a42a)

Maybe the team would reconsider for the rest of us that use this beautiful add-on with skins.

**Comment by theasguard** [comment]
> Heyy @OdinIsLord , this is still planned however, our contributors don't really use kodi skins and I'm still unsure on how widgets can be coded and all. If we could get help or if somebody can show me some documentation, I definitely will add this future.

seren\resources\lib\modules\list_builder.py
seren\resources\lib\modules\globals for "g"
seren\resources\settings.xml
	Line 132:         next_args = params.pop("next_args", None)
	Line 161:                     not (g.FROM_WIDGET and g.get_bool_setting("general.widget.hide_next"))
	Line 166:                     if next_args:
	Line 167:                         g.REQUEST_PARAMS["action_args"] = next_args
	Line 174:                         menu_item=g.create_icon_dict("next", base_path=g.ICONS_PATH),
	
	Line   48: 				<setting id="general.widget.hide_next" type="boolean" label="30452" help="">

**Comment by Goldenfreddy0703** [comment]
seren\resources\lib\modules\list_builder.py
> seren\resources\lib\modules\globals for "g"
> seren\resources\settings.xml
> 	Line 132:         next_args = params.pop("next_args", None)
> 	Line 161:                     not (g.FROM_WIDGET and g.get_bool_setting("general.widget.hide_next"))
> 	Line 166:                     if next_args:
> 	Line 167:                         g.REQUEST_PARAMS["action_args"] = next_args
> 	Line 174:                         menu_item=g.create_icon_dict("next", base_path=g.ICONS_PATH),
> 	
> 	Line   48: 				<setting id="general.widget.hide_next" type="boolean" label="30452" help="">
> 	

@theasguard can you actually try to code this setting in? That would be amazing if you could. 🙏 

Thanks

**Comment by theasguard** [comment]
> seren\resources\lib\modules\list_builder.py
> 
> > seren\resources\lib\modules\globals for "g"
> > seren\resources\settings.xml
> > Line 132:         next_args = params.pop("next_args", None)
> > Line 161:                     not (g.FROM_WIDGET and g.get_bool_setting("general.widget.hide_next"))
> > Line 166:                     if next_args:
> > Line 167:                         g.REQUEST_PARAMS["action_args"] = next_args
> > Line 174:                         menu_item=g.create_icon_dict("next", base_path=g.ICONS_PATH),
> > Line   48:
> 
> @theasguard can you actually try to code this setting in? That would be amazing if you could. 🙏
> 
> Thanks

hey ill go over the code, dont get your hopes up quick though theses pys in seren are crazy, may take some time to figure out how it all goes together.

**Comment by OdinIsLord** [comment]
> hey ill go over the code, dont get your hopes up quick though theses pys in seren are crazy, may take some time to figure out how it all goes together.


Thanks so much for looking into this. Wish I could help, yesterday Arctic Fuse got a huge fullscreen update and this feature is so needed now. Fingers crossed.

**Comment by joezito129** [comment]
I added the setting on Otaku please test and let me know if it works for you.

**Comment by Goldenfreddy0703** [comment]
Hey so we just made a release so hopefully this issue should be resolved. Huge thanks to @joezito129 for figuring this out.

**Comment by OdinIsLord** [comment]
> I added the setting on Otaku please test and let me know if it works for you.

Works flawlessly, kudos!
