### ISSUE TITLE
TMDB Helper Player Issues

### ISSUE THREAD

**Issue by treb118** [Goldenfreddy0703/Otaku#196]
Hey All,

I adore the addon - it's an absolute game changer

I've been having some issues with the TMDB Helper player feature ever since that was released a few months ago. At first it would work for a while and then break, when I deleted the cache etc it would work again. Now no matter what I do I can't get anything to open via Otaku

Attached is my log, any ideas? Thanks in advance!

[Otaku Log.txt](https://github.com/Goldenfreddy0703/Otaku/files/13880705/Otaku.Log.txt)

**Comment by Goldenfreddy0703** [comment]
Aghhh I knew someone would ask about this, yeah tmdb2anilist is down unfortunately so will have to either get someone to host it or someone to put the whole code in the tmdb.py.

**Comment by Goldenfreddy0703** [comment]
Heyyyy @treb118 good news, i managed to get Tmdb Helper Player working today but this was very hard to code. Its on another branch right now but i hope to release soon. 

Right now @Gujal00 just has to make it python 2 compatible and help me with changing request to client.request sense im still clueless on how to use client.request. 

Hope this helps and hopefully we should have this released soon.

**Comment by Goldenfreddy0703** [comment]
Hey so im actually going to close this but i big release will be coming very soon that will have tmdb player support working.

**Comment by Goldenfreddy0703** [comment]
Heyyyy great news, we have finally released and we hope tmdb helper player works now. If you have any issues, please feel free to reply back to us and we will look further into it. 

Thank you

**Comment by braniak87** [comment]
Is it just me/ am I too stupid or does this not work? When I try to play anything from otaku via tmdb helper I always get „No TVDB_ID found“

**Comment by Goldenfreddy0703** [comment]
Can you give me a few animes, it's possible are tmdb helper code might have broke again

**Comment by braniak87** [comment]
> Can you give me a few animes, it's possible are tmdb helper code might have broke again

To me it seems rather an exception if an anime works.
Here are a few from my library where it fails:

- Go! Go! Loser Ranger!
- The wrong way to use healing magic
- Ragna Crimson
- Shangri-la Frontier
- Jujutsu Kaisen

**Comment by Goldenfreddy0703** [comment]
Ahh thanks ok will look into this tomorrow then.

**Comment by Gujal00** [comment]
All five of them do not have id mappings in tmdb site. So will never work with Otaku through tmdb_helper
TMDB do their thing with Anime and do not agree with any of the anime sites on the season or numbers

`https://api.themoviedb.org/3/tv/215799/season/1/external_ids?api_key=`

`{"id":318892,"freebase_mid":null,"freebase_id":null,"tvdb_id":null,"tvrage_id":null,"wikidata_id":null}`

As tvdb_id is `null` Otaku is correctly reporting `No TVDB_ID found`
You have to search for the anime and view it from within otaku and it will work
This is the kind of response we get from tmdb api for all of the above shows

**Comment by Goldenfreddy0703** [comment]
anilist_id | mal_id | mal_dub_id | mal_picture | kitsu_id | anidb_id | thetvdb_id | thetvdb_season | themoviedb_id | imdb_id | trakt_id | anime_media_type | global_media_type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
158417 | 53770 | 53770 | 1183/141489.jpg | 46840 | 17703 | 428030 | 1 | 215799 | tt28082379 | 200456 | TV | SHOW
137908 | 49613 | 49613 | 1733/140802.jpg | 44981 | 16537 | 415440 | 1 | 131365 | tt15237152 | 203893 | TV | SHOW
146493 | 51297 | 51297 | 1763/140359.jpg | 46000 | 17263 | 417983 | 1 | 195459 | tt28685470 | 199863 | TV | SHOW
151970 | 52347 | 52347 | 1500/139931.jpg | 46241 | 17501 | 421855 | 1 | 205050 | tt28776190 | 196794 | TV | SHOW
113415 | 40748 | 40748 | 1171/109222.jpg | 42765 | 15275 | 377543 | 1 | 95479 | tt12343534 | 158594 | TV | SHOW

Actually @Gujal00 , these 5 animes actually do have tmdb id's from looking at my database and it looks like they do contain a tvdb_id so im going to have to take a look at our tmdb helper code again sense we added new ids recently.

**Comment by Gujal00** [comment]
Yes I know. but the entire tmdb_helper logic you have needs to be redone as it expects tvdb id and season number. There is no mapping of tmdb season in the mappings db

**Comment by Goldenfreddy0703** [comment]
> Yes I know. but the entire tmdb_helper logic you have needs to be redone as it expects tvdb id and season number. There is no mapping of tmdb season in the mappings db

That is true but what we can do is add a fallback where the tmdb season number which could also be the tvdb season number if its a number 1 or i could possibly add the tmdb season number for our database as well to help with tmdb results more accurately.
