### ISSUE TITLE
[Feature Request] Multiple (search allow mature, manual sync, more)

### ISSUE THREAD

**Issue by Nemes15** [Goldenfreddy0703/Otaku#197]
Hi Freddy and fellow devs,

Thank you for this addon, I had so much trouble moving my "wall of dubs" as I call the wall of blurays (which looks great in the house but is very inconvenient to watch things on the fly), into my bluray player, using a mediaplayer for this instead is a life saver! I support the creators and get convenience my streaming service do not provide!

To get to my feature requests.

1.
The "Sort & Filter > Enable Searching Mature titles only" is very annoying! I understand Hentai should be hidden by default but simple shows such as Peter Grill (which is pretty colorful but mostly comedy) get hidden too, actually, it does not show up at all no matter the settings.
As I said, I understand Hentai needs to be limited by default for users but could it change from a "yes/no" into a "If/or" option? This way you could add an extra box that "if results are found "publish" else "search mature""
This would help a lot because I keep swapping between settings because there are no results :/

2. This might be the skin I'm using (AH2) but I can only clear my full search history. I don't want that, I want to clear singular events that are no longer useful

3. I watch dubs (yes, I am that dweeb, nerd, annoying person and anything sub watchers want to throw at me) I know the raw is better, I know the Subs are often better. But I watch while doing other things I usually threw a bluray in for. The kids also watch dubs since that is what's on streaming so my default is dub.
Is it possible to get a dub calendar? I know it is a lot to ask because it requires a lot of scraping (or often setting release dates to a few weeks later). But there are various sources that show dub availability and progress and would help out dub watchers a lot (https://animeschedule.net/ has it somewhere in the code, I'm not a coder but I know its there, as an example, and I do know it is a lot to ask). Maybe we could get a dub/sub section or, for less of an overhaul, dub flags? Even if it is only for each episode (source released sub source - releases dub english)

4. Last one, my kids watch Pokemon on Netflix and other sources, however they're at "Master Journey"? Iirc but nothing shows up. There are 25+ seasons and only a few show up when searching. 

5. Last one, can we get a "sync with services" option in the settings so we can update our Anilist/mal/kitsune or what you are using by the press of a button in settings (so it doesn't flood)

Thank you for all the hard work, I and my blurays love you guys

**Comment by Goldenfreddy0703** [comment]
Ahhh so many questions but i will answer them but not all of them. 

1. I agree with this and i had a talk with Gujal00 about this but we mainly just made that option for only one or two animes which was Redo of the Healer or Interspecies Reviewers, we do already have the code made where it would have the mature results on the bottom and labeled with adult in it but we just never considered adding it just cause it looked weird. 

2. About this, most addons like youtube, seren, fen don't really have the option to clear singular events, if you can show me a kodi addon that does this, i will consider adding this feature. 

3. About having a dub calendar, we mainly used anichart to provide us a calendar cause thats how SwagOtaku originally did it but for dub calendar, that would probably be too hard to add cause most anime calendar websites don't offer api's or mappings from either simkl, anilist, kitsu, mal, anidb and it would be very complicated adding a dub calendar, also there is dub airdates as well which is a pain. You may have to stick with turning on the dub anime filter in the Otaku General settings sense your a dub person. 

4. When it comes to Pokemon, there is alot of seasons that are split and anilist sometimes has problems with Pokemon, to get more seasons in Pokemon, you may want to go into the context menu and use the find all anime button which may help show all the seasons and all in order and everything.

5. Sadly no, we tried experimenting with watchlist and did a whole code rewrite on it and we were just unable to have them synced unfortunately but as a workaround, you could use mal sync browser extension and have it sync to all your watchlist if you keep it running in the background, there should be a setting for it and a way to sign into all your watchlist and all. 
https://malsync.moe/

**Comment by Goldenfreddy0703** [comment]
EDIT: The website you picked from anime to get dub calendars is actually a pretty good site to get dub animes and allow the use of anilist id's so i will have @joezito129 look into this. Thank you

Documentation: https://animeschedule.net/api/v3/documentation
Example: https://animeschedule.net/api/v3/anime?anilist-ids=140960

**Comment by Goldenfreddy0703** [comment]
Heyyyyy so we are gonna go ahead and close this Feature Request for now but we managed to get 2 and 4 completed and we will release in a couple of days. About 3. im still going to keep this in mind cause dub people could probably use dub airdates but we are not sure if there is a way to have two airdates which is a drawback. 

We Declined your request on 1 and 5 so we will go ahead and close this. 
Thank you and also thank you for pointing out 2 and 4, this helped us fix bugs on 2 and added a needed future on 4.
