### ISSUE TITLE
Subtitles in French no way to change the source

### ISSUE THREAD

**Issue by giventofly** [Goldenfreddy0703/Otaku#200]
Hi, I been getting a problem of the video having french subtitles and there isn't a way to force a source video change, is this something to be implemented in the future?

**Comment by Goldenfreddy0703** [comment]
Umm that's odd, were you using torrents or embeds. If embeds, what embed did you use? Did you edit subtitle settings and all to English and stuff?

**Comment by giventofly** [comment]
I just clicked to watch and it automatically selected the source, I have english set for subtitles

**Comment by Goldenfreddy0703** [comment]
Weird, whats the anime and you may wanna go to context menu and select source so that way you can choose the source instead and see if other streams have french

**Comment by Gujal00** [comment]
@giventofly 
Go to Settings-Provider tab and disable other language providers and only have multisub and your preferred language providers

**Comment by giventofly** [comment]
It was mashle and dead mount death play, happened the same.

Will try the @Gujal00 suggestion later

**Comment by icarok99** [comment]
Here it is normal even with all providers activated 

![Screenshot_2024-01-21-10-22-04-677_org xbmc kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/1d9cc4a2-3f57-4515-b944-2e141277ac3f)

![Screenshot_2024-01-21-10-25-50-615_org xbmc kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/6e5e70f0-045c-46c4-8edf-e5b45282a678)

**Comment by icarok99** [comment]
@Goldenfreddy0703 @Gujal00 The only problem I found is if my Kodi has a Portuguese language and the subtitle preference is in English, the subtitle of the anime currently playing  is in Portuguese.

**Comment by icarok99** [comment]
This problem started with the update 0.4.60
I downloaded previous versions to check

**Comment by Goldenfreddy0703** [comment]
> This problem started with the update 0.4.60
> I downloaded previous versions to check

Question, are you sure it was not 0.4.61 cause all those translations we merged kinda made it hard to work with at first. 

Also if you guys were using aniwatch and had your regional settings set to Portugal then that could explain a lot sense gujal connected aniwatch with region.

**Comment by Goldenfreddy0703** [comment]
> @Goldenfreddy0703 @Gujal00 The only problem I found is if my Kodi has a Portuguese language and the subtitle preference is in English, the subtitle of the anime currently playing  is in Portuguese.

One last question, what embed were you using, if aniwatch then that could explain anot.

**Comment by m-spitfire** [comment]
> > @Goldenfreddy0703 The only problem I found is if my Kodi has a Portuguese language and the subtitle preference is in English, the subtitle of the anime currently playing  is in Portuguese.
> 
> One last question, what embed were you using, if aniwatch then that could explain alot.

I had the same problem, after disabling aniwatch, it seems to be finding subs in english instead of Portuguese.

**Comment by icarok99** [comment]
> > This problem started with the update 0.4.60
> > I downloaded previous versions to check
> 
> Question, are you sure it was not 0.4.61 cause all those translations we merged kinda made it hard to work with at first.
> 
> Also if you guys were using aniwatch and had your regional settings set to Portugal then that could explain a lot sense gujal connected aniwatch with region.

Yes I'm sure it's version 0.4.60

![Screenshot_2024-01-21-12-40-17-016_org xbmc kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/b30ee29b-b83e-4f4c-9a37-36759c408dbb)

**Comment by icarok99** [comment]
> > @Goldenfreddy0703 @Gujal00 The only problem I found is if my Kodi has a Portuguese language and the subtitle preference is in English, the subtitle of the anime currently playing  is in Portuguese.
> 
> One last question, what embed were you using, if aniwatch then that could explain alot.

Aniwatch, but the selected language preference was English

**Comment by Goldenfreddy0703** [comment]
> I had the same problem, after disabling aniwatch, it seems to be finding subs in english instead of Portuguese.

Ok awesome so looks like we should connect aniwatch with the subtitle settings instead of the regional settings that gujal did in the past.

Thanks for letting me know

**Comment by Goldenfreddy0703** [comment]
Ok so @giventofly @icarok99 and @m-spitfire , i looked into and made a couple of changes that should hopefully resolve your issue for any user that uses Aniwatch. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/480ceb22-b141-442b-8abc-8809c0fed3e7)
Ok so i made a release that should have where Aniwatch subtitles will be based on the subtitles settings by default in the Playback Category. I have also added an option called Region Subtitles which sets Subtitles based on the Region your in. 

Hopefully this should fix #200 but just encase, Please test the latest release that should be online and tell me if it works so we can close this issue.

**Comment by Goldenfreddy0703** [comment]
> Yes I'm sure it's version 0.4.60

I don't think so, we had Aniwatch for a long time where subtitles were always based by region if you were to change your region settings, Reason why we did this was cause Gujal coded it this way and it made sense to me. Around version 0.4.61, we introduced your translation changes which is probably why this issue was brought up so any version you choose will basically have this issue. 

Also 0.4.60 was just embed extraction changes that did not bother with any embeds nor players so is shouldn't have been 0.4.60 at all.

**Comment by icarok99** [comment]
@Goldenfreddy0703 With this update, the problem was resolved. Post can be closed.

**Comment by Goldenfreddy0703** [comment]
ok awesome, now i just need to know @giventofly if he was using aniwatch or not. If he was then this problem was solved.

**Comment by giventofly** [comment]
Sorry for the delay, tested now and seems to be working perfectly. thanks

**Comment by Goldenfreddy0703** [comment]
Awesome thanks
