### ISSUE TITLE
[suggestion] A menu item for latest viewed

### ISSUE THREAD

**Issue by giventofly** [Goldenfreddy0703/Otaku#203]
Problem:

Every time I want to see a show I need to do a search and select from there

Possible Solution:

keep a list of the latest 10 watched so they can be directly accessible when entering

**Comment by Goldenfreddy0703** [comment]
Im sorry but im a bit confused on what your asking. Do you want like a history menu basically so when you start Otaku, you will see like 10 watched items?

If so, we actually have watchlist and if you pair one of those watchlist, you can access that watchlist and go to a menu called Current where is shows the history of anime you watched.

**Comment by giventofly** [comment]
The watchlist might be what I'm missing probably, will give it a try

I'm talking about the latest watched only tracks the last show, was asking to track the latest 10 for example, but the watchlist might work, will give it a try, thanks
