### ISSUE TITLE
Simkl new sort also effects continue playing and next

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#205]
could you add in so itll exclude these 2 simkl lists from displaying last added as it doesnt update the current shows in them via the new sort setting, it instead also sorts them to last added, so recently updated is best for those 2 lists.

**Comment by Goldenfreddy0703** [comment]
Hey, I'm not really sure what you mean but if you do want it to recently updated, you can go to watchlist setting and set the sort order to Last Updated instead of Last Added. 

Tell me if that helps.

**Comment by Goldenfreddy0703** [comment]
Hey, I'm not really sure what you mean but if you do want it to recently updated, you can go to watchlist setting and set the sort order to Last Updated instead of Last Added. 

Tell me if that helps.

**Comment by Goldenfreddy0703** [comment]
Hey so been about a week sense i heard a response so im gonna go ahead and close this and assume this helped out a bit. If you are still facing issue relating this this issue, i will open this back up and look into it more. 

Thank you
