### ISSUE TITLE
Random forward skipping

### ISSUE THREAD

**Issue by obsydion** [Goldenfreddy0703/Otaku#207]
I've been having a strange issue where the show randomly skips forward a few seconds. It happens several times during the show and it is very jarring. It's not buffering or pausing, just skipping a few seconds ahead. with no warning.
There isn't an issue with my network because all other add-ons are behaving as normal. I have the latest version of Otaku, Kodi etc. My device is a Shield TV Pro 2019.

**Comment by Goldenfreddy0703** [comment]
Funny story, we actually worked on that yesterday and I didn't release today even tho I had all day. 😅

For now disable aniwave provider for now until we release. Sorry for the inconvenience.

**Comment by Goldenfreddy0703** [comment]
Hey so good news, apparently I can edit files on github mobile and I made a release so hopefully this should fix the skipping issue. 

I'm gonna go ahead and close this but if you have any problems, feel free to reply and we will reopen this. 

Thank you.
