### ISSUE TITLE
Request to change the otaku animess source to the tanoshi digital source.

### ISSUE THREAD

**Issue by icarok99** [Goldenfreddy0703/Otaku#208]
The source otakuanimess changed address and now has protection cloudflare.

New source `https://tanoshi.digital/`

**Comment by Gujal00** [comment]
Seems to be no cflare and working fine. Even if cflare protection is turned on in your location, try running with flaresolverr and it should work

![screenshot00000](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/cba78369-6eb4-4513-b9d6-42f052ecb003)

**Comment by icarok99** [comment]
> Parece não haver clarão e está funcionando bem. Mesmo que a proteção cflare esteja ativada em sua localização, tente executar com flaresolverr e deve funcionar
> 
> ![captura de tela00000](https://private-user-images.githubusercontent.com/17394059/303875376-cba78369-6eb4-4513-b9d6-42f052ecb003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MDg3NTEsIm5iZiI6MTcwNzYwODQ1MSwicGF0aCI6Ii8xNzM5NDA1OS8zMDM4NzUzNzYtY2JhNzgzNjktNmViNC00NTEzLWI5ZDYtNDJmMDUyZWNiMDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDIzNDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2U1NGI4YWJkYWI3ODNmMTI2YWZiZTAwMTU1YjNjMmI1MDc1NTNjOWViYTVkNTYwYWY2ZDA0MGE1NzAwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eSRCY913P7eoulnQq19xHoQFXibDD9SOLevpfGJQLEs)

Another reason to change the font is that many of the animes have very low resolution and the font is not correctly naming the animes.

**Comment by icarok99** [comment]
Of the 20 animes shown on the first page, only 7 have the correct name. Website owner's fault.

**Comment by icarok99** [comment]
Site was closed and those responsible for the site were arrested in the anime operation.

**Comment by Goldenfreddy0703** [comment]
Aww that sucks, sorry to hear that. Hopefully there is an alternative out there.
