### ISSUE TITLE
Otaku not working on firestick

### ISSUE THREAD

**Issue by CaptainFeatherHammer** [Goldenfreddy0703/Otaku#209]
Hey guys I just got Otaku on Kodi a couple of weeks ago and it was working beautifully, now all of a sudden whenever I pick an episode and it loads in I get kicked out of Kodi altogether or I get an error telling me to check my log but nothing appears there. Can anyone help me because almost no other anime apps are working on Kodi anymore and this was my saving grace. I appreciate the help if I can get any.

**Comment by Goldenfreddy0703** [comment]
Ok so reason why is cause aniwave vidplay is not skipping to the next source correct so for the time being you could either disable aniwave embed or by going into the context menu and selecting "source select" and then choosing a source after that and that should do the trick.

**Comment by CaptainFeatherHammer** [comment]
It worked, thank you so much!

**Comment by Goldenfreddy0703** [comment]
Hey anytime, im going to go ahead and close this issue but if you try aniwatch, vidplay should be blocked so you should be good.
