### ISSUE TITLE
[Bug/Issue] Wrong name parsing when using UpNext folder with AniList compared to using the "Current" folder

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#211]
Okay, here are the details and I'll share screenshots down below showing the issue.

First of all, since Otaku doesn't support any sort of Trakt implementation within the addon's settings. I tend to use the official Trakt addon found in Kodi's Official Repository. The addon has a setting when you can universally Scrobbe any of your shows and movies from any addon when you set it up with your account, etc. Well, the issue lies when I play any episodes from within my UpNext folder. The Trakt addon can't detect the Episode being played due to the different way the name parsing shows. So, it doesn't kick in the Trakt scrobbe, unless I use the **Current** folder instead and look for the show, then episode manually. I could always do that. However, I like the less hassle way of just going into the **UpNext** folder instead and I can just **one-click** the in next episode from that exact show instead of doing too many clickings and scrollings specially since I have multiple shows within the **Current** folder. 

So, in conclusion I was wondering if this is a thing that can be corrected for the Up Next folder. So, it starts showing the correct name parsing whenever there's a new Episode available to watch. That way the Trakt addon will be able to recognize the correct name parsing and successfully scrobbe the Episodes same as it does when you play them by going into the official title of the show, season and click on the Episode.

Here are some screenshots showing the difference in name parsing when using the Up Next folder and navigating manually into the title, season, and episode.

**Current** folder name parsing.
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/285ffa76-fbd4-4df8-b529-8b01a28489c2)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/b0c6a4b4-2d0a-496d-a2b9-e6706493f746)

**Up-Next** Folder name parsing.
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/fe03c666-3ff7-4690-99cb-9888d61f9028)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/50837751-d056-400e-bd51-40c9977109cf)

**Comment by Goldenfreddy0703** [comment]
Hey so UpNext is quite weird when it comes to naming and episode which honestly, i don't understand at all, you may wanna ask @Gujal00 about this sense i know nothing about NextUp unfortunately. Now about your trakt scrobbling situation, you may not be able to scrobble every anime cause reason why is cause anime has a different database then what trakt offers, the closest thing to trakt i would recommend is simkl cause simkl is basically like trakt but with an anime supported database. It also supports trakt integration so you can import your trakt and all.  

If you don't mind, see how Seren does there UpNext for any anime show and see how there headings and titles are labeled and provide screenshots and maybe there is a small possible chance we could match that for our NextUp.

**Comment by Nuklear92** [comment]
> Hey so UpNext is quite weird when it comes to naming and episode which honestly, i don't understand at all, you may wanna ask @Gujal00 about this sense i know nothing about NextUp unfortunately. Now about your trakt scrobbling situation, you may not be able to scrobble every anime cause reason why is cause anime has a different database then what trakt offers, the closest thing to trakt i would recommend is simkl cause simkl is basically like trakt but with an anime supported database. It also supports trakt integration so you can import your trakt and all.  
> 
> 
> 
> If you don't mind, see how Seren does there UpNext for any anime show and see how there headings and titles are labeled and provide screenshots and maybe there is a small possible chance we could match that for our NextUp.

Absolutely, here it's;

Seren's Up-Next

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/6ca13e28-5dae-4f3e-ab64-8ad318bc3a46)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/458a70fc-aaab-454b-9e53-da4af342885b)

As you can see, the name parsing is also the correct one.

**Comment by Goldenfreddy0703** [comment]
Ok interesting, thank you very much, in the future lets make Seren NextUp like Otaku NextUp but only for name parsing and headers. Maybe @Gujal00 or @joezito129 can look into this but it may take some time. 

Thank you

**Comment by Goldenfreddy0703** [comment]
If you don't mind, im going to make this an enhancement sense the bug is just with trakt not scrobbling due to Otakus name parsing and all.

**Comment by Nuklear92** [comment]
> Ok interesting, thank you very much, in the future lets make Seren NextUp like Otaku NextUp but only for name parsing and headers. Maybe @Gujal00 or @joezito129 can look into this but it may take some time. 
> 
> 
> 
> Thank you

Awesome, no rush! Take all the time you guys need, I just wanted to report the issue. 😄👍

**Comment by Gujal00** [comment]
I mentioned many times stop comparing Seren with Otaku. Seren uses Trakt for `next up` so the names will always match. Otaku uses Anilist/Mal/Kitsu/Simkl for `next up` and the naming is different. We could tweak the labels a little to improve trakt scrobbling but there will always be a mismatch with seasons for all long anime which trakt breaks into seasons whileAnilist/Mal/Kitsu/Simkl treat them as a single season.

**Comment by Goldenfreddy0703** [comment]
Yeah I just meant tweaking the labels, that's all. Sorry about that and thank you

**Comment by Nuklear92** [comment]
That's what I looking forward to really, tweaking the labels. I understand that Otaku doesn't rely on Trakt. But, when you manually navigate to the title show and season. Episodes label the names exactly as in general all other streaming addons do, including Seren. It's only Otaku's "Next Up" that's labeling the names weirdly and I believe it's what's making the Trakt addon not kick in the scrobbing. As I mentioned in my original comment the Trakt addon **does** work if you browse manually into the show's title and season, because the label names are correct as shown in my screenshots.

So, hopefully tweaking the labels will work, of course **if** it's possible to make that change. 👍

**Comment by Goldenfreddy0703** [comment]
That's cause our next up only has the TV title label, not the episode label which is why your trakt is not scrobbleing unfortunately.

**Comment by Nuklear92** [comment]
> That's cause our next up only has the TV title label, not the episode label which is why your trakt is not scrobbleing unfortunately. 

Oh, I see! So, do you think you guys could make that label name tweak without nothing breaking from the Next Up overall? 🤔

**Comment by Goldenfreddy0703** [comment]
I'm not too sure, that's up to either @Gujal00 or @joezito129

**Comment by Nuklear92** [comment]
> I'm not too sure, that's up to either @Gujal00 or @joezito129 

I see, well in case you guys think that will bring any issues or break other stuff just close the issue without notice. I can just continue doing the tracking manually in the Trakt app. I opened the issue thinking the solution was a bit simpler, hehe. 😅

**Comment by Gujal00** [comment]
Yep, unfortunately when we pull up the current watchlist from anilist we only have the anime name, episodes watched, and when then next episode is being aired. So can't realistically get the episode title at that point
