### ISSUE TITLE
Arctic fuse next episode popup style

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#213]
With the latest updates I noticed the next-up notification has changed in Arctic Fuse. It used to look like this
![Screen Shot 2024-02-07 at 12 35 22 PM](https://github.com/Goldenfreddy0703/Otaku/assets/43726430/21391ca3-4136-4efc-a6a1-78d4fffb2274)
but now looks like this
![Screen Shot 2024-02-07 at 12 03 50 PM](https://github.com/Goldenfreddy0703/Otaku/assets/43726430/d197d193-04f5-438f-9c76-5b09fed058f7)
I can't remember if you guys had a setting to choose the skin style or not like Umbrella does.

**Comment by Goldenfreddy0703** [comment]
Hey so we do have a setting for it. Just change it to the skin you are using and you should be good.

![Screenshot_20240210_123319_Kodi.jpg](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/0ff269af-7a6a-4903-b5dc-268ab8dbcce5)

**Comment by Liquidrag** [comment]
Ok, that's how has been set, wonder why it changed to this new look with the update.

**Comment by icarok99** [comment]
> Ok, that's how has been set, wonder why it changed to this new look with the update.

It didn't change, it was the button mapping that changed

**Comment by Liquidrag** [comment]
> It wasn't him who changed, it was the button mapping that changed

thank you, I hope its an easy fix.

**Comment by icarok99** [comment]
> > It wasn't him who changed, it was the button mapping that changed
> 
> thank you, I hope its an easy fix.

https://github.com/jurialmunkey/skin.arctic.fuse/commit/69cf5501d574302b256a601e4395d88a2d5f8029

**Comment by Goldenfreddy0703** [comment]
> > > It wasn't him who changed, it was the button mapping that changed
> > 
> > thank you, I hope its an easy fix.
> 
> https://github.com/jurialmunkey/skin.arctic.fuse/commit/69cf5501d574302b256a601e4395d88a2d5f8029

Wait a sec, is something actually wrong with the play next dialog? I see that Jurialmunkey changed playnext in his commit.

**Comment by icarok99** [comment]
> > > > It wasn't him who changed, it was the button mapping that changed
> > > 
> > > 
> > > thank you, I hope its an easy fix.
> > 
> > 
> > [jurialmunkey/skin.arctic.fuse@69cf550](https://github.com/jurialmunkey/skin.arctic.fuse/commit/69cf5501d574302b256a601e4395d88a2d5f8029)
> 
> Wait a sec, is something actually wrong with the play next dialog? I see that Jurialmunkey changed playnext in his commit.

The play and pause buttons are not appearing.

**Comment by Goldenfreddy0703** [comment]
> The play and X buttons are not appearing.

are they by anychance appearing on my play next? If not im going to have to update up next on Otaku and Up Next Skin for Seren

**Comment by icarok99** [comment]
![IMG_20240210_210550](https://github.com/Goldenfreddy0703/Otaku/assets/46580318/a899d1d4-74c8-4dbc-b70d-144a9f0298c3)

**Comment by Goldenfreddy0703** [comment]
u kidding, dang it, now im going to have to fix it

**Comment by Goldenfreddy0703** [comment]
Ok new release should be online and this should be fixed it now so we should be good. Thanks to everyone who informed me about this issue.

**Comment by Liquidrag** [comment]
Thanks!
