### ISSUE TITLE
[Feature Request] Add toggle for disabling message "can't connect api myanimelist"

### ISSUE THREAD

**Issue by DaisyF8** [Goldenfreddy0703/Otaku#216]
Sometimes Myanimelist-site will go offline for a while and come back. 

But I forget that this can be the cause, do re-auth and then curse "It's the site that's offline" harrrr!

**Comment by Goldenfreddy0703** [comment]
Interesting, i mean we could possibly add a setting in the Mal watchlist settings that disables notifications but i don't think it would really be necessary cause if you had a setting to have the notification disabled, how would the user know if there anime is being tracked or not, wouldn't really make any sense.

**Comment by DaisyF8** [comment]
It's not the notifications themselves I would want to stop.  It's purely the message "I can't connect to the MAL api" that is beside the point for me.

If that is the message, there are two possibilities : either MAL is offline, or my authorization isn't working. Since I can't make the distinction between the two I'd rather not see the "can't connect"-message.  Seeing the message triggers me to retry the authentication. And when I do that while MAL is offline (most of the time this is the cause of the error), I can't do anything anyway.

A "Don't show connection errors" toggle in MAL-settings would solve this.

But that's just me, no worries. I justed wanted to let you know.

**Comment by Goldenfreddy0703** [comment]
Ok I thought about it and you do have some points so going to add it soon, maybe tonight. 

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey @DaisyF8 , added the setting so should release in a few min, im gonna go ahead and close this but please test and if you have any issues about this feature, feel free to reply in here and we will look into this further.

Thank you

**Comment by DaisyF8** [comment]
Thanks so much for adding the feature. I'll let you know if I have news.
