### ISSUE TITLE
hmm only single source sometimes are available and its an ads 1min ads of hololive.

### ISSUE THREAD

**Issue by TomieAi** [Goldenfreddy0703/Otaku#219]
heres example only 1 source and its from animix a 1min ads about hololive why? then it will go to next episode. :(
this happen no matter how much rescrap i do. 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/f09a0977-faa3-4d6c-a9ca-19e3ce30dbee)

**Comment by TomieAi** [comment]
I wonder if its the special character that triggers it..  I found another example anime that triggers it like "Onegai☆Teacher" but it in english it became "Please☆ Sensei" which is not gonna show anything on gogoanime .. unless u remove the star.   but again ep1 works the other ep next to it doesnt xD maybe thats not it.. 

actually no idea.. its just sad that this holo live ads keep popping up xD theres other anime that i have to manually watch at gogoanime website xD and mark manually my anilist sad.

**Comment by Goldenfreddy0703** [comment]
That's very very weird where at the point I don't understand why you would be getting ads from animix. @Gujal00 you wanna look into this, I have never seen an issue where a user is getting ads on one of our embeds which is very odd and interesting.

**Comment by TomieAi** [comment]
> That's very very weird where at the point I don't understand why you would be getting ads from animix. @Gujal00 you wanna look into this, I have never seen an issue where a user is getting ads on one of our embeds which is very odd and interesting.

ikr xD and the worst thing is.. it goes to next episode instead of loading the current episode after an ads..  u endup cant watch any episode only holo live xD 

heres the demo of the bug

https://github.com/Goldenfreddy0703/Otaku/assets/111332073/d98a4271-f7e1-462a-9cb0-d337c62e6467

**Comment by TomieAi** [comment]
i think animix is tripping balls @Goldenfreddy0703 ..  

another example showing ep1 works then if the bug occurs on other ep which only gonna show animix or nothing at all.. animix sometimes just xD changing the anime.. it became one piece.. from **nande koko ni sensei** ga to **one piece.**

https://github.com/Goldenfreddy0703/Otaku/assets/111332073/2147467d-2d35-4b24-90da-c0a59f7b51ff

**Comment by Goldenfreddy0703** [comment]
Ok that's just very weird, idk what just happened but you may wanna try aniwatch or aniwave instead sense they work 100% of time. Animix is a weird embed cause of the shutdown they had so we're are using alternate sites and all.

**Comment by TomieAi** [comment]
> Ok that's just very weird, idk what just happened but you may wanna try aniwatch or aniwave instead sense they work 100% of time. Animix is a weird embed cause of the shutdown they had so we're are using alternate sites and all.

yeah but its not like i want animix xD im stuck on only that is the only option.. actually i have every embed checked. i dont know why only animix is the listed source :(

**Comment by Gujal00** [comment]
Works fine with gogo, animepahe, aniwave and aniwatch enabled. 20 sources found
![screenshot00000](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/32d43682-67f7-44b1-b9dd-1fb767655e44)

**Comment by TomieAi** [comment]
> Works fine with gogo, animepahe, aniwave and aniwatch enabled. 20 sources found ![screenshot00000](https://private-user-images.githubusercontent.com/17394059/305742472-32d43682-67f7-44b1-b9dd-1fb767655e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyODYxOTAsIm5iZiI6MTcwODI4NTg5MCwicGF0aCI6Ii8xNzM5NDA1OS8zMDU3NDI0NzItMzJkNDM2ODItNjdmNy00NGIxLWI5ZGQtMWZiNzY3NjU1ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE5NTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDhiMWFlMDQwOGYxODUyNDZmNjI4NzU3NDU3MGVlNDBhYjE3ZDExNGZjZjk0ZGQ3ZWYwMTdjYzhmZDQxZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fYD_DV_TzqQlZJOMA4numjpQGuJZC8XUAo5786I3-ug)

yeah ep1 on that anime works on me too..

**Comment by TomieAi** [comment]
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/ce22f4a4-e547-416a-b952-988b0489a5d2)

i think u selected the 1st one.. i selected this one.. secret couple one xD it has same episode name

**Comment by Gujal00** [comment]
What search term are you using, I cant seem to find it in search results
![screenshot00001](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/4685934b-3759-4f89-aec0-685821c4db0a)

**Comment by Gujal00** [comment]
What search term are you using, i am not able to get that show
![screenshot00000](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/655d91eb-5028-4ece-a818-29bf1706b078)

**Comment by TomieAi** [comment]
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/3ac57ee9-060f-4972-8336-2a9a442d7eea)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/70bc8160-1ccd-4ea1-98ac-3d9bd47b7f1d)

actually i dint search this anime at 1st.. i dint know theres alot of variant with same name and same ep name too xD

this anime is just randomly at the multi select tag searching result xD

**Comment by Gujal00** [comment]
animix is not good when searching similarly named anime, it could pickup unrelated streams. That needs to be improved

**Comment by TomieAi** [comment]
> animix is not good when searching similarly named anime, it could pickup unrelated streams. That needs to be improved
> 
> Anyway, `Please Teacher!: Secret Couple` is the alternative name of `Onegai Teacher OVA` so the search is listing correctly

![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/888b1d91-736f-45b6-abdf-c38db580ce84)

yeah theres some stuff weird when its a same name

like this one.. one should have 12 ep.. and one is just 1 ep. 
but both of them has 12.. but one has 12 + 1.. i think something got confused.. because the other one should be "Nande Koko ni Sensei ga!? Special" it only has 1ep which is unaired part 13th ep. of the original series.

**Comment by Goldenfreddy0703** [comment]
Hey so about those search results and all. Those search results come from Anilist and when it comes to Anilist, its weird tbh. Specials, ova, ona, ect are very weird when it comes to anilist cause there not going off by mal, anidb, or simkl which i find weird. That could probably be the reasons why its a bit buggy.

**Comment by Goldenfreddy0703** [comment]
Hey so about these 1 min ads, there is really nothing we can do at this point unless there was another animix clone out there using the same animix servers. If you guys know any animix clones out there using the same servers feel free to add to this. Im going to go ahead and close this but in my next release, we will add a warning next to the embed saying 1 min ads or something.

Anyway im going to close this but if you guys have any questions or any solutions, feel free to reply and we can open this back up and all. 

Thank you
