### ISSUE TITLE
Anilist Authorization Error

### ISSUE THREAD

**Issue by CNDVidel** [Goldenfreddy0703/Otaku#220]
Hello. I keep getting the "Incorrect username and password" error message when trying to authorize Anilist. I'm on an Nvidia Shield running Android TV 11, Shield TV SW v. 9.1.1, and Kodi v. 20.4.

**Comment by Goldenfreddy0703** [comment]
Mmm it's possible you typed your username incorrectly, mind showing me your anilist profile

**Comment by CNDVidel** [comment]
I quadruple-checked my login info and it was correct every time. I was able to authorize my MAL account with no issue. I saw that someone posted here about the same issue some years back, and an update or something was released to fix it? 

Here is the link to my Anilist profile:

https://anilist.co/user/CNDVidel/

Is this what you needed? Thanks!

**Comment by Goldenfreddy0703** [comment]
Ok one possibility I can think of is that you abilist profile maybe set to provide, see if you can set your anilist profile to public and see if your able to authorize this time. If not then something maybe wrong with your connection to anilist on the shield so if you have not restarted your shield or device, that could be the issue but not too sure.

**Comment by Goldenfreddy0703** [comment]
Hey so about Anilist, i think it could have something todo with your connection so do either of these solutions to help.

1. Reinstall Otaku and Make sure all related data is removed and then try reauthorizing Anilist again. 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/e5a57af8-bcab-48a0-bf23-4908ccf786a3)

2. Restart you whole Nvidia Shield by unplugging for 10 seconds and plugging it back in. 

3. Restart your wifi router by unplugging for 10 seconds and plugging it back in. 

4. Sense your using an Nvidia Shield, There is a possible chance IPV6 is Affecting it so you may wanna disable IPV6.

5. Reinstall Kodi if non of those solutions help. 

Hopefully one of these solutions will solve your issue.

**Comment by CNDVidel** [comment]
Yeah...

None of these suggestions worked. Still getting the same error message. 

Don't worry about it, though. I'll just use myanimelist since that's the only one that will let me authorize with no issue.
 
Thanks anyway.
