### ISSUE TITLE
last 4 episodes of jujutsu kaisen not playing

### ISSUE THREAD

**Issue by mxrislyna** [Goldenfreddy0703/Otaku#221]
hello, i will attach a photo.
![image](https://github.com/Goldenfreddy0703/Otaku/assets/160684475/a92fc81a-9a8a-4147-b8c5-99318d7d3e7d)

**Comment by icarok99** [comment]
> Olá, vou anexar uma foto. ![imagem](https://private-user-images.githubusercontent.com/160684475/306457271-a92fc81a-9a8a-4147-b8c5-99318d7d3e7d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzgwNzEsIm5iZiI6MTcwODQ3Nzc3MSwicGF0aCI6Ii8xNjA2ODQ0NzUvMzA2NDU3MjcxLWE5MmZjODFhLTlhOGEtNDE0Ny1iOGM1LTk5MzE4ZDdkM2U3ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwMTA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDU2Zjk5NzkyNDE1MTg2MzdjMzhmNzdhMjQ2NmU3NTZmN2I0Mjk2MTNjMmFmZGU2NDNjYjI2ZWY3NmM2OTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l_c8ul4CappnEWjkZaxjGOjD-cSiYGjp7TZkLT7G7ag)

@mxrislyna Play from season 2 because these last 4 episodes are part of the second season.

**Comment by icarok99** [comment]
There is no way to reproduce something that is not part of the season.

**Comment by mxrislyna** [comment]
ohhhh how did i not know that🥲 thank you

**Comment by icarok99** [comment]
> ohhhh how did i not know that🥲 thank you

Topic resolved may close post.
