### ISSUE TITLE
[feature requests] Can the watchlist be tracked using trakt?

### ISSUE THREAD

**Issue by giventofly** [Goldenfreddy0703/Otaku#223]
I usually use https://trakt.tv so I have everything in one place (series/anime/movies) can the trakt watchlist be used to see the missing episodes?

(there are some trakt addons already in place: https://kodi.wiki/view/Add-on:Trakt the official from kodi) if a starting point/boilerplate is needed

best regards

**Comment by Goldenfreddy0703** [comment]
Unfortunately no cause Trakts Database is way different then any other watchlist and Trakt does not support anime databases like anilist, mal, kitsu, ect. Simkl surprisingly supports Trakt and other Anime databases which is way better then Trakt. 

If there is a project such as mal sync that supports mapping trakt stuff, maybe I will consider adding trakt support but I don't see that happening anytime soon.

**Comment by giventofly** [comment]
so you will just need an api endpoint that maps anidb <-> trakt ?

**Comment by Goldenfreddy0703** [comment]
> so you will just need an api endpoint that maps anidb <-> trakt ?

Well yes and no, anidb's database is anime with separate seasons, parts, specials and trakt would probably not be able to get all that which would most likely be an incomplete watchlist. Trakt database is basically all seasons in one series. Parts and specials may not be included but again not too sure. 

We found a way to convert anidb to tvdb and it's season and parts but sense trakt is going away from tvdb, it kinda makes it impossible to get tvdb mappings from trakt sense they moved away from tvdb.

**Comment by giventofly** [comment]
by tvdb you meant tmdb?
