### ISSUE TITLE
Global watched indicators

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#226]
Hi again! I was wondering if it is possible for global watched indicators. It works inside anilist and anilist but if I do a global search, the indicators are not there. This would be extremely useful when searching for  shows/seasons like Attack on Titan where it will indicate what I've already watched when I search it. As is there are no indicators when searching.

Here is a screenshot of indicators inside anilist
<img width="1238" alt="Screen Shot 2024-03-02 at 9 30 14 AM" src="https://github.com/Goldenfreddy0703/Otaku/assets/43726430/4c5a3086-c5af-4042-b374-0f19b0b20e83">

Here is a screenshot of a global search and it shows no indicators. Makes it difficult to sort out what is needed to watch next.
<img width="1242" alt="Screen Shot 2024-03-02 at 9 30 47 AM" src="https://github.com/Goldenfreddy0703/Otaku/assets/43726430/5c7e187a-fcf1-471f-bc23-f8a0da92305a">

**Comment by Goldenfreddy0703** [comment]
Funny story, me and @joezito129 are actually going to be working on that very soon but we are only going to have completed indicators so no ongoing indicators, just completed so that it can still run very fast.

**Comment by Liquidrag** [comment]
Completed is better than none! Definitely useful because I have a crap memory and can't remember all the shows I watched 20 years ago.

**Comment by Goldenfreddy0703** [comment]
Sameeeeeeee!!!!!!! I hate going on my phone looking up that anime if I already watched it or not and I also don't want to keep backing out and finding it in my watchlist. 

I hope to get this worked on very very soon hopefully.

**Comment by Goldenfreddy0703** [comment]
Heyyyy so great news, one of our contributors @joezito129 has made this possible and it works great. It is completed but there is one small thing we need todo and thats just making an option where if a user completed the last episode of an anime, it will do a watchlist sync but after that its done, we will make a release on it soon.

**Comment by Liquidrag** [comment]
Awesome news! Thank you @joezito129!
