### ISSUE TITLE
old aniwatch domain

### ISSUE THREAD

**Issue by NastyDream** [Goldenfreddy0703/Otaku#227]
hey there,
aniwatch got a new domain and it cant find any streams right now.

old "aniwatch.to"
new "aniwatchtv.to"
![Bild_2024-03-03_192057268](https://github.com/Goldenfreddy0703/Otaku/assets/162049587/2719f5d3-acfb-4bd8-9ec7-65e5542cd636)

After the change it works again :)

**Comment by Goldenfreddy0703** [comment]
Hey thanks for pointing this out, will make a quick release to fix this. Thank you.
