### ISSUE TITLE
[Feature Request] Filtering scraped results for auto-play

### ISSUE THREAD

**Issue by JonLuepf** [Goldenfreddy0703/Otaku#228]
Sometimes I am watching a series that has no batch torrent because the season is not completed but I want to watch a specific release for the anime for example by the group SubsPlease. There is no way to change what episode is being auto played so the only option I have is to source select the correct torrent for every episode manually.
I thought it would be a good feature to set a filter for auto play either by anime or globally that could then filter the scraped results. For example if I filter by “SubsPlease” I would only get their releases.

**Comment by Goldenfreddy0703** [comment]
Now i kinda see what you mean and i think it would be a good feature but unfortunately you would have to have the file names identical to each other or maybe have a way to exclude the season or part numbers and all which would take time, and also, im not too sure on how to do that. 

Luckily as a workaround, we do have embeds such and Aniwatch or Aniwave so when you select an embed and watchlist and episode to the end, it will play the same embed for the next episode automatically, hopefully that workaround helps a ton.

Im gonna go ahead and close this but i will keep this in mind if i work on torrent sources again and all. 
Thank you.

**Comment by Goldenfreddy0703** [comment]
Huge thanks to @jonathanluepfert for making a pr on this, i would have had a hard time figuring this out.
