### ISSUE TITLE
Crashing after selecting

### ISSUE THREAD

**Issue by Livest1** [Goldenfreddy0703/Otaku#229]
Whenever i try to load an episode it shows the sources, goes back to the episode selection screen, indicates that it's playing in the upper right corner then crashes 😵‍💫

**Comment by Goldenfreddy0703** [comment]
An embed server must be crashing on your side, go to Otaku setting and go to the embeds catagory and make sure to disable VidStream or HD-1, Also maybe VidPlay

**Comment by Goldenfreddy0703** [comment]
Hey there, its been a few days, Any Updates so far on this @Livest1?

**Comment by Livest1** [comment]
Sorry for the late response, but yeah, what you suggested to do worked! Thanks for the assist, man. I really appreciated it!

**Comment by Goldenfreddy0703** [comment]
Oh no, it's ok, thank you!!!!!

**Comment by umop3plsdn** [comment]
i have this same issue the only one in the list of three that i had is VidPlay i removed it and im still getting the same problem
