### ISSUE TITLE
Otaku 0.2.15, not scrapping link

### ISSUE THREAD

**Issue by DylanEhv** [Goldenfreddy0703/Otaku#23]
Version of kodi: 19.4
Version of Otaku 0.2.15
Android tv version 9

When i try any anime there isn’t any scrapping links loaded, i don’t have any extra addons like Real Debrid.

log shown below:
Https://paste.kodi.tv/ukequsujiw

**Comment by Goldenfreddy0703** [comment]
Ok well sense you don't have any extra addons like real debrid could you only see embeds?

**Comment by DylanEhv** [comment]
When I tried to load for example Naruto, it went to the scrapping loading screen and everyone of them had a 0 behind it. Then after a while it just went back to the anime episodes

**Comment by Goldenfreddy0703** [comment]
Heybso that's odd. Mine is working just fine, oh did you follow the troubleshooting steps as well and your not by anychance a Verizon user are you?

**Comment by DylanEhv** [comment]
Hmm yeah i did do the troubleshooting steps but that didn’t work, It is really weird that it isn’t working are you using a Real-Debrid account or not? I really liked how this addon showed everything so i was pretty bumped when it didn’t work. May i ask what a verizon user is?

**Comment by Goldenfreddy0703** [comment]
Oh Verizon is just a bad cellphone carrier and I was using a debrid account and it worked fine then I disabled my debris account and it still worked fine with the embeds, I'm not sure why yours is having problems.have you tried restarting your kodi maybe?

**Comment by DylanEhv** [comment]
Okay so i have checked with my little brother and his does work on some for example Blue Lock did work for him but aoashi didn’t work for him there were no embeds available

**Comment by Goldenfreddy0703** [comment]
Oh well yeah, some embeds don't work with anime and most anime does. It's either a hit or miss on some animes, in the future, we will improve the embedding a little and see if that fixes your issue. If you have real debrid, that would help you a ton.

**Comment by DylanEhv** [comment]
Yeah hahah i have heard from multiple people, and i am still figuring out a easy way to buy a real debrid account without using a credit card

**Comment by Goldenfreddy0703** [comment]
You could always use amazon pay, its really simple and for real debrid, i either use a debit card or use amazon pay.

**Comment by DylanEhv** [comment]
Hmm that's weird i tried to use amazon pay but when i added my card it didn’t let me pay

**Comment by DylanEhv** [comment]
Do u know actually what the highest quality is what you can watch with Real Debrid?

**Comment by Goldenfreddy0703** [comment]
Any quality really, most animes have a max quality to 1080p and some animes that are movies are like 4k.

**Comment by DylanEhv** [comment]
Hmm okay yeah maybe that’s the 10 euro worth than, I’m gonna think about it.

**Comment by Goldenfreddy0703** [comment]
Real Debrid is worth it, You can pay 16 euro every 6 months. That's a way better price then paying for those crappy streaming services out there that make you pay 15 euros monthly, your basically getting a better deal then any other streaming service.

**Comment by DylanEhv** [comment]
Fair, for what addons do you use real debrid?

**Comment by Goldenfreddy0703** [comment]
Seren, Otaku, TMDB Helper. Thats about it but there are 3rd party addons like Ezra, Umbrella, Fen, Etc

**Comment by Goldenfreddy0703** [comment]
Hey so im going to go ahead and close this sense this issue is kinda resolved i guess but let me know if you would like this issue to be open.
