### ISSUE TITLE
Add a way to set default view like elementum does

### ISSUE THREAD

**Issue by TomieAi** [Goldenfreddy0703/Otaku#232]
please make it possible to select defautl view

i really love this to be my default view

![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/2485f7a6-0f0f-4f0d-8404-a6ece5e5fd5d)

**Comment by Goldenfreddy0703** [comment]
You know funny story, I definitely would and we have some settings for that but they are not implemented unfortunately. I have always wanted to have a way to set view types in Otaku but I don't know how to code that nor what Setting viewtypes there are. In multiple skins, there are so many and I'm not sure how to go about that. 

Hopefully will get added soon or if somebody could give me a pr for that, that would be amazing. Again hopefully will be added soon, it's on my list.

**Comment by icarok99** [comment]
> please make it possible to select defautl view
> 
> i really love this to be my default view
> 
> ![image](https://private-user-images.githubusercontent.com/111332073/313521692-2485f7a6-0f0f-4f0d-8404-a6ece5e5fd5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTAyNzQsIm5iZiI6MTcxMDc4OTk3NCwicGF0aCI6Ii8xMTEzMzIwNzMvMzEzNTIxNjkyLTI0ODVmN2E2LTBmMGYtNGYwZC04NDA0LWE2ZWNlNWU1ZmQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxOTI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWFhMGRkOWE3ZjE3ZjcwNzQzODgyNDFlODM0ZWQ3Y2YwZTJkMzA2ZWQyMjA4NmFiMTcwODYwM2JhNGZkNjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6S-EoncshuY9nHw2BpQjgRzLJTX1-iJ7YUNA72fRSj8)

The arctic fuse skin allows you to do this

**Comment by Goldenfreddy0703** [comment]
Ayyyyyy great news @TomieAi , we have finally added Viewtypes to Otaku and turns out it was way easier then i thought.
Huge thanks to @joezito129 for helping me add this. 

Our 99th release should be out so if you have any questions or concerns or issues with it, please feel free to reply and we will look further into it. 

Thank you

**Comment by TomieAi** [comment]
> Ayyyyyy great news @TomieAi , we have finally added Viewtypes to Otaku and turns out it was way easier then i thought. Huge thanks to @joezito129 for helping me add this.
> 
> Our 99th release should be out so if you have any questions or concerns or issues with it, please feel free to reply and we will look further into it.
> 
> Thank you

lets goooo <3

**Comment by Goldenfreddy0703** [comment]
Unfortunately I don't think so cause we are mostly an anime addon, not really a Manga addon.
