### ISSUE TITLE
Download RD Source

### ISSUE THREAD

**Issue by TwilightMercy** [Goldenfreddy0703/Otaku#233]
Hi,

is it possible to download the video file in Otaku?
Example from Fen:

![image](https://github.com/Goldenfreddy0703/Otaku/assets/29895680/ab1486d1-681c-481c-9562-ff5da2fe9ef8)

**Comment by Goldenfreddy0703** [comment]
Not at the moment unfortunately, but we will be adding it with this issue sometime soon. It will take tike time tho so we are unsure on when we could add something like this.

https://github.com/Goldenfreddy0703/Otaku/issues/160

**Comment by Goldenfreddy0703** [comment]
Hey so good news, our contributor @joezito129 has some code for downloading sources. I manage to add his code into our addon and i managed to get it working. This is still kinda experimental but it works super well with individual episodes. 

There are a couple of drawbacks but in the future, we plan to work on the download function more.
- Unable to download Batch Torrents.
- Unable to download Episode Groups.
- Will not work for movies yet.

About releasing, i just need help with getting this code to work without requests module and we should hopefully be good to release after we get the download function fully finished.

**Comment by Goldenfreddy0703** [comment]
Hey so great news, i manage to get the code to work without requests so we released and it should be online as we speak, hope this helps, if you have any trouble with this experimental download feature, please tell me and we will look into it. 

To download, you just need to right click on an episode and it should pull up a context menu and you click download. 
Anyway hope this feature helps, im going to go ahead and close this but we plan to improve on it in the feature.
Thank you

**Comment by TwilightMercy** [comment]
Thanks!

What is the reason for not using requests module?

**Comment by Goldenfreddy0703** [comment]
Ok it's not really a good reason but slowness, that's why @Gujal00 made his own in client.py and it works really well.

**Comment by TwilightMercy** [comment]
Yes, it works great!
