### ISSUE TITLE
[Request] Add IMDb ID info tag

### ISSUE THREAD

**Issue by TwilightMercy** [Goldenfreddy0703/Otaku#234]
Hi,

I was wondering if you can add IMDb ID as info tags so these 2 parameters will get values:
When not playing video - `ListItem.IMDBNumber`
When playing - `VideoPlayer.IMDBNumber`

https://kodi.wiki/view/InfoLabels

As an example for these params set, you can look at Fen addon code in:
```plugin.video.fen\resources\lib\modules\player.py```

This will help subtitles addons to find subtitles easier from Otaku's sources (with IMDb ID)
Thank you very much!

**Comment by Goldenfreddy0703** [comment]
Hey so yeah, we do have some imdb id's in our database but it's not alot. We could try to add them but may not be as useful sense most animes you see don't have imdb id's unfortunately.

**Comment by TwilightMercy** [comment]
I would love to have it anyway 🙏🏻👌🏻

**Comment by Goldenfreddy0703** [comment]
Ok so good news, i found out a way to get the imdb_id and i made a function for it but only problem is idk where to put it in my code so this will probably take more time then i thought.

**Comment by Goldenfreddy0703** [comment]
Wait.....did I not put it in the right place, I thought I did

**Comment by TwilightMercy** [comment]
Are you able to send me zip file of the addon with the changes, so I can test it? (if IMDB ID is set in video playback / menu listing)

**Comment by TwilightMercy** [comment]
I've tested this branch's version, and unfortunately, I still don't see IMDb ID proprty value from:
`ListItem.IMDBNumber `or `VideoPlayer.IMDBNumber`

**Comment by Goldenfreddy0703** [comment]
exactly which is why i need a place for that new function i added in the simkl.py file to help recognize that function correctly.

**Comment by TwilightMercy** [comment]
What so you mean recognize?
The function doesn't run when video tags are set?

**Comment by Goldenfreddy0703** [comment]
I'm not too sure tbh, me and @Gujal00 looked into this yesterday and we had trouble with it so we are going to look into this further tonight. The function does run but for some odd reason the videotag is not being recognized and its odd.

**Comment by TwilightMercy** [comment]
Very weird.. the "setIMDBNumber" should work, just like other tags are working (title/year/season/episode that I do see)

**Comment by Goldenfreddy0703** [comment]
Yeah but it's possible functions in wrong place, who knows, will get it figured out tonight

**Comment by TwilightMercy** [comment]
Hopefully good news? 😀

**Comment by Goldenfreddy0703** [comment]
Hey so good news, we manage to get the a4k subtitles to recognize the imdb id, we will release very soon so hopefully we should have this request completed. Only thing we just need to do at the moment is just fix the tmdb helper player sense we made alot of file changes to it and all.

**Comment by Goldenfreddy0703** [comment]
Heyyy so release should be out so hopefully it works very well for you. I'm going to go ahead and close but if you run into trouble with imdb, feel free to reply and we will open this up and look into it. 

Thank you

**Comment by TwilightMercy** [comment]
Hi,

thank you very much for the update, I've tested it and IMDBNumber is set successfully on video playback and I see it's value, both through:
`VideoPlayer.IMDBNumber` and `VideoPlayer.UniqueID(imdb)`

It works perfectly with a4k subtitles and other subtitles addons that are excepting IMDB ID.
My only request if possible (and if not, that's not that important to live with):
is to make the IMDb ID value set also through `ListItem.IMDBNumber` (when not playing video)

The reason is I have subtitle addon that can search subtitles through Kodi's context menu on selected list item, without playing the item. and the other info labels (such as OriginalTitle,year,etc..) are set successfully (except IMDB ID)

Screenshot example:
![image](https://github.com/Goldenfreddy0703/Otaku/assets/29895680/33da9073-75b2-4371-8f60-388bc069e1b9)

**Comment by Goldenfreddy0703** [comment]
I think I can do that in rhe next release so will see. Thx
