### ISSUE TITLE
Spanish source select not found

### ISSUE THREAD

**Issue by OldMartin** [Goldenfreddy0703/Otaku#235]
When i try to use Anime HD Latino for spanish anime the only sources i get its H!Anime and some english embeds, When i try to only use Anime HD kodi crash

**Comment by Goldenfreddy0703** [comment]
Odd, Anime HD must not be working anymore or they changed there site or something, you may wanna stick with H!anime sense they provide spanish anime.

**Comment by OldMartin** [comment]
> Odd, Anime HD must not be working anymore or they changed there site or something, you may wanna stick with H!anime sense they provide spanish anime.
> 
> Will take a look at AnimeHD in a few weeks. Thank you

i guess the only change the embed its now Delta, i see H!Anime have spanish anime but the updates take a while when a anime its on episode 10 the spanish its just in the 1

**Comment by Gujal00** [comment]
Anime HD Latino are now encrypting the search response, so the current code is not working. Have to crack their encryption keys before the site would be operational in Otaku again. Will be another 3 weeks before I would have time to look at this

**Comment by Gujal00** [comment]
> i guess the only change the embed its now Delta, i see H!Anime have spanish anime but the updates take a while when a anime its on episode 10 the spanish its just in the 1

v0.4.92 released with the fix. please test and report back @OldMartin

**Comment by OldMartin** [comment]
Thanks! now its fixed
