### ISSUE TITLE
Otaku Next Episode Issue

### ISSUE THREAD

**Issue by LFC295** [Goldenfreddy0703/Otaku#237]
Every time I try to watch the next episode of a series, it plays the previous episode that I had just watched. It takes multiple attempts each time for it to sort itself out and play the correct episode (this occurs both on autoplay and when I manually select the episode using source select).

Also, I’ve noticed that this happens when I’ve watched something from other addons e.g., I’d watch a series on Seren or Umbrella and then later try to watch something on Otaku, but after I've selected the episode I want, the last thing I previously watched on the other addons would start playing.

Does anyone know of a fix?

**Comment by Goldenfreddy0703** [comment]
Hey sorry i never got back to you but thank you for reporting this. If you don't mind, could you share use a log using the Kodi Logfile Uploader for us?

https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

Also what version and device are you using?

**Comment by guenguer** [comment]
I experienced that too, but it hasn't happened lately.

**Comment by Goldenfreddy0703** [comment]
Hey guys, sorry its been awhile but i wanna look into this more, does this happen on embeds or torrents or both and could someone send me some steps to replicate this issue?

**Comment by guenguer** [comment]
I'm only using torrents.

**Comment by Goldenfreddy0703** [comment]
Alright, good thing its not happening with embeds, again, if anyone could tell me how to replicate this issue that could be great. I think it could have something todo with last_played_source setting or function but i don't understand how playing something on Otaku would play something that was previously watched on Seren or Umbrella which makes no sense to me sense we utilize last_played_source to only filter sources with the same titles to be ontop or our sources list which is very odd. 

> I’d watch a series on Seren or Umbrella and then later try to watch something on Otaku, but after I've selected the episode I want, the last thing I previously watched on the other addons would start playing.

This makes no sense so if you can replicate and tell me the steps on the issue @LFC295 , that would be great.
Thank you

**Comment by guenguer** [comment]
For me it just played anime episodes of other animes I watched shortly before. I never experienced something played from another addons, that would be indeed pretty weird.

**Comment by Gujal00** [comment]
Disable Cloud scaraping and see if the issue still persists

**Comment by theasguard** [comment]
this has happened to me before, or something similar id be watching a series then switch to another series and watch an episode of that then on the next up itd display the previous series and scrape that series again. hasn't happened in awhile though, if it does ill log it.

**Comment by Goldenfreddy0703** [comment]
Hey so its been long enough so im gonna go ahead and close this issue, if this still happens, feel free to reply and let me know so we can open this back up and test. 

Thank you.
