### ISSUE TITLE
Torrent file removal after download

### ISSUE THREAD

**Issue by deadsmond** [Goldenfreddy0703/Otaku#240]
Hello,

I can't find this information in docs - does Otaku remove torrent manifest after downloading files, so they would not become part of torrent network?

By default these files remain and incorporate user as torrent source which is illegal in EU, thus I have to make sure Otaku won't do that

Thank You in advance!

**Comment by Goldenfreddy0703** [comment]
Hey there, I'm actually not sure what you mean. The download function was just to download files from cached sources from the debrid like what fen or seren had. Sense I'm unsure about your question, I'm sure @Gujal00 has the answer to that. Thank you

**Comment by deadsmond** [comment]
Wonderful, thanks!
