### ISSUE TITLE
why xD the background has to be nsfw.

### ISSUE THREAD

**Issue by TomieAi** [Goldenfreddy0703/Otaku#241]
is it possible to have sfw background while waiting for scrapping? xD bruh those fan arts are insane.. those are hentai. how you guys even pull that off xD where u guys get those images. XD my parents look at me in disgust xD i have to explain my self those image are not in the anime those are just fan art.

**Comment by Goldenfreddy0703** [comment]
.......if you don't mind, would you mind showing me a few examples. We can't really control fanart when it's nsfw unfortunately unless we could use fanart from tmdb or tvdb or trakt maybe sense we have a full database for it. 

Btw sense you mentioned scrapping screen, as a temporary workaround, go into Otaku settings and go to General catagory and find the option that says "Disable Fanart During Scrapping" hopefully that will help as a temporary workaround for now.

**Comment by Gujal00** [comment]
Anime and risque fanart go together. It is how it is and if you do not like it, use the `Disable Fanart during Scraping` option.
