### ISSUE TITLE
Replace Anilist posters with MAL posters?

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#242]
Not a bug just a question. What is the benefit of turning this on? Do I also need to log into MAL?
Than you guys for this addon and all the support!

**Comment by Nuklear92** [comment]
> Not a bug just a question. What is the benefit of turning this on? Do I also need to log into MAL?
> 
> Than you guys for this addon and all the support!

This ONLY works when navigating Otaku's menus, NOT if you're navigating for example your AniList account if you're signed in and you navigate to "Next Up", "Current", etc. all those menus will still have the same AniList posters which are basically just plain photos not real Artworks. 

I also thought this feature at first was going to work for those menus inside of your AniList account, but then discovered the is only when navigating titles in normal Otaku menus like "Popular", "Trending", etc.

**Comment by Liquidrag** [comment]
@Nuklear92 Thank you, I mainly use my "Current" inside anilist so that's why I don't see a change. I'll just keep it enabled.

**Comment by Goldenfreddy0703** [comment]
Yeah I thought it wouldn't make as much sense if i added mal posters inside the watchliat menus and also If I were to add them, it would probably take me time to figure out simkl and kitsu and in where there poster locations are and then trying to code it in. I mean it wouldn't be such a bad idea but idk if I should tho.

**Comment by Liquidrag** [comment]
Personally I prefer consistency but it’s up to you if you think it’s worth it to change it. I thank you guys for the effort!
