### ISSUE TITLE
MAL Watchlist error playing video and "Mark watched Watchlist" via context

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#243]
i switched back to MAL watchlist this morning and i get this error on playback near the end of 
"is it wrong to pick up girls in a dungeon? II" and season 3 also.
the error doesn't occur on season 1, this is the only series I've looked at  so far.
the error also occurs when i try to mark any episodes in season 2 or 3 "marked as watched Watchlist".
ill use anilist in meantime 

Error Type: <class 'KeyError'>
Error Contents: 'my_list_status'

Traceback (most recent call last):
 File "plugin.video.otaku\default.py", line 21, in <module>
   main.Main()
 File "plugin.video.otaku\resources\lib\main.py", line 2531, in Main
   router_process(control.get_plugin_url(), control.get_plugin_params())
 File "plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
   return route_obj.func(payload, params)
 File "plugin.video.otaku\resources\lib\main.py", line 2302, in PLAY
   player.play_source(link, anilist_id, watchlist_update_episode, _BROWSER.get_episodeList, int(episode),
 File "plugin.video.otaku\resources\lib\ui\player.py", line 528, in play_source
   watchlistPlayer().handle_player(anilist_id, watchlist_update, build_playlist, episode, filter_lang, skip)
 File "plugin.video.otaku\resources\lib\ui\player.py", line 107, in handle_player
   self.keepAlive()
 File "plugin.video.otaku\resources\lib\ui\player.py", line 291, in keepAlive
   _ = self.onWatchedPercent()
 File "plugin.video.otaku\resources\lib\ui\player.py", line 142, in onWatchedPercent
   self._watchlist_update(self._anilist_id, self._episode)
 File "plugin.video.otaku\resources\lib\WatchlistIntegration.py", line 198, in watchlist_update_episode
   status = WatchlistFlavor.watchlist_anime_entry_request(anilist_id).get('status', '')
 File "plugin.video.otaku\resources\lib\WatchlistFlavor\__init__.py", line 52, in watchlist_anime_entry_request
   return WatchlistFlavor.get_update_flavor().get_watchlist_anime_entry(anilist_id)
 File "plugin.video.otaku\resources\lib\WatchlistFlavor\MyAnimeList.py", line 282, in get_watchlist_anime_entry
   results = json.loads(r)['my_list_status']
KeyError: 'my_list_status'
-->End of Python script error report<--

**Comment by Goldenfreddy0703** [comment]
Heyyy so usually when watching an episode, it automatically gets marked as watch, Mal Watchlist mostly has the most of the issues so you may want to reauthenticate mal and see if that fixes your issue.

**Comment by theasguard** [comment]
reauthing and cleaning seems to of solved it I think, ill test it out and update if anything happens . thank you

**Comment by theasguard** [comment]
hey my bad this error happened again this morning. it went through season 2 of the said show fine last night, i started it on season 3 and the error popped up around 4 minutes left on episode 1, i did the same cleaning and reauthing again and it just keeps reproducing the same error as before 
File MyAnimeList.py", line 282, in get_watchlist_anime_entry
results = json.loads(r)['my_list_status']
KeyError: 'my_list_status'
ill use one of the other watchlists, MAL doesn't seem to like me binging series haha

**Comment by Goldenfreddy0703** [comment]
Out of curiosity, what show is this again?

**Comment by theasguard** [comment]
Hey it was "is it wrong to pickup girls in a dungeon?" Season 2 and 3 it was happening on, but I'm starting to think it's a MAL issue itself.
I did delete the series from my MAL list and it displayed 1 error after that and the error hasn't reproduced since. 
It did scrape the next episodes I'll add so it was just when it'd update the list I'm assuming.

**Comment by Goldenfreddy0703** [comment]
Mmmm....it could be a mal issue but most likely an anilist, reason why is cause anilist does there own mappings and sometimes animes can usually split of not match up, I will try to look into this tho just incase. Thank you
