### ISSUE TITLE
new watchlistintegration.py breaks all watchlist loads into episodes

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#244]
the log doesn't really much.
Error getting plugin://plugin.video.otaku/watchlist_to_ep/169417/56690//4
CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watchlist_to_ep/169417/56690//4) failed
i uninstalled and reinstalled same issue (everything was wiped before install)
i then replaced the watchlistintegration.py from the previous version, and my lists work again. 

tested on tsukimichi, re:monster, then i just started clicking shows in my watchlists and it was the same thing.
or is this just me? lol 
ive reverted to the previous version at the moment.

**Comment by Goldenfreddy0703** [comment]
Ok now i see what you mean now

**Comment by theasguard** [comment]
I tried in all of them, I started in anilist, current watching mostly and any series, then I changed my settings to simkl same thing, and same with Mal.
To search anything I believe was fine itself but the lists wouldn't load past a series. I readded the new simkl. Py without any issues, so it's not that, it's odd to me as there isn't any actual error to it.

**Comment by Goldenfreddy0703** [comment]
Im actually surprised no one on reddit made a post about this yet, in the next 20min, we will either revert the change or have a quick fix on it.

**Comment by theasguard** [comment]
Yea that's surprising haha most probably haven't updated yet in my opinion or just overlooked it, I like to look over stuff too much, so I usually do delve into testing everything that's related to the updates. 
Thanks for getting back quick, I appreciate you guys.

**Comment by Goldenfreddy0703** [comment]
Hey so release should be out and should fix watchlist so I'm going to go ahead and close this issue. If you have any issues related to this, please feel free to reply and we will open this back up. 

Thank you

**Comment by theasguard** [comment]
this issue is happening again, or is it actually me this time ? lol 
problems loading into episodes from lists again, any list, any section. not sure whats causing it, log doesn't specify any real error again. (my current list is anilist, was working earlier till i updated again) this is kind of odd to be honest.

**Comment by Goldenfreddy0703** [comment]
Odd but interesting, could have been some updates that happened recently but not sure. Glad your fixed it thought.
