### ISSUE TITLE
Not an issue an enhancement maybe?  Alldebrid cloudfile sources

### ISSUE THREAD

**Issue by theasguard** [Goldenfreddy0703/Otaku#245]
I was wondering if any of the Scraper devs planned on adding alldebrid to the debridcloud file. Py?
I see real debrid and premiunize, just not alldebrid, would that cause me to see a lack of results when I cache stuff to alld? or is that just the search not finding the name?
 Example is moonlit fantasy season 2, i cached a bunch of the single episode links including some duel audio and it wasn't finding them as cached torrents? Another show was that chilling in another world with lvl2 super cheats, and mashle magic and muscles season 2 , I cached duel audios for those also and it wasn't finding them? 
Sorry if I'm just being a pain, I'm more just curious haha. 

Edit I'll add I don't have premiunize or real debrid so this is why I was wondering.. 😅

**Comment by Goldenfreddy0703** [comment]
Ok funny story, i came across something today and found out that AllDebrid has a cloud. What im not sure about is if it supports the same cloud functionality as real debrid and premiunize. We could possibly add cloud scrapping for AllDebrid but only if it supports it. Hopefully one of our contributors has AllDebrid and we can add it very soon.

**Comment by theasguard** [comment]
hey that would be awesome, i went over Seren Omega thats in the diggz repo it supports ad cloud i believe, if the code from that can help you guys some how thatd be wicked. 
let me know i figure id mention that in case it helps you guys in some way :)

**Comment by Goldenfreddy0703** [comment]
I never really used Diggs repo but would you mind giving us the link for seren omega?

**Comment by theasguard** [comment]
Hey yea no problem here is a link to the repo for it http://diggz1.me/diggzrepo

**Comment by Goldenfreddy0703** [comment]
Hey so looks like cloud debrid is on the official seren repo so should be able to see if we we can add it to Otaku very soon, thank you

**Comment by Goldenfreddy0703** [comment]
Hey so looks like we were able to add AllDebrid CloudFiles. Huge thanks to @joezito129 for adding AllDebrid CloudFiles. Im going to go ahead and close this but in the future, we will make improvements on this. If you run into any issues related to this, please feel free to message in here and we will look further.

Thank you
