### ISSUE TITLE
Scraping Issues version 0.4.103 [20240428]

### ISSUE THREAD

**Issue by EchoFiend2000** [Goldenfreddy0703/Otaku#247]
On the most recent version 0.4.103 [20240428] I'm having scraping issues with the original Dragon Ball. It seems to be scraping every show with 'DB' in the title (including file names) and also every other version of Dragon Ball (Z, Kai, Super etc.). I have tried the new 'scrape torrents consistently' option and it seems to have the same result. 

I just want to say thank you for working so hard on a project that allows so many people to enjoy these great shows & films, I really appreciate it. Otaku is amazing and it feels wrong to only talk about an issue I'm having rather than how much I love it. 

Thanks again

**Comment by theasguard** [comment]
the latest version fixed a ton of bugs resolving around torrents, but on (Fate/Apocrypha) it returns (Frieren) now, hopefully a fix comes along for these odd bugs, i really appreciate the work put in..

**Comment by Goldenfreddy0703** [comment]
Maybe that 2nd scrapping update was not a good idea just cause of what happened with fate/Apocrypha showing multiple different animes so im going to go ahead and revert the update sense its causing issues. What i did was i utilized all the synonyms of the anime title cause they are like alt titles so that we could get more torrents then usual but turns out some of those synonyms could have probably not matched with the main anime title or was in a different language so im not very sure but going to revert it maybe and see what i could do for it. 

Thank you

**Comment by theasguard** [comment]
The second update definitely helped with series like mashle and Tsukimichi as it actually displayed more of what I was seeing on the site, just certain stuff it didn't agree with. Hopefully you guy can work something out.

**Comment by Goldenfreddy0703** [comment]
> The second update definitely helped with series like mashle and Tsukimichi as it actually displayed more of what I was seeing on the site, just certain stuff it didn't agree with. Hopefully you guy can work something out.

Oh yeah it did help with alot of series but certain series just had weird sources and weird synonyms where they led to different animes, it was weird so going to have to look into it soon or see if i can find a different list of alt titles for animes, if i can than that would be awesome

**Comment by Sickhead01** [comment]
> Maybe that 2nd scrapping update was not a good idea just cause of what happened with fate/Apocrypha showing multiple different animes so im going to go ahead and revert the update sense its causing issues. What i did was i utilized all the synonyms of the anime title cause they are like alt titles so that we could get more torrents then usual but turns out some of those synonyms could have probably not matched with the main anime title or was in a different language so im not very sure but going to revert it maybe and see what i could do for it.
> 
> Thank you

the dragon ball title issue has been a thing since before update, ever since i started using otaku which is probably like a year now

**Comment by Goldenfreddy0703** [comment]
Heyyyy so i know its been but we recently released an update that should hopefully improve scrapping significantly and we also recoded prioritization settings to help with filtering season, parts, episodes, etc

Anyway im going to go ahead and close this but if you guys still happen to have any issues with scrapping, please feel free to reply back in here and we will open this back up and look into it. 
Thank you
