### ISSUE TITLE
Search Paths showing no results

### ISSUE THREAD

**Issue by Rinicko** [Goldenfreddy0703/Otaku#255]
Hello, first off, big thanks for all your hard work with this addon and for consistent updates.

I've been having an issue with the search paths. None of them seem to work... Movies, Tv, and both... none working,  they just show no results. Have they been changed?...the one I use is
 plugin://plugin.video.otaku/search/movie/

**Comment by Goldenfreddy0703** [comment]
Odd do the regular search paths work?

**Comment by Rinicko** [comment]
> Odd do the regular search paths work?

Yeah, the search directly from the addon works... it's the search paths added to the search function of the skin that doesn't work... tried on both Arctic Fuse and Horizon 2

**Comment by Goldenfreddy0703** [comment]
Oh I think I know what happened, one of our recent releases probably had the search path changed due to a small bug with having "/" in the title. Will have that fixed very soon thank you.

**Comment by Rinicko** [comment]
> Oh I think I know what happened, one of our recent releases probably had the search path changed due to a small bug with having "/" in the title. Will have that fixed very soon thank you.

ohh.. that'll be great, thank you 😁

**Comment by Goldenfreddy0703** [comment]
Hey so made a quick release that should hopefully fix the custom search paths. Im going to go ahead and close this but if issues still persist, please feel free to reply and i will get back to you and look into this further. 

Thank you
