### ISSUE TITLE
[BUG] SIMKL Authentication error: An unknown error occurred when adding SIMKL account

### ISSUE THREAD

**Issue by CEV-A** [Goldenfreddy0703/Otaku#257]
**Describe the bug**

On a fresh install of Kodi and Otaku, I get an error when trying to add my SIMKL account. It says "Otaku error: An unknown error occurred". The popup screen with code and URL shows for a split second then disappears.

**To Reproduce**

1. Fresh install Kodi
2. Fresh install Otaku
3. Try to add SIMKL account
4. Error

**Expected behavior**

No error

**Kodi Version**

 - Kodi Version 19.5
 - Otaku Version 0.4.110
 - Nvidia Shield 9.1.1

**Additional context**

- I've tried clearing cache in Otaku, reauthorizing, wiping addon data and fresh install of Kodi, still get the same error
- Log complains of an access_token issue?

**Comment by theasguard** [comment]
could you provide the log? 
i just tested this on Kodi 20 and it worked fine. 
also check your Simkl account and revoke Otaku there should be an option to revoke access, then try reauthing again in Otaku

**Comment by theasguard** [comment]
> **Describe the bug**
> 
> On a fresh install of Kodi and Otaku, I get an error when trying to add my SIMKL account. It says "Otaku error: An unknown error occurred". The popup screen with code and URL shows for a split second then disappears.
> 
> **To Reproduce**
> 
> 1. Fresh install Kodi
> 2. Fresh install Otaku
> 3. Try to add SIMKL account
> 4. Error
> 
> **Expected behavior**
> 
> No error
> 
> **Kodi Version**
> 
> * Kodi Version 19.5
> * Otaku Version 0.4.110
> * Nvidia Shield 9.1.1
> 
> **Additional context**
> 
> * I've tried clearing cache in Otaku, reauthorizing, wiping addon data and fresh install of Kodi, still get the same error
> * Log complains of an access_token issue?



> **Describe the bug**
> 
> On a fresh install of Kodi and Otaku, I get an error when trying to add my SIMKL account. It says "Otaku error: An unknown error occurred". The popup screen with code and URL shows for a split second then disappears.
> 
> **To Reproduce**
> 
> 1. Fresh install Kodi
> 2. Fresh install Otaku
> 3. Try to add SIMKL account
> 4. Error
> 
> **Expected behavior**
> 
> No error
> 
> **Kodi Version**
> 
> * Kodi Version 19.5
> * Otaku Version 0.4.110
> * Nvidia Shield 9.1.1
> 
> **Additional context**
> 
> * I've tried clearing cache in Otaku, reauthorizing, wiping addon data and fresh install of Kodi, still get the same error
> * Log complains of an access_token issue?

hey, we were wondering if you sorted this issue, or are you still having problems?

**Comment by Goldenfreddy0703** [comment]
We will wait about a day or two

**Comment by CEV-A** [comment]
> could you provide the log? i just tested this on Kodi 20 and it worked fine. also check your Simkl account and revoke Otaku there should be an option to revoke access, then try reauthing again in Otaku

Still having an issue. Only difference I can think of is that I'm on 19 Matrix and not 20 Nexus, or a network issue.

There is no connected applications listed in my SIMKL account, since I've never successfully authorized it with Otaku.

Log: https://paste.kodi.tv/jekacikudi

**Comment by theasguard** [comment]
> > could you provide the log? i just tested this on Kodi 20 and it worked fine. also check your Simkl account and revoke Otaku there should be an option to revoke access, then try reauthing again in Otaku
> 
> Still having an issue. Only difference I can think of is that I'm on 19 Matrix and not 20 Nexus, or a network issue.
> 
> There is no connected applications listed in my SIMKL account, since I've never successfully authorized it with Otaku.
> 
> Log: https://paste.kodi.tv/jekacikudi

Hmm I'm not too sure on this, an access error usually suggests it can't access what you're trying to authorize into, could also be a network thing I'd suggest forking a 20+ kodi and trying, if issue persists it's a network issue, if it doesn't it's a kodi 19 issue and they must of updated a module and it broke any functionality it had. Those are my thoughts

**Comment by Goldenfreddy0703** [comment]
Hey so i wanna look into this further but do me a favor sense you already did a fresh install of kodi and everything. 

On your device, see if you can disable ipv6 on it, there should be tutorials online on how to disable ipv6 on Nvidia Shield>

Also one last thing is definitely restarting your device and router as well so that way, you can have a stable connection and then tell me if this has fixed your issue or not.
Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so i know this issue has been open for a month by now but i tried to replicate the issue on my windows computer sense i don't really have an issue as well as my google chromecast and simkl is working ok for me. I think you may need to try other devices or unplug your router and plug it back in or disable ipv6 sense ipv6 causes most of the issues.

Im going to go ahead and close this but if issues still persist or if you have any questions related to this, we will open this back up and look further. 

Thank you
