### ISSUE TITLE
Empty Kitsu lists throw error instead of just showing an empty folder

### ISSUE THREAD

**Issue by miguelkennedy** [Goldenfreddy0703/Otaku#26]
Hey there!

First of all, great addon. Many thanks for all the work you and your team have been putting in Otaku. It's much appreciated!

If we enable Kitsu integration and we browse to the Kitsu profile folder folder inside the Otaku addon, any folder we open there like "Next Up",  "Want to Watch", etc. that is empty will return an error instead of just showing an empty folder.

I have my theme set up with some widgets that point to these directories. If any of them is empty (for instance when I've catched up on all my Next Up episodes" and there's nothing left on that list/dir) Otaku is constantly throwing errors as my widgets auto refresh.

I'm attaching my Kodi log where you can find several errors thrown by Otaku as the widgets try to refresh my "Next Up" and Want to Watch" folders that are currently empty.

Hope you find the time to maybe sort this out. If those empty Kitsu lists could be handled as empty folders inside Otaku instead of throwing an error that would greatly improve the user experience instead of having to constantly be displayed Otaku error notifications as my widgets try to auto refresh from time to time.

Thank you!

[kodi.log](https://github.com/Goldenfreddy0703/Otaku/files/9769408/kodi.log)

**Comment by joezito129** [comment]
above line 125 of Kitsu.py you can add:
if not result.get('included'):
      result['included'] = []

this should fix the issue

**Comment by miguelkennedy** [comment]
Thank you, that fixes it! No more constantly annoying error notifications :)

Can you include this fix in the next release so I can leave my Otaku on autoupdate?

**Comment by miguelkennedy** [comment]
Created a pull request with the fix purposed by @joezito129 

https://github.com/Goldenfreddy0703/Otaku/pull/27

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry i did not see this sooner but i've noticed that too with empty and i never thought to fix it sense the user would have something in there watchlist already. Again, huge thanks for coming up with a fix for that and i will merge your pr for the next release soon.

**Comment by Goldenfreddy0703** [comment]
Thank you to everyone who fixed this error. 
New version of Otaku will be released in a few min.
