### ISSUE TITLE
Question about anime_mappings.db generation

### ISSUE THREAD

**Issue by crosfitjesus** [Goldenfreddy0703/Otaku#260]
Hi,

I have a question about the `anime_mappings.db` file in the `script.otaku.mappings/resources/data` directory. Could you please provide some information on how this file is generated or created?

Thank you!

**Comment by Goldenfreddy0703** [comment]
Hey there, I actually have a script that updates it monthly. The script runs on my server and it automatically gets updated on github. I would use github actions but there are a few api keys I have on there and all.

**Comment by crosfitjesus** [comment]
Thank you for the information! I appreciate the clarification.

Thanks again!
