### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nuhmey** [Goldenfreddy0703/Otaku#261]
Just found this addon and it is great. My question is. Is there a way to download the entire batch file at once for a season/show instead of having to do each episode one at a time?
Like some shows will have movies and specials, but won't show up when you search for them in movies and specials/season 0 won't show up under TV shows. The batch file will have it, but no way to get it.

**Comment by Goldenfreddy0703** [comment]
Unfortunately no but we do have a download manager coming very soon I just need either @Gujal00 or @joezito129 to help me with the resolver.py for local files and then I will make a huge release.

**Comment by Goldenfreddy0703** [comment]
Hey so great news, I finally fixed this bug that I've been having trouble with and now all i need todo is python 2 conversions and we should be able to release very soon. Hopefully i can either release 21st or 22nd.

**Comment by Goldenfreddy0703** [comment]
Hey so great news, there wasn't much python 2 converting so i went ahead and released so our latest version is 0.5.0. Hopefully this answers your question you have, feel free to give it a try and tell us what you think. Im gonna go ahead and close this but if you have any issues or concerns, please feel free to reply and we will open this back up. 

Thank you
