### ISSUE TITLE
[Feature Request] Smaller intervals in filtering by size

### ISSUE THREAD

**Issue by Sickhead01** [Goldenfreddy0703/Otaku#263]
Currently when setting a maximum or minimum size limit on torrents I can only increase/decrease at a minimum of 1GB. I want to set a minimum limit of 500MB but that's impossible and 1GB is way too much.
![photo_2024-05-21_15-00-56](https://github.com/Goldenfreddy0703/Otaku/assets/70452344/3cd73c1c-bef6-4ae1-b734-729fc29c303c)

**Comment by Goldenfreddy0703** [comment]
I knew somebody would complain about that eventually, yeah later tonight I will have minimum file size by decimal instead so it's similar to what how Seren has it.

As a workaround, have it go by internet speed and it will have it automatically adjust it for your liking.

**Comment by Goldenfreddy0703** [comment]
Hey so i went ahead and added Smaller intervals in filtering by size, will have this release tonight. Im going to go ahead and close this but if you have any questions or concerns, please feel free to reply and we will open this back up and look further into this. 

Thank you

**Comment by Sickhead01** [comment]
Yeah so, Thanks for adding my request. I appreciate your hard work but the size filter setting is bugged. I set my minimum episode size to 0.5 GB and max to 300MB. It works as intended on some shows but on others it doesn't do anything at all or does the opposite of what it's supposed to and filters out everything except torrents smaller than 500MB

![photo_2024-05-21_23-50-51](https://github.com/Goldenfreddy0703/Otaku/assets/70452344/978637e8-c612-4b1a-bc7f-64b8cbd912de)
![photo_2024-05-21_23-46-50](https://github.com/Goldenfreddy0703/Otaku/assets/70452344/76d49cbd-1243-4530-9aac-df9c74d4ae1d)
![photo_2024-05-21_23-46-51](https://github.com/Goldenfreddy0703/Otaku/assets/70452344/748f3d50-d49a-461f-aaf2-01c45a367a11)
![photo_2024-05-21_23-52-37](https://github.com/Goldenfreddy0703/Otaku/assets/70452344/8a7d6b0c-0c79-43a2-b3fa-13bbfbec6b3b)

**Comment by Goldenfreddy0703** [comment]
> Yeah so, Thanks for adding my request. I appreciate your hard work but the size filter setting is bugged. I set my minimum episode size to 0.5 GB and max to 300MB. It works as intended on some shows but on others it doesn't do anything at all or does the opposite of what it's supposed to and filters out everything except torrents smaller than 500MB

Hey so from doing some testing, i tested multiple Animes and episodes and it seems to be working for me just fine but i do notice that you said that you set your max to 300mb which can't be possible cause i have the file selection set in gb, not mb and we based the filtering by size off of Seren where its going by gb. I can probably add an option to filter in mb instead or have max size use decimal. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/cc91d4cd-8139-47fc-8fd9-3ca2b056ea42)

**Comment by Sickhead01** [comment]
Oh the MB was a typo for the maximum. It's in GB. The highest it can go

**Comment by Goldenfreddy0703** [comment]
Oh then wait I'm confused, ok so what do you have your settings on and what is it supposed to do exactly?

**Comment by Goldenfreddy0703** [comment]
Ok I see now, will look into that today, thanks for explaining.

**Comment by Goldenfreddy0703** [comment]
Hey so i just made a release so hopefully it should fix this bug. Thank you noticing this, apparently this was a long time bug and no one has noticed. So what happened was apparently gb and mb were not being converted which was why you had issues with the minimum size, again thank you for noticing this and hopefully this should fix it. 

If you do have any other issues with this, please feel free to reply again and we will look further, Thank you
