### ISSUE TITLE
✨️ [Feature Request] Sorting lists by ascending or descending order

### ISSUE THREAD

**Issue by InternetRooke** [Goldenfreddy0703/Otaku#265]
Under the watchlist section, we are able to choose how lists should be sorted in list settings "sort by"... is it possible to also add "sort order" to this, I would like to sort my lists in ascending order. Just wondering if this could be added.

Thank you for this amazing add-on!!

**Comment by Goldenfreddy0703** [comment]
Heyyyy @InternetRooke looks like i was able to add the setting but the only watchlist i could not set the setting is Simkl sense simkl's watchlist is a bit weird for some odd reason. Will release very soon.

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so looks like i made an early release so should be out by now. I'm going to go ahead and close this but if you have any issues related to this or any concerns, Please feel free to message in here and we will open this back up. 

Thank you

**Comment by InternetRooke** [comment]
> Heyyyy @InternetRooke looks like i was able to add the setting but the only watchlist i could not set the setting is Simkl sense simkl's watchlist is a bit weird for some odd reason. Will release very soon.
> 
> Thank you

Ahh, thank you very much. I really appreciate this. I don't really use simkl, I am using anilist, so hopefully, people who use simkl don't need this... Thanks again for your continued effort 🙏🙏

**Comment by InternetRooke** [comment]
> Hey so looks like i made an early release so should be out by now. I'm going to go ahead and close this but if you have any issues related to this or any concerns, Please feel free to message in here and we will open this back up. 
> 
> Thank you

That's alright, will do.

**Comment by InternetRooke** [comment]
> Hey so looks like i made an early release so should be out by now. I'm going to go ahead and close this but if you have any issues related to this or any concerns, Please feel free to message in here and we will open this back up. 
> 
> Thank you

Hello, sorry to come back to this, just wondering if the sort order could be different for current... i.e if it is possible to have descending on the other list but ascending for current?

**Comment by Goldenfreddy0703** [comment]
I mean it could be possible but I would have to add a bunch of settings for the watchlist and that would be quite annoying.

**Comment by InternetRooke** [comment]
> I mean it could be possible but I would have to add a bunch of settings for the watchlist and that would be quite annoying. 

Thanks for responding. I get that adding a bunch of settings could be a hassle. Maybe there's a simpler way to do it? Like one additional setting for just "current" sort order? if it's not too much trouble, please consider it 🙏🙏
