### ISSUE TITLE
[Feature Request] Source Filtering To Exlude Certain Words

### ISSUE THREAD

**Issue by Sickhead01** [Goldenfreddy0703/Otaku#267]
Similar to how it already has the setting to only include sources with certain words/numbers, it would also be good to be able to exclude certain words. For example, I do not like the torrents from an uploader called "EMBER". They are always really small, less than 500MB for each episode at 1080p, and the real problem is that his torrents often appear at the top of the torrent list for some reason despite the preferred language I set. I have it set to play dub by default if available but even when EMBER has no dub for the episode i'm trying to watch his sub torrent is at the top for some reason...and even if it was dubbed i still don't wanna watch his torrent because it's evidently highly compressed. I tried filtering by size to cut out anything lower than 500MB but now I'm getting his sub BATCH torrents appearing at the top (which are still very small for complete seasons). So i'd like to just exclude EMBER or any other undesirable factors specifically.

**Comment by Sickhead01** [comment]
Or alternatively just like how option to "Prioritize Dual-Audio/Multisubs/Batch Sources" you could just add the option to sort the torrents scraped by size while still having the language and quality in mind. Like based on my settings all the 1080p dubs at the top sorted from largest to smallest

**Comment by Goldenfreddy0703** [comment]
@jonathanluepfert hey sorry to bother you but your pr is doing a fantastic job but this user wants to filter out or exclude an up loaders torrents called "EMBER"s torrents, could you make a setting to exclude titles and names? If you can that would be great.

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey @Sickhead01 , looks like i was able to do this easily, When you enable Source Filtering by Release Title, you should have an option called Exclude Keywords where it will Exclude any Keyword you don't want. 

@jonathanluepfert looks like i was able to do this easily so i went ahead and completed this but if you could look at my changes and see if i did this right, that would be fantastic, 

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so looks like i made an early release so should be out by now. I'm going to go ahead and close this but if you have any issues related to this or any concerns, Please feel free to message in here and we will open this back up. 

Thank you
