### ISSUE TITLE
Trakt integration?

### ISSUE THREAD

**Issue by minhgi** [Goldenfreddy0703/Otaku#268]
Would it be possible to integrate Trakt and use it as a "watchlist " service similar to Myanimelist and Anlist.  Seems every anime I watched or searched for can be found on Trakt.

**Comment by Goldenfreddy0703** [comment]
At the moment, no due to episode count and all, we have the id's for trakt but not the episode count which is a problem.

**Comment by minhgi** [comment]
Thank yiu

**Comment by minhgi** [comment]
I can get the Trakt to sync with Otuka using the Kodi builtin addon.   The problem if you use Trakt and Seren (any other addon), it wont sync back to MyAnimeList.

**Comment by Goldenfreddy0703** [comment]
Makes sense cause reason why it wouldn't synce to Mal is due to episode count sense trakt and mal can have different episode count, we can map them by id but episode count is very important.

**Comment by minhgi** [comment]
Understood. Hopefully you find a solution sometime in the future. I have a trakt widget that combines both my anime and TV shows for the home screen. It work but I have to go otuka to remove the episodes that watch from myanimelist. Thanks for efforts in researching it.
