### ISSUE TITLE
CRASHING ISSUE

### ISSUE THREAD

**Issue by XHALOX18** [Goldenfreddy0703/Otaku#269]
I have a issue with my otaku I've tried and experienced the same issue on two different devices whenever I run otaku with the embed it crashes my kodi and my pc is way above average so it couldn't be performance and my firestick is pretty average but otaku only works when l'm using the real-debrid method but with the embed it just crashes

**Comment by Goldenfreddy0703** [comment]
Question, you don't happen to have the HD-1 embed enabled do you?

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/6b2da905-a7b3-4da7-8b29-c747820578f8)
If so then that could be related to the crashing unless it happens on every embed.

**Comment by XHALOX18** [comment]
At first I had it on but then I decided to turn it off and do a test and it still crashes

**Comment by Goldenfreddy0703** [comment]
Did you clear torrent cache before testing?

**Comment by XHALOX18** [comment]
I didn't but I don't think that would be the issue because I tested the embed alone with the real-debrid off just to be sure and it would crash

**Comment by XHALOX18** [comment]
I take it back it's working now thanks

**Comment by Goldenfreddy0703** [comment]
Awesome, must have been either a router issue or one service was down but not quite sure.
