### ISSUE TITLE
Clicking on"Marked at Watched Watchlist" give error popup

### ISSUE THREAD

**Issue by minhgi** [Goldenfreddy0703/Otaku#270]
Clicking on"Marked at Watched Watchlist" give error popup.  This is happening for both MyAnimeList and Anlist.

![image](https://github.com/Goldenfreddy0703/Otaku/assets/4175702/e551b1f5-2192-4a1a-a884-40631d341949)

![image](https://github.com/Goldenfreddy0703/Otaku/assets/4175702/932e232f-a132-459a-b467-e322c8d5e6d2)

**Comment by Goldenfreddy0703** [comment]
That's a bit odd, it's possible that you may wanna rebuild database, sometimes watchlist can have trouble with certain animes like these.

**Comment by minhgi** [comment]
Hi Freddy.

This with any anime I tried.   If I go into MyList Manager, I can mark it as watch, delete, and etcs all the functions work.  Thank for looking into it.

**Comment by Goldenfreddy0703** [comment]
Wait so just incase, did that fix your issue?

**Comment by minhgi** [comment]
Still the same.

**Comment by minhgi** [comment]
Just saw update for Otuka.  Seem the problem was fixed. Thank you so much,   Without that function, can't mark an already episode and season annoying.  Please close the ticket.

**Comment by Goldenfreddy0703** [comment]
Ahh sounds good, closing ticket.

**Comment by minhgi** [comment]
Hi Freddy.

Seem like issue have came back with Myanimelist.  also the anime is not syncing with Myanimelist either.

**Comment by Goldenfreddy0703** [comment]
Did you try the troubleshooting steps and all. Clear cache, rebuild database, etc

**Comment by minhgi** [comment]
Yes all that was done. Switch to anime list and sync and watched list function work. BTW. Which tracker are you using?

**Comment by Goldenfreddy0703** [comment]
Anilist, try reauthorizing the watchlist and see if that works. If that doesn't work then try other animes and see if it's just that particular anime your watchling.

**Comment by minhgi** [comment]
Reauthorization MAL is still the same.  "Marked at Watched Watchlist" and video progress does not sync to MAL.   I just switch to AnimeList, like your preference.

Thanks you
