### ISSUE TITLE
Downloaded Otaku but all folders are empty

### ISSUE THREAD

**Issue by boog11** [Goldenfreddy0703/Otaku#272]
The add-on has been downloaded correctly but when I click on any section of the menu the next page opened up is completely blank with only the two dot prompt to return to the main menu. From “Airing Anime” to “TV Shows” or “Top 100 Anime” the issue is the same. I’m not sure what the problem is & would greatly appreciate any help.

**Comment by Goldenfreddy0703** [comment]
Mmmm.....that's a bit interesting, it's possible you may need to reinstall Otaku. If you don't mind telling me what version of kodi and what device that would be great.

If you could also provide a log that would be great. Thx

**Comment by boog11** [comment]
I’m pretty sure it’s the latest update of kodi 19 but I’m not sure how to check that or provide a log? I’m on amazon firestick. I will try uninstalling & reinstalling when I get home.

**Comment by Goldenfreddy0703** [comment]
Hey did you ever uninstall and reinstall it by any chance? Another person had this issue and got it fixed on there end, they either did a reinstall or a fresh start on kodi. This happens on some addons for some odd reason.

**Comment by theasguard** [comment]
i noticed a lot of issues with older Kodi versions with several addons, it could also be module updates in kodi 19 thatd break it, so many versions of kodi its quite insane really. im also wondering if you solved this issue

**Comment by Goldenfreddy0703** [comment]
I'm not sure if this issue is solved tbh, I think I might close it cause on reddit I saw several addons where there addons settings were blank as well as the menus so could be a bug with omega sometimes. Not sure.

**Comment by Goldenfreddy0703** [comment]
I'm not sure if this issue is solved tbh, I think I might close it cause on reddit I saw several addons where there addons settings were blank as well as the menus so could be a bug with omega sometimes. Not sure.

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this cause there has not been a response for weeks now, if you do respond or have this issues, we will open this back up and look further. 

Thank you
