### ISSUE TITLE
Feature Requests: Elementum Integration

### ISSUE THREAD

**Issue by rahadiancs** [Goldenfreddy0703/Otaku#274]
Hi,

Is it possible to integrate the torrent function with Elementum addons? Using Otaku as the frontend, and Elementum as the backend.
For now torrent only works if we have debrid account (please correct me if I'm wrong). I can play anime on torrent using Elementum, but it requires me to search manually, it's rather tedious.

I find that Otaku has very good list season based Anime show, but embed is very unreliable, buffering so often even though I have 200mbps connection, I can watch 4k youtube no problem. If Elementum can stream Anime directly with torrent, it would be nice if somehow Otaku can pass the search result to Elementum, and let Elementum play it.

**Comment by Goldenfreddy0703** [comment]
Unfortunately Elementum integration would be challenging to add and reason why we are mainly a debrid addon/embed addon is mainly cause we don't want users to have isp complaints and all of that. One of our users by the name of servicerobot has been wanting to add Elementum integration, but we never really had enough contributors to help with that. We can try to look into this, but it will take a long time.

**Comment by Goldenfreddy0703** [comment]
Also about embeds, they are not very unreliable but if you have all providers enabled then that could be the reason why they are slow. If you do want faster embeds, try Hianime, Aniwave, Animepeha. Those three embeds are super fast and great.

**Comment by Goldenfreddy0703** [comment]
Also about embeds, they are not very unreliable but if you have all providers enabled then that could be the reason why they are slow. If you do want faster embeds, try Hianime, Aniwave, Animepeha. Those three embeds are super fast and great.

**Comment by rahadiancs** [comment]
Thank you for all the valuable insight. I will try that suggestion. My use case is watching current Anime, so yeah I find that torrent provides the best speed for me, especially the HEVC one due to it's very small size (I don't mind the minor artifact)

**Comment by Nuklear92** [comment]
> Hey so im actually going to close this but we still plan to add EasyNews and Offcloud Debrid one day once we have a contributor to help us code those. 
> 
> 
> 
> Thanks

Awesome, can't wait for that day to come! Easynews will definitely be a great addition since it surprisingly has lots of anime movies and tv shows in great quality just like Debrid services. 👍
