### ISSUE TITLE
Portuguese & Spanish Dubs/Subs not working

### ISSUE THREAD

**Issue by RodrigoMaroteOfficial** [Goldenfreddy0703/Otaku#275]
Being using the add-on for about 6 day on Steam Deck and it's awesome, however, for some reason yesterday the Otaku animes source (PT-BR dubs and subs) stopped working for me. I also tried the Spanish one (AnimeLatino) and it also does not load (this one actually just never finishes finding sources, the PT-BR one loads but does not give any results). The English options are working fine.
I also noticed that the movies section have zero sources too (even from the english ones), but I don't know if it was supposed to be like that since I only used the anime shows for the time being. I tried everything on the troubleshoot page besides deleting and then installing the addon again; Should I just try that or is this a temporary known error that I'm not aware? I did not see any error messages popping up at all.

**Comment by Goldenfreddy0703** [comment]
Hey so Otaku Animes could have stopped working so as a workaround, you may want to utilize the H!Anime Provider and have your Preferred Subtitle and Audio Language configured in the Playback Category of Otaku Settings, We will have @Gujal00 look into this very soon. 

Thank you

**Comment by Gujal00** [comment]
fixed in https://github.com/Goldenfreddy0703/Otaku/commit/6084c001e34557930026b3d4ce029a9feaeb886b

**Comment by Goldenfreddy0703** [comment]
Hey so huge thanks to @Gujal00 for fixing this bug. We just made a release so hopefully Portuguese & Spanish Dubs/Subs will be working for you. I'm going to go ahead and close this but if you have any issues or concerns related to this, we will open this back up. 

Thank you
