### ISSUE TITLE
hentai genre empty and hentaiwont play when a title is found without only search

### ISSUE THREAD

**Issue by jnail776** [Goldenfreddy0703/Otaku#277]
I have real debrid enabled on an android and pi Otaku installs.  Searching for adults only titles gives results but they won't play and Otaku errors and I need to check the log.  Enabling the hentai genre makes it display but when I select it it's empty.  This is happening on both an android tablet and a pi.

**Comment by Goldenfreddy0703** [comment]
Yeah...this addon is not really meant for hentai, that's why you will mostly receive errors
