### ISSUE TITLE
Add 480p max resolution

### ISSUE THREAD

**Issue by Eskander** [Goldenfreddy0703/Otaku#279]
Hello! Thank you for maintaining this great addon.

Could you please add a setting for 480p max resolution? It's useful for conserving metered data while watching on phone/tablet.

**Comment by Goldenfreddy0703** [comment]
This is a first time hearing someone wanting 480p anime, we probably could but im not sure if there are torrents or embeds out there that even support 480p, we have 360p but not sure if that will help.

**Comment by Eskander** [comment]
Yeah I'm sure the use case is quite uncommon.
360p helps too, but it's not currently selectable in max resolution settings (lowest is 720p).
I suggested 480p since there are embeds with said quality, and failing that it would fallback to 360p anyway.

**Comment by Goldenfreddy0703** [comment]
Ohhh wait, 360p is NA, It should have been SD, if you don't mind. Try NA and see if that works. If not then I will look into this more.

**Comment by Eskander** [comment]
That indeed worked, thank you!

Somewhat related, but I noticed that InputStream embeds don't follow Otaku's max resolution setting, they follow InputStream Adaptive settings instead. Is that a known behavior?

**Comment by Goldenfreddy0703** [comment]
Yea it is cause embeds run very smoothly with InputStream Adaptive. Back then they use to be buggy for some odd reasons especially with playback. Thanks to InputStream Adaptive, we got those bugs fixed.

**Comment by Eskander** [comment]
Alright, thanks for your help.

**Comment by Goldenfreddy0703** [comment]
Hey so i took this into account and i decided instead of having NA, i decided to add 480p and EQ into our options of resolutions and there were some improvements and fixes a discovered when doing this. 

Thank you for making this Feature Request.

**Comment by Eskander** [comment]
Thank you for looking into this! I gave it a try, and while 480p works as expected, it's not quite clear what EQ quality means. From looking at the code I understand that it corresponds to 576p, is that correct? And if so, it standard to note 576p as EQ?

**Comment by Goldenfreddy0703** [comment]
EQ quality most likely means Embed Quality so that way you can you can't find embed qualities your looking for, you can always try EQ quality.
