### ISSUE TITLE
Steins;Gate 0 showing season 1 episode list instead

### ISSUE THREAD

**Issue by icpryde** [Goldenfreddy0703/Otaku#28]
Dude the add-on is amazing you and the team did so much stuff and i'm so impressed! 

I just wanted to mention i noticed Steins;Gate still grabs the wrong season for example I have Steins;Gate 0 but its showing the episode list for the 1st season.

![Screen Shot 2022-10-13 at 4 07 40 PM](https://user-images.githubusercontent.com/29389746/195699100-5716894f-0859-49c0-8b1d-bc442caadcea.png)

![Screen Shot 2022-10-13 at 4 11 10 PM](https://user-images.githubusercontent.com/29389746/195699621-dafa207b-1297-4baf-a4e7-74a50437b668.png)

**Comment by icpryde** [comment]
just another thing i noticed when scraping for Aoashi i can't seem to find any torrents I have PM set up as well just this one specifically i can't find.

**Comment by Goldenfreddy0703** [comment]
Mom odd, we will look into that when we have time.

**Comment by Gujal00** [comment]
![screenshot00000](https://user-images.githubusercontent.com/17394059/195728378-232fde75-2e19-4d75-ad7e-0087e85a668a.png)
I have both Alldebrid and PM enabled and looks like PM doesnt have them cached. So all you can do is to add those torrents from nyaa to your PM so that they get cached

**Comment by icpryde** [comment]
oh i see, ok didn't realize that was the issue
