### ISSUE TITLE
Combining seasons into one folder?

### ISSUE THREAD

**Issue by Rummyster** [Goldenfreddy0703/Otaku#280]
When searching for a show each season will be shown separately.  Is there an option to just display the show and keep the seasons held within? When displayed as widgets if I have 20 items showing 5 would be the same show.

**Comment by Rummyster** [comment]
Can the context menu be used for widgets?

**Comment by Goldenfreddy0703** [comment]
Maybe but you would need to have the exact path for the context menu, you would have to input a custom path

**Comment by Rummyster** [comment]
Sounds good, thanks. I'll play around with it. Also nice work with the addon it is very well done!

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this but hopefully you were able to get your seasons into one folder, If you still have not figured that out, there is an addon called Autowidget, i use this addon for basically every skin build i do and its the best and works very well with widgets. Hopefully this should help you. If you have any questions or concerns related to this, Please feel free to message and we will look into this further, thank you.

https://github.com/drinfernoo/plugin.program.autowidget
