### ISSUE TITLE
Feature Request: could you add https://donghuastream.org/ for chinese animation series to this addon

### ISSUE THREAD

**Issue by software-ace** [Goldenfreddy0703/Otaku#284]
Hello, I appreciate the efforts in this addon. 
It's one of the best of all time that I tried.

it would be an even greater addon if you could add a Chinese animation source to it like https://donghuastream.org/ or any other websites if you know better ones.

all the best guys. :smile_cat:

**Comment by Goldenfreddy0703** [comment]
We don't really support Chinese anime as much cause most Chinese anime does not even have episode meta available unfortunately. We can probably still add this but this one is totally up to @Gujal00 on this one sense he handles all the embed stuff.

**Comment by Goldenfreddy0703** [comment]
Hey so if you don't mind, im gonna go ahead and close this but please add https://donghuastream.org/ to #144 so that way, we have less issues. 

Thank you

**Comment by software-ace** [comment]
Done 👍 
Thanks guys
