### ISSUE TITLE
Set Views

### ISSUE THREAD

**Issue by Dappakid13** [Goldenfreddy0703/Otaku#285]
It it possible to have a set view option when I can adjust for menus, movies, TV shows, seasons, episodes etc like how fen has it?

**Comment by Goldenfreddy0703** [comment]
Are movies and tv shows are combined and we have no season content menu cause we utilize an anime database, not a global database like fen or seren. 

In Anime Database, seasons are not in one anime series cause seasons get released individually. 

For view options, we have an option called set viewtypes in our general settings category of Otaku.

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this but incase you cannot find the setting, here is is, hopefully this should help. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/e1e765bc-1aab-461e-b9ec-8a8e8bc6de76)

If you have any more questions feel free to ask and we will look into this further, Thank you

**Comment by Dappakid13** [comment]
Just saw this but thanks though

**Comment by port-eighty** [comment]
@Goldenfreddy0703 I have never gotten this to work, does this not work for certain skins?

**Comment by Goldenfreddy0703** [comment]
It should work, bur you may have to use the custom view id's sense skins have different viewtypes and all.
