### ISSUE TITLE
Feature Request: Option to select folder as source select

### ISSUE THREAD

**Issue by 20mattay05** [Goldenfreddy0703/Otaku#286]
Instead of using providers, one could select a folder where all the episodes already are and pressing play will then find the file in that folder and proceed to play that file as normal

**Comment by Goldenfreddy0703** [comment]
We kinda already have that, its basically just utilizing the select source in the playback category of Otaku settings or when using the context menu on one the episodes.

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this cause there has not been any response or anything from here, anyway hope this resolves your issues, if you have any more questions, feel free to reply and we will get back to you on this. 

Thank you
