### ISSUE TITLE
[Issue] After adding "unique id for trakt scrobber"

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#288]
So, all in all it's a nice addition to improve Trakt scrobbing recognition. However, when you play an episode directly from the **Next Up** menu the trakt scrobber can't detect the correct episode, tv show title you're playing due to Kodi displaying only the number of the episode without any broader info of the episode, season, show title. The Trakt scrobber will start scrobbing some weird random title instead. The only way it the trakt scrobber detects the show and episode correctly is by playing directly from the **Current** menu and manually searching through the tv show, season.

Below I'll show some screenshots of the differences and how playing from Up-Next makes the trakt scrobber scrobbe some random title.

**Episode played back from Next-Up**

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/090817bc-9f8b-42ae-99f5-6e79504c0d36)

**Will trigger Trakt Scrobbe to a random title that has nothing to do with Anime**

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/629c24f6-5a2d-46d6-98fa-bd0d1d5de460)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/9678c193-2f2e-4a4c-a4a0-84df34b5553b)

**Playing back the same Episode from Current menu**

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/98abb84e-7bfe-4c85-8c75-afe0ca0701b7)

**WILL trigger Trakt Scrobbe to the correct Episode, Season, Title**

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/dfa9ed1d-a898-4f4c-976f-701962146a9e)

As you can clearly see, whenever you playback anything from the Next Up menu there's simply no information displayed in the media player, and I believe that's what is causing the Trakt Scrobbe to go crazy and Scrobbe random content. 

Overall, the addition of this unique ids seems to be working because Trakt Scrobbe seems to pick up Otaku's content and Scrobbe them correctly as long as the information is displayed correctly within the Media Player I believe.

In any case, this can easily be replicated if you have the Trakt account, the addon installed from the official Kodi Repo and you go ahead and play any of your Otaku's **Next Up** Episodes if you're using AniList, MAL, etc.

The skin I'm using from the screenshot is Arctic Fuse, just in case if you discover this only happens with that skin. Or if you have any other skin installed, try to replicated in your end. And see if the issue is the same.

My apologies for the long explanation, I wanted to provide as much detail as possible from the issue in order for you guys to see if perhaps any further improvements is needed to the **Unique IDs for Trakt Scrobber** to be able to detect the episode, season, show correctly regardless of the missing information in the media player whenever something is played back from the **Next Up** menu.

**Comment by Goldenfreddy0703** [comment]
Ok I kinda see what you mean cause I've always thought Next Up was very weird, is there a possibility that you used Next Up as a widget cause if you did then it's quite broken when utilizing a widget.

**Comment by Nuklear92** [comment]
> Ok I kinda see what you mean cause I've always thought Next Up was very weird, is there a possibility that you used Next Up as a widget cause if you did then it's quite broken when utilizing a widget. 

Yes, you're correct I'm using Next Up as one of my home screen widgets in Kodi. I'll try doing it again from within inside the Otaku's addon and see if there's any difference. 

I'll report back in a moment.

**Comment by Goldenfreddy0703** [comment]
Hopefully, it should not be bugged inside Otaku. If the Trakt Scrobbler on Next Up works inside Otaku then I will be closing this issue cause we basically already have a duplicated issue with next up and widgets.

**Comment by Nuklear92** [comment]
> Hopefully, it should not be bugged inside Otaku. If the Trakt Scrobbler on Next Up works inside Otaku then I will be closing this issue cause we basically already have a duplicated issue with next up and widgets. 

Well, I just doubled checked by going inside of the otaku addon and using the next up from there. And sadly, the issue still persist, the Trakt scrobber tracks some random title not related to anime just like I showed in the screenshots above. 

I even changed my skin back to Estuary to see if it was skin based and still the same issue. Happens either by using the **Next Up** from inside of Otaku or by using it as a widget in the Kodi homescreen.

It's quite a bummer that the **Next Up** haven't been functioning like for example the **Current** menu does, which seems to display episode, titles correctly within the Media Player's OSD and Trakt addon picks and Scrobbe the episodes correctly. 

It's a very handy and convenient menu, just like "Next Episodes", "Up-Next" are within FEN and Seren addons that you have a Mixed Episode list of all the current tv shows you might be watching and it's just a one click, scrape and play. Unlike **Current** menu where you have to click the tv show title, then scroll to the next episode you're watching, then scrape, and play a link. 

But, since you're saying you have another duplicated issue about the Next Up. Just close this one, I'll see what I can do to stop Trakt addon to Scrobbe random content. 

Hopefully, in the future you guys could plan to overhaul the Next Up section so it can be more accurate when it comes to displaying meta info within the player's OSD and maybe be more accurate with Trakt scrobber. 🙂

**Comment by Goldenfreddy0703** [comment]
wait did you clear cache, torrent cache, and rebuild database?

**Comment by Nuklear92** [comment]
> wait did you clear cache, torrent cache, and rebuild database?
> 
> 

Yeah, the issue still persist. It seems like there's something wrong in the way the Next Up behaves that it doesn't seem to play well with Trakt scrobber. Every other menu works fine and Trakt addon scrobbe correctly. 🤷‍♂️

I'll figure something out in order to not have to use that menu even though it's quite handy. Maybe use the Next Episodes with TMDB helper addon and use otaku as the scraper/player. Either way I'm still hopeful that one day you guys are going to take a moment and overhaul that menu in specific. 🙂
