### ISSUE TITLE
Kodi Tv shows not working Xbox Kodi 20.5 & 21

### ISSUE THREAD

**Issue by AlexGitHub1405** [Goldenfreddy0703/Otaku#291]
After deleting and redownloading clearing cache and re-downloading Kodi the tv show anime still don’t work only movies

**Comment by Goldenfreddy0703** [comment]
Hey so a change had to be reverted and released so try out our latest version and see if this fixes your issue. 

Thank you

**Comment by AlexGitHub1405** [comment]
I’ve re downloaded otaku and the tv shows still don’t load this is what comes up when I checked the log
![IMG_1627](https://github.com/Goldenfreddy0703/Otaku/assets/174119735/e4c0736f-2c76-4c0a-bfff-cc2e15b2c27f)
![IMG_1626](https://github.com/Goldenfreddy0703/Otaku/assets/174119735/fd3bd922-9205-45b4-a72a-64e7b26b4e23)

**Comment by Gujal00** [comment]
upload the log using `Kodi Log uploader` and provide the short url that it display here. Those pictures above habe nothing relating to OTAKU

**Comment by AlexGitHub1405** [comment]
![Uploading IMG_1630.jpeg…]()

**Comment by AlexGitHub1405** [comment]
My bad here it is 
![IMG_1630](https://github.com/Goldenfreddy0703/Otaku/assets/174119735/d33b00ed-262a-4c7b-b290-cacb3b5d9679)

**Comment by Goldenfreddy0703** [comment]
Hey so we had a change that had something todo with Trak_id which has caused some peoples kodi to crash, would you mind giving yours a test and seeing if its working on your end?

Thanks

**Comment by AlexGitHub1405** [comment]
Still no working ![image](https://github.com/Goldenfreddy0703/Otaku/assets/174119735/e3743540-27bc-4991-95c0-26e13b5c9e5b)

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at the log, we think your unable to access the simkl so try to see if you can access: https://simkl.com and if not, try doing these steps

1. See if you can access this site: https://simkl.com
2. Unplug your router and plug it back in
3. Unplug your xbox and plug it back in
4. If none of those work, then try disabling ipv6 on your xbox sense ipv6 blocks certain websites

**Comment by AlexGitHub1405** [comment]
For some reason this website just won't open with out a vpn and my router is a 4g modem that won't let me use vpns through it

**Comment by Goldenfreddy0703** [comment]
Ahh then I guess we found the problem then, did you try all the steps I mentioned above?

**Comment by AlexGitHub1405** [comment]
I've done everything except the router but I'll do that later tonight

**Comment by Goldenfreddy0703** [comment]
Interesting, another user is having the same issue so let me see if I can look into it.

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at this issue, there is nothing we can really do sense we utilize simkl for most of our episode meta, we can probably add our backup episode meta in the future but it may not be ready yet unless @Gujal00 can add the fallback. 

Im going to close this for now, your best bet is to either wait for a episode meta fallback fix or setting up a vpn if possible. If you have any more questions or concerns, please feel free to message and we will get back to you.
Thanks
