### ISSUE TITLE
Spanish source not working on new animes.

### ISSUE THREAD

**Issue by Piasmus** [Goldenfreddy0703/Otaku#296]
Hi! I'm spanish user, so I'm sorry for my bad english. I've been using the addon for a few months now and I hadn't had any problems. But I just tried to watch chapter 8 of Kimetsu No yaiba season 5 and the source of AnimeLatinoHD does not appear, I tried out of curiosity with chapter 7 of last week that I saw in the addon and no source appears either, in fact there is no source other than that of chapter 1, and it is the same situation for Boku No Hero Academia season 7. On the other hand, HiAnime fonts do appear without a problem. I use kodi on a firestick tv lite if it helps to know.

**Comment by Goldenfreddy0703** [comment]
Hey so there is nothing we can really do cause Kimetsu No yaiba season 5 chapter 8 just came out 7/30/24 which should not have Spanish sources already out so you may have to wait. As for Boku No Hero Academia season 7 chapter 1, its possible that HiAnime nor AnimeLatinoHD has Spanish sources so if you have a debrid account, you might be better off using torrents which contain multi-subs or dual-audio. 

Im going to close this issue but if you are still having problems related to this, let us know and we will look into it further.
Thank you

**Comment by Piasmus** [comment]
Hello! Thanksfor your answer, I open the topic because the source is already available in AnimeLatinoHD, it is the website that I use regularly to watch anime, in fact I ended up watching it on my pc on said website, in addition to that as I comment that all the sources of AnimeLatinoHD of the complete season have disappeared, and I saw until chapter 7 in the addon the same day of the premiere without problem.
