### ISSUE TITLE
Update multiple tracking sites

### ISSUE THREAD

**Issue by guybarner** [Goldenfreddy0703/Otaku#297]
Hey, it will be nice if you could update multiple tracking sites. Like I want to watch episode and update it in myanimelist and Anilist at the same time. Thank you and have good day :)

**Comment by Goldenfreddy0703** [comment]
We tried this a long time ago and for some odd reason, it just wasn't possible due to how Otaku was coded, also if we were to have multiple watchlist tracking, we would have to recode watchlist manager and watchlist indicators and that would be a huge pain.
