### ISSUE TITLE
One Piece 3D2Y redirects me to episodes list instead of playing the movie

### ISSUE THREAD

**Issue by sgrontflix** [Goldenfreddy0703/Otaku#298]
If I click on the One Piece 3D2Y movie I get redirected to the regular episode list instead of the actual movie. I suppose this is a scraping problem that could also manifest elsewhere?

I haven't edited my settings at all and I'm on a fresh install of Kodi.

**Comment by sgrontflix** [comment]
Hi, I don't think this should be tagged as "Completed"... Looks like a bug to me.

**Comment by Goldenfreddy0703** [comment]
Hey there, last night, we actually fixed this, reason why its not released yet is cause we are working on another issue with fanart at the moment. This will be released very soon.

**Comment by sgrontflix** [comment]
That's great!! Thanks!!

**Comment by Goldenfreddy0703** [comment]
Hey so good news, we just released about an hour ago so feel free to test and see if that works for you. 

Im going to close this but if you have any issues related to this, please reply back and we will look further into this. 
Thank you
