### ISSUE TITLE
Can't open settings + can't view anime list + can't open anything without the update notes popping in my face 

### ISSUE THREAD

**Issue by guybarner** [Goldenfreddy0703/Otaku#299]
All the problems listed above, i think it has something to do with the recent update

**Comment by guybarner** [comment]
I am sorry if I wrote it in a rude way btw

**Comment by Goldenfreddy0703** [comment]
You may have to reinstall Otaku than have your cache and database cleared and all.

**Comment by guybarner** [comment]
Did what you said and it is now fixed, thank you very much :) and again sorry about how I said it
