### ISSUE TITLE
Custom search path for skins?

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#3]
I tried adding custom search paths for Otaku in both Arctic Horizon 2 and AuraMod by just changing 
`plugin://plugin.video.kaito/?action=search_results&action_args=` 
to 
`plugin://plugin.video.otaku/?action=search_results&action_args=`

But it seems to only pull in the root menu of the addon and not any actual results? Has the search path changed or am I doing something wrong? I originally got the Kaito search path from here: https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/104

from AH2 skin search (you can see Kaito pulls correct results):
![screenshot00002](https://user-images.githubusercontent.com/13154733/186226571-06a291ca-ef7f-4416-9567-aa4e37e65395.png)

**Comment by Goldenfreddy0703** [comment]
Hey @meesterexx, we may need to reconfigure the custom search path for skins cause, this was part of the original Kaito in past and it required two lines instead of one sadly so in the feature, we will probably reconfigure that. 

Sense your using AH2 Skin, This little workaround could probably help you as long as you don't update AH2

`plugin://plugin.video.otaku/search/`
`/1`

**Comment by Goldenfreddy0703** [comment]
In the future, it will be change, it will probably take a little while tho. Thank you

**Comment by meesterexx** [comment]
No worries, I can wait for a final solution. I will use the search  in the addon for now. Thanks!

**Comment by Goldenfreddy0703** [comment]
Hey anytime!!! Hope you like our addon so far. 😁

**Comment by Goldenfreddy0703** [comment]
Hey good news @meesterexx 

Im going to update Otaku in my hoot repo in a sec but the new search path is 
`plugin://plugin.video.otaku/search_results/?query=`

Give that a try and see if that works.
This is all thanks to @Gujal00

**Comment by meesterexx** [comment]
That worked perfectly, thanks! And thank you @Gujal00 for the quick turn around on the fix!
