### ISSUE TITLE
New FanArt selector fails in Anilist User Account folders

### ISSUE THREAD

**Issue by MightyMase04** [Goldenfreddy0703/Otaku#301]
The new fan art selector works in widgets pulling straight from AniList, like all time trending. 

But when I try any show from my Current watchlist (or any other user folder, like planning) folder from Anilist, (Oshi no Ko S2 for example), it errors out. Even for shows that worked in other widgets/folders. 

Temporary workaround:

From context menu, 
1. Select get watch order
2. Re-enter context menu
3. Select Fanart as normal

**Comment by joezito129** [comment]
lol @Goldenfreddy0703 you forgot that i got rid of the kitsu_id in my urls you need to add it as an expected value from the payload

**Comment by Goldenfreddy0703** [comment]
Ahh your right. Will look into it and add those urls as well, thank you

**Comment by Goldenfreddy0703** [comment]
Hey so good news, looks like Joezito added the kitsu_id to Otaku so huge thanks to @joezito129. A release will be out in a min so feel free to give it a test and we should be able to close this issue now. 

If you run into problems related to this issue, please feel free to reply and we will open this issue back up.

**Comment by MightyMase04** [comment]
Hey! I appreciate the work y'all do!

The menu functionality is indeed restored in these sections. However, it's
looking like the change isn't actually being made when selecting fanart
from the kitsu_id dependant menus

It works as-expected in the other menus, as tested before. But in the ID
menus, after selecting a new fanart piece, I suspect one of two things is
happening:

1. The menu is entirely ineffective, or not applying changes properly in
Kitsu_ID sections, or,

2. A bug is causing it to reset to default/always apply the Random selection

I have tested this repeatedly across today and yesterday. Neither
refreshing/restarting Kodi or restarting my device fixes the issue.

The issue is *not* present in public folders like "All Time Trending." In
those menus, the change is applied instantly.

**Comment by Goldenfreddy0703** [comment]
Oh I might have forgotten to say but rebuild database and try it again and see if issue is still the same.

**Comment by joezito129** [comment]
i noticed you missed a lot of code that needs to be added/changed in the Anilist.py file
1. the fanart is always set to random
2. you need to add the unique ids

**Comment by joezito129** [comment]
I dont believe any of this data is being stored in the database so no need to rebuild database

**Comment by Goldenfreddy0703** [comment]
> i noticed you missed a lot of code that needs to be added/changed in the Anilist.py file
> 1. the fanart is always set to random
> 2. you need to add the unique ids

Oh I thought you added that part when you added the kitsu_id, my bad, will go ahead and add that tonight, thank you
