### ISSUE TITLE
When using auto play in Bleach Thousand Year Blood War Part 2 it Plays jujutsu Kaisen

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku#303]

**Comment by GitHubSand** [comment]
Is there a way to have a show stay in the torrent it's streaming from eg. Complete naruto 1-220

**Comment by Goldenfreddy0703** [comment]
Yes by having your playback set to autoplay and then on the episode utilize the select source context menu and pick the batch steam and on the next episode, it will play that same stream.
