### ISSUE TITLE
A problem with one of the naruto movies.

### ISSUE THREAD

**Issue by Adu185** [Goldenfreddy0703/Otaku#304]
Naruto the last movie it replaced by the legend of the stone of gelel movie and the legend of the stone of gelel doesn't exist.

**Comment by Goldenfreddy0703** [comment]
Hey so im kinda confused about your issue:
With Otaku, we use anilist as our database so its possible that anilist eaither has wrong data or its split or something. 

On Anilist, here are the movie titles i found
- [Naruto the Movie: Legend of the Stone of Gelel ](https://anilist.co/anime/936/NARUTO-Dai-Gekitotsu-Maboroshi-no-Chitei-Iseki-Dattebayo)
- [The Last: Naruto the Movie ](https://anilist.co/anime/16870/THE-LAST-NARUTO-THE-MOVIE)

**Comment by Goldenfreddy0703** [comment]
Hey so its been about 3 weeks sense you made this issues, im gonna go ahead and close this but if issues still persist, we will open this back up.

**Comment by Adu185** [comment]
Hey, sorry I didn't think you would have messaged back, but I still have the same problem. However, there is another movie that has the same problem: Dragon Ball Battle of Gods is not available to watch. Also, the two Quintessential Quintuplets specials don't seem to work like the one from last year and the recent one. Sorry to bother you.
