### ISSUE TITLE
Local scraper does not work correctly, my files are not played

### ISSUE THREAD

**Issue by jonathanluepfert** [Goldenfreddy0703/Otaku#305]
The files on my computer are found by the scraper but they show a wrong file size and do not play correctly. I get the error message "'NoneType' Object is not subscriptable".
The Kodi log shows this error message;

Request-Error: ('URLError' object has no attribute 'read') => C:\Users\Jonathan\Anime\[HorribleSubs]%20Polar%20Bear%20Cafe%20[1080p]

**Comment by jonathanluepfert** [comment]
Sure, here is the file: https://drive.google.com/file/d/1HOSJHRDUTd7J4yO9YkztRhvJ2fZx_g7L/view?usp=sharing
the file path is this: "C:\Users\Jonathan\Anime\[HorribleSubs] Polar Bear Cafe [1080p]\[HorribleSubs] Polar Bear Cafe - 01 [1080p].mkv"
and it's the first episode of the Anime "Polar Bear Cafe".

I'm keineahnungking on Discord, if you need more info about this, you can contact me on there.

**Comment by joezito129** [comment]
why is it url encoding the filename?

**Comment by joezito129** [comment]
never mind i see what the problem was. the title has "/" and it thinks its another directory

**Comment by jonathanluepfert** [comment]
No it is in another directory, but GoldenFreddy fixed the scraper to scrape subdirectories

**Comment by Goldenfreddy0703** [comment]
Oh @joezito129 sense your back, I made some changes on localfiles.py in the main branch. Check then out and see if you would like to add them to you lr version

**Comment by joezito129** [comment]
because of the way os.path.join works it thought there was another directory because "/" was in the title ([HorribleSubs] Polar Bear Cafe [1080p]\[HorribleSubs] Polar Bear Cafe - 01 [1080p].mkv 

The character needed to be escaped which @Goldenfreddy0703 already fixed by adding f.lstrip('/\\') before joining the paths

and yes already fixed it on my version
