### ISSUE TITLE
Source select is not playing selected sources

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku#306]

**Comment by Goldenfreddy0703** [comment]
Hey there, when you say that Source select is no playing selected sources, what type of sources are you trying to play? Are they embeds, torrents, local files, cloud files? Also are you getting any errors and can you show me a log if you are. 
Thanks

**Comment by Goldenfreddy0703** [comment]
Hey so i think i was able to resolve the issue, apparently when when i coded the Last Played Feature for select source, i forgot to add something that made it not play the selected source, see if this fixes your issue. 

Im going to go ahead and close this but if issues persist, please message and we will look further into this.
Thank you
