### ISSUE TITLE
No “Favorites” category shows for me.

### ISSUE THREAD

**Issue by Bucchiac** [Goldenfreddy0703/Otaku#308]
No matter how many times I add/remove/re-add a series to favorites, there isn’t actually anywhere to view my favorites. It used to be there, but it vanished some time ago. Any idea why this would be?

**Comment by Goldenfreddy0703** [comment]
Im not sure unfortunately but Otaku does not have a favorites category, the only favorites I can think of is the kodi global favorites which is located on your kodi homescreen that should be a star icon.
