### ISSUE TITLE
Bleach: Thousand-Year Blood War Error

### ISSUE THREAD

**Issue by ahmedashed** [Goldenfreddy0703/Otaku#31]
Hi everyone, thank you again for reviving this anime addon as to be honest all the normal addons don't cater for anime. I have come across this weirdly specific bug.

Issue description
Accessing Bleach Thousand Year Blood War creates an error in Otaku, it won't even load up the episodes. However the 'old' bleach title still works just does not have the new episodes being released, so I cannot work around that way.

Steps to reproduce the issue

1. Open Otaku
2. Search - Bleach
3. Select Bleach:Thousand-Year Blood War
4. Otaku Error

1.Open Otaku
2. Airing Anime
3. Select Bleach:Thousand-Year Blood War
4. Otaku Error

What's the expected result?

To load the episodes being released

What's the actual result?

Otaku error - will not even open episodes

Additional details / screenshot

I have cleared cache, local torrent cache and rebuilt database

Every other anime is working fine, that's why it makes me think it could be something specific with the new Bleach, I am happy to try provide logs if needed but I wonder if anyone else has experienced or recreated the bug? Thanks.

![IMG20221017102951](https://user-images.githubusercontent.com/63984654/196142626-db559a48-d487-4f45-8268-27bc74aff806.jpg)

**Comment by Goldenfreddy0703** [comment]
You do realize that anime has not come out right. That anime is coming out somewhere in November which is why there is no episode meta for it yet.

**Comment by icpryde** [comment]
@Goldenfreddy0703 bleach blood war already started episode 2 comes out today and it started last week

**Comment by Goldenfreddy0703** [comment]
Oh when i saw the date 11/10/2022, I thought that's when production starts. I may take a look more into that. Thank you

**Comment by ahmedashed** [comment]
> Oh when i saw the date 11/10/2022, I thought that's when production starts. I may take a look more into that. Thank you

Sorry for the confusion, I am in the UK so the dates are DD/MM/YYY

**Comment by Goldenfreddy0703** [comment]
> Sorry for the confusion, I am in the UK so the dates are DD/MM/YYYY

Ohhhh ok that makes sense

**Comment by Gujal00** [comment]
![screenshot00000](https://user-images.githubusercontent.com/17394059/196342427-7892a63c-1d2b-4eb0-9185-9020177f0df2.png)
