### ISSUE TITLE
Error trying to open a series from my SIMKL list.

### ISSUE THREAD

**Issue by Hemicrusher** [Goldenfreddy0703/Otaku#310]
When trying to open a series in my SIMKL list, Otaku throws up an error. This started happening with the last update. So, I uninstalled Otaku completely and reinstalled, but it did not fix the error.

In the log file below,  I see that Anilist is listed, yet I do not have Anilist enabled in Otaku.

[Kodi Log File](https://paste.kodi.tv/waneyeyazo)

I am running Kodi 21 stable, on a ONN 4K Google TV

Thank you!

**Comment by Goldenfreddy0703** [comment]
Did you also clear cache and rebuild database as well?

**Comment by Hemicrusher** [comment]
> Did you also clear cache and rebuild database as well?

Yes I did.

Thanks!

**Comment by Hemicrusher** [comment]
> Did you also clear cache and rebuild database as well?

I ended up uninstalling again, clearing cache and rebuilding the database and it seems to be working.

So, I'll close this.

Thanks!
