### ISSUE TITLE
Feature Request: Add a min resolution for source filters

### ISSUE THREAD

**Issue by karlosmexicanos** [Goldenfreddy0703/Otaku#312]
Hi there!

I truly appreciate the effort you've put into this. Could you please add a minimum resolution filter to the sort and filter settings? For instance, being able to set both a max resolution (e.g., 4K) and a min resolution (e.g., 1080p) would be very helpful. This would save time by automatically excluding 720p and SD sources that aren't needed.

**Comment by Goldenfreddy0703** [comment]
Hey so good news, I added min resolution but for some odd reason, this was hard to add even tho i just had to filter out the resolutions and all. I made this harder for myself lol. 

Anyway im gonna go ahead and close this but if you have any issues related to this, Please feel free to reply and we will look further into it. 
Thank you
