### ISSUE TITLE
New Feature: Random Shows and Movies Folders

### ISSUE THREAD

**Issue by karlosmexicanos** [Goldenfreddy0703/Otaku#316]
Hello again,

I hope you're doing well. I was wondering if it would be possible to add a feature that displays a random selection of movies and anime shows. This would be a great way to keep the content feeling fresh, as every time you load Kodi, you'd be greeted with new recommendations. I’ve attached some photos from Fen Lite as an example of what I have in mind. This could include random selections from different genres, popular titles, trending shows, and more

Thank you for considering this suggestion!
![20240810_140233](https://github.com/user-attachments/assets/86ebbae4-1996-490c-8e93-6ab3a9a7184a)
![20240810_140238](https://github.com/user-attachments/assets/1a2f8508-a041-4149-941e-d29a8b09ac02)
![20240810_140245](https://github.com/user-attachments/assets/6dd6dd55-3d02-4c84-bd37-9488a699b628)

**Comment by Goldenfreddy0703** [comment]
Hey so unfortunately Anilist does not offer random shows or movies so we are kinda unable to provide random shows and movies folders. This is also one of the reasons why there are so many menus on Otaku where the user to customize, enable or disable, etc.
