### ISSUE TITLE
Embeds identified but don't show up on the selection screen

### ISSUE THREAD

**Issue by islandtj** [Goldenfreddy0703/Otaku#317]
Hello, while Otaku is searching for links, it identifies 7 embeds; however, when it turns to the selection screen, nothing appears. I have other instances of Kodi and Otaku on additional TVs in my home that will show the embeds on the selection screen, just not on the TV where I am having this issue.

I've cleared cache, torrent cache, rebuild database, wiped data, and even reinstalled Otaku but the identified embeds still don't show.

Note, it did work in the past but I recently reinstalled Kodi and Otaku, and that is when the issue started.

Has anyone experienced this before and resolved?
![1000006894](https://github.com/user-attachments/assets/61759060-09b1-49bf-b527-312ca4af4869)
![1000006893](https://github.com/user-attachments/assets/89683e31-a50f-4259-97fa-1edb7efe590f)
[kodi log.txt](https://github.com/user-attachments/files/16570299/kodi.log.txt)

**Comment by Goldenfreddy0703** [comment]
Hey so we recently added a max and min resolution to the addon, check and see if it has anything todo with that. If not then it's possible that you have the playback stuff set to find dubs maybe.

**Comment by islandtj** [comment]
Mahalo @Goldenfreddy0703 , you were spot on on the resolution settings. I changed the settings now the links show.  I appreciate your guidance,  thanks!

**Comment by islandtj** [comment]
Issue resolved!
