### ISSUE TITLE
Airing Anime is exactly the same as Popular this season

### ISSUE THREAD

**Issue by potatowe** [Goldenfreddy0703/Otaku#318]
Title is self-explanatory. Seems redundant to have two of the same category; maybe it could be 'New Episodes' instead?

**Comment by Goldenfreddy0703** [comment]
Hey there, some menus may look the same but they are actually different when you keep scrolling, its just a little bit out of order. Technically they are the same but one of the menus just has the Airing Status set to airing which is why its a little bit different when scrolling.
