### ISSUE TITLE
Next up in MAL

### ISSUE THREAD

**Issue by dpetka2001** [Goldenfreddy0703/Otaku#32]
So I noticed that when using MAL "Next Up" it shows all animes you're watching correctly updated for the episodes that you've already watched. But when using Anilist "Next Up" it shows only the animes that have already aired episodes if you haven't watched them already. If you watch the episodes then the anime disappears from "Next Up" until the next episode is aired again (which is the correct behavior in my opinion). Could something be done, so that MAL "Next up" behaves the same as Anilist "Next Up"?

**Comment by Goldenfreddy0703** [comment]
I believe the reason why they are not behaving the same way is cause you have an update watchlist option where you can only select one watchlist to update from. In the future we are gonna have a way where you can update with all watchlist instead of one.

**Comment by dpetka2001** [comment]
I for sure don't understand as much as you do, but I have the setting to update the MAL list already. The episodes get updated correctly. It just doesn't hide the anime that don't have any more airing episodes. Anilist hides the anime until there is an airing episode again. My assumption is it has to do something with the way the UI is set up in Otaku for the MAL "Next up". It doesn't hide animes that you have already watched the airing episodes. Whereas Anilist "Next up" hides the anime if there are no more airing episodes left. But of course I could be wrong as I don't understand how you program the addon.

**Comment by Goldenfreddy0703** [comment]
Tbh i may not understand either so let me get @Gujal00 to help answer your question.

**Comment by Gujal00** [comment]
I dont use MAL so didnt notice this, I use Anilist and it works correctly there. Will see if it is possible to get MAL Next UP behave similarly

**Comment by Gujal00** [comment]
@dpetka2001 Unfortunately this is not possible in MAL API, so can't be done
Reference `https://myanimelist.net/forum/?topicid=2023844`

**Comment by dpetka2001** [comment]
Thank you very much for your effort. I will switch to Anilist so I don't really mind anyway. Closing since this is resolved.
