### ISSUE TITLE
Feature request - Ability to view log file from tools menu

### ISSUE THREAD

**Issue by djarumlights** [Goldenfreddy0703/Otaku#321]
Hello! 

I use Otaku on an Android TV-based projector. Would love the ability to view errors from the Tools menu, as navigating to where the log file is stored and viewing using conventional methods is fairly painful and obtuse.

Thanks for the continuous improvement!

**Comment by Goldenfreddy0703** [comment]
Hey so it would be a good idea but there are other addons out there that we can view the log like kodi log viewer and kodi log uploader where you can upload your log file online so it's easier to identify the error. Hope this helps.

**Comment by djarumlights** [comment]
Ahhhh okay. My overall experience with Kodi is limited, as I literally set it up on this projector just for your add-on and a couple others. I'll look into those. ^_^

**Comment by Goldenfreddy0703** [comment]
Sure and if you have any trouble, download the kodi log uploaded and upload your log and send me the url and I should be able to look into it and all. Thanks
