### ISSUE TITLE
Default subtitle options

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#325]
Is there a default subtitle options within otaku? It would be great if we could set it so that it does not go straight to "signs and songs."

 
<img width="2560" alt="Screen Shot 2024-08-20 at 10 28 12 AM-min" src="https://github.com/user-attachments/assets/48d479d9-f418-4569-b2af-2410426cc9f5">

**Comment by Goldenfreddy0703** [comment]
Unfortunately no, we looked into that but could not find a way to code it to avoid signs and songs.

**Comment by Liquidrag** [comment]
Damn that’s too bad. Thanks for trying though.
