### ISSUE TITLE
Shows like Made in Abyss season 2 now not loading episode lists

### ISSUE THREAD

**Issue by icpryde** [Goldenfreddy0703/Otaku#33]
Issue in the latest version 0.2.24 depending the anime i try to click to pull up the season episode list some will show up but now others like made in abyss season 2, MHA season 6, Mob Psycho season 3 and some others are now not pulling some of the meta data but now they won't load the episode list at all. 

Made In Abyss season 2 was working in the previous version .23 as i was using it yesterday.

Heres the error i'm receiving. 

![12C6B5F2-B320-4F66-913C-2258867CC514](https://user-images.githubusercontent.com/29389746/196343749-ba810140-cc71-4bcb-85cd-1b454230074b.jpg)

**Comment by icpryde** [comment]
noticed also just when browsing shows the meta data for shows like made in abyss don't show up anymore (they did on .23) 

![IMG_6767](https://user-images.githubusercontent.com/29389746/196345108-dce44c71-0819-4d64-bd69-0773d075fa0c.jpeg)

heres what it should look like when the data is pulled:

![IMG_6768](https://user-images.githubusercontent.com/29389746/196345157-7bf88cde-a520-4cc0-9228-04f99dfb5c60.jpeg)

**Comment by icpryde** [comment]
Still not working after the .25 update 

log: https://paste.kodi.tv/vuwisuqeti

**Comment by Gujal00** [comment]
Please close the issue If it is working with the latest release

**Comment by icpryde** [comment]
yup all is working now!
