### ISSUE TITLE
[BUG] Random popup error from otaku addon

### ISSUE THREAD

**Issue by IamJanarthan** [Goldenfreddy0703/Otaku#331]
I get addon error popups randomly (at startups mostly)
[koddi.log](https://github.com/user-attachments/files/16961844/koddi.log)

> 
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: context.otaku v0.0.15 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: plugin.video.otaku v0.5.27 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: repository.otaku v1.0 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.otaku.mappings v24.09.08 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.otaku.themepak v0.0.13 installed
                       File "C:\Users\weebg\AppData\Roaming\Kodi\addons\plugin.video.otaku\service.py", line 8, in <module>
                       File "C:\Users\weebg\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\maintenance.py", line 104, in run_maintenance
                       File "C:\Users\weebg\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\maintenance.py", line 57, in sync_watchlist
                       File "C:\Users\weebg\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\AniList.py", line 419, in save_completed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: context.otaku v0.0.15 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: plugin.video.otaku v0.5.27 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: repository.otaku v1.0 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.otaku.mappings v24.09.08 installed
    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.otaku.themepak v0.0.13 installed
    warning <general>: CPythonInvoker(187, C:\Users\weebg\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py): the python script "C:\Users\weebg\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::DialogProgress,class XBMCAddon::xbmc::PlayList
    info <general>: CServiceAddonManager: failed to stop context.otaku (may have ended)
    info <general>: CServiceAddonManager: failed to stop plugin.video.otaku (may have ended)

-->Both Otaku addon and kodi are in their latest versions available
-->I have two kodi setups one on my laptop and one one my desktop both linked with anilist and both use artic fuse skin, but only the 
     desktop one throws this error. 
-->I don't use embeds i use RD
-->As far as i observed, aside from this error, everything works from the addon till now, but the pop is really annoying
FYI: I set anilist watchlists as widget in my desktop setup but no widgets in my laptop setup.

**Comment by joezito129** [comment]
I updated the Anilist.py please let me know if this fixed your issue.

**Comment by Goldenfreddy0703** [comment]
Thank you @joezito129 for providing a fix I forgot that Anilist will be down for maintenance today.

**Comment by IamJanarthan** [comment]
That fixed the issue, Thank you
