### ISSUE TITLE
[Bug] Incorrect root Media View for Next Up list

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#337]
This issue had been present for a long time, I just didn't felt like creating an issue for it. I thought someone else would also noticed this by now and report it, but I guess none has.

So, the Next Up list is an mixed **Episode List** similar to Fen's "Next Episodes" or Tmdb's helper "your next episodes" list. however as you'll see in the screenshot below, it's set as that Menu list is a **tvshows list** So, what's happening is that it's making all of the thumbs as poster instead of landscape. 

So, for example if I'd change the views to landscape for that menu list and lock that view in as Nimbus skin does. When I go back to let's say, any only my TV Shows list in FEN Light they would be in Landscape mode as well since changing the media views in the Otaku's Next Up being set as a "tvshows" list triggers the change for every other addon. 

So, the correct thing would be making the Next Up list as an "Episode list" so the landscape mode is correctly set for that list same as every other episode or mixed episode list. I'll share two additional screenshots showing that my set view for tv show episodes and mixed episode lists is already set as Landscape. Just the Next Up list being the issue since it's being displayed as a "tvshows list".

**Next Up list displayed as a tvshows list, when it's a mixed-episodes list**
![image](https://github.com/user-attachments/assets/836a403b-d37f-4f7c-a5aa-6a355ad8578b)

**Inside the TV Show itself, as you see that is correct set as an Episode list, so displaying the thumbs correctly.**
![image](https://github.com/user-attachments/assets/244f80f7-968a-4428-8bf5-c4caa48ac463)

**This is the Next Episodes list in Fen Light, again displaying the thumbs correctly since it's a mixed episode list plus as you see media view is set for episodes. Next Up list in Otaku is the same as this list which is a mixed episode list.**
![image](https://github.com/user-attachments/assets/4a6de2c2-f6ce-4dff-b247-b2ae8d60dfba)

Hopefully, this can be easily corrected so that way Episode thumbs in the Next Up display as they should in Landscape mode instead of being displayed in Poster mode since the list is being displayed in tvshow mode instead of episodes.

**Comment by Gujal00** [comment]
There is no episode thumb available in next episodes section, only show posters hence it is is setup as tvshows to show the posters, What you are showing is specific to the skin you are using as it is probably pulling the thumb from tmdb.
In the default estuary skin, it shows the tvshow posters for the next up section and not doing its own additional pull from tmdb using the tmdbhelper addon

**Comment by jewbmx** [comment]
If i recall someone had a similar type of issue with my addon so i just threw in a setting for them users to toggle on that way their suggestion wasn't forced on everyone and i could keep enjoying it the way i wanted lol.
This might be fixed the same way if ya wanna code it in for the setView type of spot this user is speaking of.
I think yall did something similar too not long ago with the next option and widgets or some shit.
