### ISSUE TITLE
Incorrect Metadata for the new bleach season

### ISSUE THREAD

**Issue by IamJanarthan** [Goldenfreddy0703/Otaku#339]
Tried to watch new season of bleach and found this,
Bleach latest season showing fairy tail anime's meta data

![image](https://github.com/user-attachments/assets/ef61d14d-3492-42d6-a436-1c7ed9e39125)
![image](https://github.com/user-attachments/assets/74be0883-ba71-4fcb-af24-ba9b1efe57b7)

**Comment by Gujal00** [comment]
no mapping available in the db for this show and the trakt search for this returns `Fairy Tail:100 year quest` as the show id, so wrong meta

**Comment by Gujal00** [comment]
should be fixed in the latest released update
