### ISSUE TITLE
Am I the only one not getting the ver.0.5.29 update?

### ISSUE THREAD

**Issue by Sickhead01** [Goldenfreddy0703/Otaku#341]
I checked github a couple mins after the most recent update dropped yesterday. I've gone into Kodi multiple times since and Otaku hasn't updated, not automatically or when i manually press "Check for updates". Is this only a problem on my end or are there others?

**Comment by Goldenfreddy0703** [comment]
Could have been a repo issue of a Auto-update could have been turned off. Try reinstalling my repo and that could probably fix your issue.

**Comment by Sickhead01** [comment]
Ah i see the problem. I originally installed it from the Hooty Repository. I'm guessing that's not being used anymore?

**Comment by Goldenfreddy0703** [comment]
Technically it is still being used but it's used for all addons I need for my builds. Use Otaku repo if you don't want modified addons from hooty.

**Comment by Sickhead01** [comment]
I installed the otaku repo and uninstalled hooty and the otaku from the otaku repo version is 0.5.29
