### ISSUE TITLE
Artwork for MF Ghost is wrong

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#347]
IDK if it can be fixed but the artwork for MF Ghost is wrong, poster is correct though. 
<img width="1103" alt="Screen Shot 2024-10-17 at 7 56 31 AM" src="https://github.com/user-attachments/assets/87419392-9585-4b55-9c73-835cd5b8923c">

**Comment by Gujal00** [comment]
If the poster is correct, what artwork is incorrect?

**Comment by Goldenfreddy0703** [comment]
Looks to be a fanart issue I believe. On my version or on fanart tv, this should be the correct fanart.  
![image](https://github.com/user-attachments/assets/40e562af-18ef-4975-9f4b-d0af205508e4)

**Comment by Liquidrag** [comment]
Yes its the fanart for each episode season 2

**Comment by Gujal00** [comment]
Episode thumbs for current shows is usually not available on simkl and nothing can be done about that

**Comment by Liquidrag** [comment]
Ok thanks.
