### ISSUE TITLE
Inputstream adaptive

### ISSUE THREAD

**Issue by epidoma** [Goldenfreddy0703/Otaku#349]
Hello
Everytime i want to play something without realdebrid account addon asks for inputstream adaptive.
and every time i select no. and then error pops up and i select ok and anime plays perfectly.
So i have been doing this select NO and then OK game for a very long time.
is there a way to remove inputstream adapative dependency from this addon because i definitely dont need it.
I tried removing it from player.py but i still get popups.
Im not that good in coding but any help on where to look to remove it please ?

thank you,
love the addon

**Comment by Goldenfreddy0703** [comment]
Hey so usually input stream adaptive is very important cause it mostly helps with embeds for playback. I don't see why you would not want to install it but maybe in the future we could make an option to disable the pop-up if you like.

**Comment by epidoma** [comment]
Yes, option to disable it would be amaizing. 
Thank you for considering it.

**Comment by joezito129** [comment]
go to your program addons "Inputstream Helper" settings and disable InputStream Helper
![inputstream](https://github.com/user-attachments/assets/5faae073-c337-4aec-93dc-e8d517334b4b)

**Comment by epidoma** [comment]
@joezito129 
Oh so inputstream helper is the one calling for inputstream adaptive. Your solution worked and I no longer have a popups. 
Thanks
