### ISSUE TITLE
One piece scraping inconsistencies

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku#351]
Anime time 1-1071 doesn't play and when scraping sometimes the wrong episodes show up even though there is a torrent for it

**Comment by Goldenfreddy0703** [comment]
When it comes to one piece, scrapping can be weird sometimes and our scrapping is kinda bugged, you may either want to use embeds or try our new Otaku Testing version sense it's alot better. 

https://github.com/Goldenfreddy0703/repository.otaku.testing
