### ISSUE TITLE
Episode count not showing in sublabel

### ISSUE THREAD

**Issue by Rinicko100** [Goldenfreddy0703/Otaku#358]
Hello, good day

The episode count for anime seasons don't show up in Arctic Fuse 2 sublabels, the code used to generate the sublabels should bring up the number episode count, but it seems there may be an issue and it uses a fallback condition instead. This is the code used for the sublabel
<value condition="[String.IsEqual(ListItem.DBType,tvshow) | String.IsEqual(ListItem.DBType,season)] + !String.IsEmpty(ListItem.Property(totalepisodes)) + !String.IsEmpty(ListItem.Property(watchedepisodes))">

Could you check the discussion to see if you can spot the issue..  I don't really have the technical knowledge to know what causes it, to phrase the question properly https://github.com/jurialmunkey/skin.arctic.fuse.2/discussions/241#discussioncomment-11082707

![Kodi_20241101_113849.png](https://github.com/user-attachments/assets/3c73b988-86e4-442f-be26-3087a8ebf1d4)

![Kodi_20241101_113214.png](https://github.com/user-attachments/assets/84f27543-35fb-4d13-93c5-0f3f5bc824c2)

The episode count shows up with TMDB helper, but not Otaku

**Comment by Goldenfreddy0703** [comment]
We never really knew how to add episode count for skins. If we could then we would try to add episode count to Otaku.

**Comment by Rinicko100** [comment]
> We never really knew how to add episode count for skins. If we could then we would try to add episode count to Otaku. 

ohh I see... no worries then, just thought I'd check if there could be something wrong somewhere in the code... I'll close this

**Comment by Rinicko100** [comment]
> > We never really knew how to add episode count for skins. If we could then we would try to add episode count to Otaku. 
> 
> ohh I see... no worries then, just thought I'd check if there could be something wrong somewhere in the code... I'll close this 

Thanks a lot for your response... very much appreciated 🙏🙏
