### ISSUE TITLE
Real Debrid cloud storage scraping

### ISSUE THREAD

**Issue by dpetka2001** [Goldenfreddy0703/Otaku#36]
Hey guys, I have a problem and would like to know if anybody else has also encountered it. It looks like when scraping for sources, Otaku seems to not be able to scrape the files that I have on my cloud storage (I'm using Real Debrid). I have authorized Real Debrid and also increased the priority to search through my cloud storage first without any luck. Is anyone else experiencing the same problem?

**Comment by Goldenfreddy0703** [comment]
Yeah cloudscraping is kinda broken at the moment cause we thought it was not a problem nor it was needed, I'm sure in the future, we will fix that tho.

**Comment by dpetka2001** [comment]
Ok so I'm not the only one with a problem. Thought it had something to do with my account. By the way it's also not working in Seren and Fen but it's working fine in Ezra. So whoever might want to fix it in the future, might want to take a look at Ezra. Thank you for your response. Is it okay if I leave the issue open until it's fixed in the future?

**Comment by Goldenfreddy0703** [comment]
Oh sure. I don't mind keeping this issue open. Hopefully it can be resolved in the future.

**Comment by Gujal00** [comment]
Unfortunately I dont have Real-debrid premium to test this. Hopefully one of the other devs with Realdebrid account can take a look

**Comment by dpetka2001** [comment]
Hey @Gujal00 I saw that you added support for Debrid Link. I guess that's what you're using? Could you share your experience? Does cloud storage scraping work with Otaku? I compared the prices with Real Debrid and they're the same, so I'm thinking of switching to their service if it's the same as Real Debrid (after my current subscription expires).

**Comment by Gujal00** [comment]
I have not coded cloud scraping for Debrid-Link. Have to figure out how it is expected to work and then code it,

**Comment by joezito129** [comment]
@dpetka2001 try changing line 44 of debrid_cloadfiles.py to
if source_utils.is_file_ext_valid(filename) and episode not in filename:

Let me know if you are able to find cloudfiles after this change.

**Comment by dpetka2001** [comment]
I did the change and reset cache and local cache but i'm not sure if it works. All the animes I'm currently watching have propagated episodes in Real Debrid. All entries say `Debrid: Real Debrid`. In the old kaito plugin it used to say `Debrid: Cached` to differentiate scraping between local cloud and other Real Debrid servers. I think it might work but I'm not 100% sure.

**Comment by dpetka2001** [comment]
So I don't know what exactly happened. But on my Firestick Kodi installation Otaku just now was able to scrape the file I had on my cloud storage without making that proposed change in line 44 in the above post. Is it dependent on filename parsing maybe? I'm not exactly sure how this happened. Is it okay if I leave this issue open a little while more and I monitor the behavior of the addon? And if there aren't any more problems I will close it or come back with new information hopefully.

**Comment by Goldenfreddy0703** [comment]
Hey sure, we will leave this issue open until it gets resolved soon.

**Comment by joezito129** [comment]
so I think it has something to do with the client.request on line 37. I changed it to use the request module instead and the cloud scrapping seams to be working fine for me now.

**Comment by joezito129** [comment]
Change line 37 to:
resp = client.request('https://armkai.vercel.app/api/fuzzypacks', params={"dict": filenames_query, "match": query})

**Comment by Gujal00** [comment]
@joezito129 
Yes, that is the correct usage as currently, it wont quote the parameters and that could cause problems. By passing a dict, it will be correctly urlencoded. Thanks for spotting

**Comment by dpetka2001** [comment]
I'm fairly certain with the last change in line 37(line 44 change is not needed I believe, but that is up to you to decide as I don't know programming, just that it already managed to scrape one file without the change in line 44 before the change in line 37) it scrapes every single file that I tested on my cloud storage. Thank you all for your help. Keep doing an awesome job. I believe it's okay to close the issue now?
