### ISSUE TITLE
(FEATURE REQUEST) Multi account Watchlist updating/syncing.

### ISSUE THREAD

**Issue by Hemicrusher** [Goldenfreddy0703/Otaku#365]
Anilist has been down a lot lately... Yesterday they had a DDOS attack. Anyhow, I use Anilist as my main watchlist in Otaku, but also keep track on MAL website just so I have a backup. It would be cool if you could sync both Anilist and MAL using the watchlist feature in Otaku.

Thanks!

**Comment by Goldenfreddy0703** [comment]
We have tried to make Watchlist utilize multiple accounts but we could not figure that out sadly, You may want to give Mal Sync extension a try cause that will sync your watchlist. 

https://malsync.moe/
