### ISSUE TITLE
Otaku errors out opening shows in any of my MAL lists.

### ISSUE THREAD

**Issue by Hemicrusher** [Goldenfreddy0703/Otaku#367]
I went to watch a show and had Anilist as my watchlist, and MAL was disabled, but I got errors, so I figured Anilist was having issues again with their API, so I disabled Anilist, and enabled MAL, and set MAL as the watchlist. I then shut down and restarted Otaku. I was able to play one episode from my list, but when I went to play another episode from a different series... Otaku is displaying errors. I cant open any animes in of my lists.

I've cleared cache etc and I am still unable to open any shows in any of my MAL lists, yet can see them.

Update....swicthing back to Anilist as the watchlist is now causing the same problem, but even worse as I can't even get into any list. Basically, Otaku is no longer working.

Update #2 - I switched back to Anilist, and now just starting Otaku, I get an error.... [HERE](https://pastebin.com/6ZaWg3QH)

I am on the latest release of Otaku 0..5.31 and running it in Kodi 21 stable.

[Here is the Kodi Log File](https://pastebin.com/U36t2B49)

**Comment by Goldenfreddy0703** [comment]
Hey so anilist may still have api errors and the old Otaku still uses anilist as it's database. Try out the new Otaku for now sense it supports the Mal database and it doesn't go down like anilist.

https://github.com/Goldenfreddy0703/Otaku-Testing

Hope this helps.

**Comment by Hemicrusher** [comment]
> Hey so anilist may still have api errors and the old Otaku still uses anilist as it's database. Try out the new Otaku for now sense it supports the Mal database and it doesn't go down like anilist.
> 
> https://github.com/Goldenfreddy0703/Otaku-Testing
> 
> Hope this helps.

Okay, that works! Is it cool if I submit bugs for the Otaku Testing?

One more question....I uninstalled Otaku before I installed Otaku Testing....can they both be installed at the same time without causing an issue?

Thanks for all your work!!!!!

**Comment by Goldenfreddy0703** [comment]
> Okay, that works! Is it cool if I submit bugs for the Otaku Testing?

You can yes in the Otaku Testing Github Repo

> One more question....I uninstalled Otaku before I installed Otaku Testing....can they both be installed at the same time without causing an issue?

They can but context menu may not work on the old version but im not too sure.
