### ISSUE TITLE
FEATURE REQUEST "Next Up" to behave like Seren's "Next Up" 

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#37]
Currently, in the "Next Up" section, my list of shows populates, and when I click on one, it plays that episode and then stops, unlike Seren's which plays on to the next episode in that show.

**Comment by icpryde** [comment]
![6DCDB72D-F876-40D3-B949-8283797B3A53](https://user-images.githubusercontent.com/29389746/200347495-40a52fa7-6f9c-4d78-a162-bbc7c7e6553a.jpeg)

this is already a feature that exists seems to work just fine unless you’re somehow accessing weird shows with no metadata .

**Comment by Liquidrag** [comment]
Yes I just tested it again and it works. What doesn't is if I point my widget to "next up" it stops after an episode.

**Comment by Gujal00** [comment]
Widget issue. Works correctly within the addon
Related to #29
