### ISSUE TITLE
Real Debrid not working correctly 

### ISSUE THREAD

**Issue by dubeyKartikay** [Goldenfreddy0703/Otaku#371]
Due to the recent changes in the real debrid api, /InstantAvailability api endpoint has been removed.
Fen light and Umbrella have come up with a workaround.
maybe otaku can implement the same workaround so that RD is not useless in this addon

**Comment by Goldenfreddy0703** [comment]
Hey so had to do a quick release so mess with the uncached sources toggle and the foreground toggle in rd in accounts category, I hope I fixed it but if not, will do a fix very soon. 

Thanks

**Comment by Gujal00** [comment]
@dubeyKartikay  @Hemicrusher 
Test with Otaku v0.5.35 released today and report back. Tested fine with AD and DL

**Comment by dubeyKartikay** [comment]
Works on Otaku testing and Otaku, tested RD today
