### ISSUE TITLE
Neither Real Debrid nor All Debrid working since the "RD fix" update

### ISSUE THREAD

**Issue by Sickhead01** [Goldenfreddy0703/Otaku#372]
I have both AD and RD enable and ever since the last update i'm only getting embedded links:
![PXL_20241127_152757224~2](https://github.com/user-attachments/assets/91809825-8516-4b7e-b79f-9da2c08ee6f7)
![PXL_20241127_152808936~2](https://github.com/user-attachments/assets/1226614c-4dfe-435a-b574-23519cf4bc56)
![PXL_20241127_152857694](https://github.com/user-attachments/assets/2c5f17d2-a0e5-48a9-8156-d70326e4a59e)

**Comment by Goldenfreddy0703** [comment]
Use Otaku Testing, it has the real debrid fix that should help. 

https://github.com/Goldenfreddy0703/Otaku-Testing

Btw when trying Otaku Testing, make sure to enable Scrape Uncached Sources in the scrapping settings.
