### ISSUE TITLE
Context menu not showing options

### ISSUE THREAD

**Issue by Duckonquack** [Goldenfreddy0703/Otaku#378]
When I use the context menu on a series I only have the default options, none of the otaku options like "Get Watch Order" or "Get Recommended"
I have them enabled in the options and have tried toggling them off and on again and switching skins
I see no errors in my log

![kodi_ZiiMsjKfA0](https://github.com/user-attachments/assets/9b9d51d3-dc67-4da0-b3b8-121bb7bd0043)
![kodi_xdXj8uHg40](https://github.com/user-attachments/assets/efe5f439-eddf-4c8a-95ed-d296e7d1d1fd)

It does work in otaku testing however so maybe it has something to do with anilist?

**Comment by Goldenfreddy0703** [comment]
Its possible that you accidentally have a version that previously worked with Otaku Testing and by changed, try reinstalling the Otaku Context menu by going to dependencies and hopefully that should work. Also restart your kodi.

**Comment by Duckonquack** [comment]
> Its possible that you accidentally have a version that previously worked with Otaku Testing and by changed, try reinstalling the Otaku Context menu by going to dependencies and hopefully that should work. Also restart your kodi.

That worked thank you

it said I had 1.0.2 but updated to 0.15

not sure if that makes sense but I’ll take it
