### ISSUE TITLE
FEATURE REQUEST add show/movie to anilist from context menu

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#38]
It would be convenient if we could just add a show/movie to our anilist list when browsing through the context menu.  I know currently, we can just add it to favorites but that doesn't update my anilist.

**Comment by Gujal00** [comment]
Added in latest release

**Comment by Liquidrag** [comment]
Works great thank you! Is there a way to add the option in the global context menu so it can be accessible in widgets?

**Comment by icpryde** [comment]
Yes please same request access to the context menu for widgets would be great

**Comment by Gujal00** [comment]
Global context menu not possible as it needs to be inside the addon to know where to add `Add to Watchlist` and `Remove from Watchlist` options
