### ISSUE TITLE
［Bug?］I can't turn off the subtitles.

### ISSUE THREAD

**Issue by tagjg** [Goldenfreddy0703/Otaku#380]
［Bug details］
I can't turn off the subtitles.

［What I did to remove the subtitles.］
I changed the add-on settings so that subtitles are not displayed.
![IMG_1435](https://github.com/user-attachments/assets/b26d9c91-51e7-4bd4-afc2-aee839716215)
I changed the subtitle settings in the Kodi app itself so that subtitles do not appear.
![IMG_1436](https://github.com/user-attachments/assets/608655ee-889f-4b7d-8eff-b0b7011bcf8c)

［What I want］
I want to keep the anime audio in Japanese but turn off the subtitles.

［Operating environment］
・iPad 9
・ios version:18.0
・kodi version:21.0

**Comment by Goldenfreddy0703** [comment]
Hey quick question, are you using embeds or debrid torrents? If you were using embeds, those subtitles are unfortunately embedded so you may want to use torrents if you have a debrid account.

**Comment by tagjg** [comment]
How can I tell if I'm using embeds or debrid torrents?

I don't know which one I'm using.

**Comment by Goldenfreddy0703** [comment]
Ahh than your using embeds than if you don't know what a debrid account or debrid torrents are. So unfortunately you can't really turn off subtitles for embeds.
