### ISSUE TITLE
Incorrect episodes for Legend of the galactic heroes

### ISSUE THREAD

**Issue by TaiDak** [Goldenfreddy0703/Otaku#40]
Instead of showing the correct episodes for Legend of galactic heroes die neue these serian, otaku shows the option to select seasons from the older 1988 ova

**Comment by TaiDak** [comment]
To your Eternity Season 2 (Fumetsu no Anata e) also gets wrong fanart, from some anime called Eternal Boys (Eikyou Shounen) and the info from season 1

**Comment by Gujal00** [comment]
Added a context menu option for you to enter the correct trakt slug manually when you encounter such issues
In case of Fumetsu no Anata e Season 2, trakt slug is `to-your-eternity` regardless of season.
and the slug for is The Legend of the Galactic Heroes: Die Neue These 2018 is `the-legend-of-the-galactic-heroes-die-neue-these`

**Comment by TaiDak** [comment]
So far it's working as expected.
