### ISSUE TITLE
Add tenshi.moe source

### ISSUE THREAD

**Issue by rollingmoai** [Goldenfreddy0703/Otaku#41]
https://tenshi.moe/

According to [the wiki](https://thewiki.moe/en/sourcing/streaming), it is listed as a tier 1 streaming source alongside with Animixplay:
> Contains the smallest library of all the sites but with the best quality for BD releases and good quality for seasonal content.

**Comment by Gujal00** [comment]
gogo nyaa and animix follow anime season cours so easy to search episode based on the episode number for split season. tenshi follows tmdb style of combined seasons so hard to match episodes for lot of split seasons

**Comment by Goldenfreddy0703** [comment]
Im going to close this cause @Gujal00 is right on this one.
