### ISSUE TITLE
no search results

### ISSUE THREAD

**Issue by unicornsandcandies** [Goldenfreddy0703/Otaku#42]
When I use search option, no matter what I search for, there are no results. 

Log: https://pastebin.com/raw/GVGiDV8A

**Comment by Gujal00** [comment]
looks like you are not sending any search term
`StartScript - calling plugin Otaku('plugin://plugin.video.otaku/search','108','','resume:false')`

If you are using as a skin widget, the path is wrong. Look at this issue for solution #3

**Comment by unicornsandcandies** [comment]
> looks like you are not sending any search term `StartScript - calling plugin Otaku('plugin://plugin.video.otaku/search','108','','resume:false')`
> 
> If you are using as a skin widget, the path is wrong. Look at this issue for solution #3

I'm using search directly in addon

**Comment by Gujal00** [comment]
` enable searching mature titles` is by default off, it should only be turned on when searching for specific anime such as `Redo of the Healer` and should be switched off otherwise

**Comment by joezito129** [comment]
it looks like when mature titles is enable it only shows mature titles

**Comment by Goldenfreddy0703** [comment]
Yes, we may either change `enable searching mature titles`  to  `enable searching mature titles only` or something like it so that it does not confuse the user.

**Comment by Goldenfreddy0703** [comment]
Hey so im going to go ahead and close this issue but we have an upcoming release very soon that will not confuse the user over the mature titles.
