### ISSUE TITLE
REQUEST option for manual file selection

### ISSUE THREAD

**Issue by TaiDak** [Goldenfreddy0703/Otaku#43]
If possible to have the seme feature as seren to manually select a file from a batch source.

**Comment by Goldenfreddy0703** [comment]
Possibly but we are working on a consistent api that will make Otaku very consistent with episode meta and help with artwork.

**Comment by icpryde** [comment]
isn't this already possible by having it set to manual instead of "auto select" and you can choose the source you want?

**Comment by Goldenfreddy0703** [comment]
> isn't this already possible by having it set to manual instead of "auto select" and you can choose the source you want?

Not really cause torrents have season batches where you can't really auto select, it just chooses it for you. We can probably make an option for that in the future but will probably take time.

**Comment by Goldenfreddy0703** [comment]
Hey @icpryde sorry to bother you but we have a setting called "Prioritize Batch Sources" where batch torrent files are always ontop. Would that resolve this issue or would you need to manually select the file when clicking on a batch source?

**Comment by Thor4201** [comment]
With the file selection already being partially incorporated for it, as seen with several series I believe all that'd be needed is the call function for it and a context menu on the source selection page to select and bring it up. I believe one show I was watching that the selection pop up displayed was s sword art online. I'll have a look myself to see if I can do something, it'd take some time for me as well

**Comment by Goldenfreddy0703** [comment]
> Only cause I've had wrong EPs play on some nyaa links is why I'd like this

Ahhh i see what you mean, ok so scrapping is kinda broken, well not broken but not very consistent when it comes to big animes with multiple season and i wish i could fix scrapping but i don't understand it well and need @jkaw to work on that. 

My best solution right now is to use embeds cause embeds are very consistent, hopefully in the future, we can fix scrapping sense its a big issue. 

Btw, one thing you could do is prioritize your torrents. We have settings that prioritize, seasons, batches, duel-audio, multisubs, ect. Hopefully those can help.

**Comment by Thor4201** [comment]
> > Only cause I've had wrong EPs play on some nyaa links is why I'd like this
> 
> Ahhh i see what you mean, ok so scrapping is kinda broken, well not broken but not very consistent when it comes to big animes with multiple season and i wish i could fix scrapping but i don't understand it well and need @jkaw to work on that.
> 
> My best solution right now is to use embeds cause embeds are very consistent, hopefully in the future, we can fix scrapping sense its a big issue.
> 
> Btw, one thing you could do is prioritize your torrents. We have settings that prioritize, seasons, batches, duel-audio, multisubs, ect. Hopefully those can help.

Yea that's definitely it, I was messing with some things and whenever I'd add a line to try and fix something, it's like itd skip lines of code and only display nyaa, presumably what it's doing here as well, I'd have to dig further to see why and provide better feedback for ya. 
I'm on windows I should say and I sorta forgot about those settings 😂 I'll have to play around with the settings more.

**Comment by Goldenfreddy0703** [comment]
> I'm on windows I should say and I sorta forgot about those settings 😂 I'll have to play around with the settings more. 

Lol, just make sure you sort sources method is set to torrents so that torrents will work properly for you.

**Comment by Goldenfreddy0703** [comment]
Hey @TaiDak been a while bug great news, Tomorrow or this weekend, we will have an option for manual file selection as well as some other features. Hope this helps and hope to release this weekend.

**Comment by Goldenfreddy0703** [comment]
Hey @TaiDak , good news, we just made a release that should have the option for manual file selection. Huge thanks to @joezito129 for pointing us in the right direction.
