### ISSUE TITLE
[REQUEST] Otaku Players for TMDb Helper 

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [Goldenfreddy0703/Otaku#44]
First I want to thank you all for this awesome addon.

so can someone make a Otaku players for TMDb Helper?
I tried to modify the existing Kaito and Seren but it did not work unfortunately.

**Comment by Goldenfreddy0703** [comment]
Ok so good idea and will be planned in the future but will be awhile due to some future api changes me and my team will be making.

**Comment by Gujal00** [comment]
This often asked feature is not possible as Otaku is a specialist anime addon and not a tmdb-id based English movie/tv addon such as Seren, Umbrella, etc. It is based on anilist and works solely on anilist id.

**Comment by psp2111-ADSLGATE** [comment]
I thought it will work on Otaku since it is originally a fork of Kaito.

it will be nice if there is a way to add players to TMDb Helper since I use TMDb Helper to play from all my addons and switch between them easily.

**Comment by Goldenfreddy0703** [comment]
I mean it probably can sense our new api can get tmdb mappings for movies and tv shows but im not too sure on that yet so there is a possibility but im not too sure on that yet.

**Comment by Gujal00** [comment]
And did Kaito ever work with tmdbhelper correctly? I told you that he addon doesnt use tmdb-id, how can it integrate with tmdb helper?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by psp2111-ADSLGATE** [comment]
@Gujal00 I did not use Kaito since Kodi 18, and at the time I did not know about TMDb Helper.
So idk if it worked correctly or not back then.

@Goldenfreddy0703 idk to be honest, I really dont like the way Anilist and Kitsu split every season as stand alone show. and idk why they do that it will be way easier if it "Main Title" and every sequel treated as season under it. or maybe because they add everything under the "Main Title" Manga, Anime, Movies, OVA...etc.

Anyway as I said it will be nice if there is a way to add support for TMDbH Players.

Thanks again :)

**Comment by Gujal00** [comment]
Every sequel as a new seas9n is American way. Anilist and kitsu as they are anime site follow the anime studios numbering and thats gow it should as you have to follow the creators numbering instead of what tmdb and tvdb think should be. One Piece for example is a s8ngle sgow with 1000+ episodes as per the creator where as tmdb and tvdb make their own arbitrary seasons and episodes so it is never going to work to search for an episode from tmdb helper data. For example episode 878 as per toyo is called Season 20 episode 1. Now if you search for sources from nyaa, gogo or animix wuth tmdbhelper data, there will be zero hits. Howrver if you use the anime studio numbering to search you will get lot of hits.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this issue cause a search player was recently discovered which could help but in the future, i may reopen this if our new api in the future can help provide mappings from tmdb mappings to anilist mappings. 

Big thanks to @mrgsi for making a search player for Otaku

**Comment by psp2111-ADSLGATE** [comment]
@Goldenfreddy0703 and @mrgsi Thanks for the search player.
it is a nice workaround to use otaku with TMDbH, but it does not work probably with foreign regions because of the translated titles. 
in my case I use Arabic Saudi Arabia as metadata lang/region from TMDbH. and it has a lots of Anime with translated title to arabic. so otaku does not give any results because the player is searching for anime with arabic title.

I think making the add-on support grapping TMDb ID is the best way for the Players to work.
also supporting IMDb ID will also be awesome for Subtitle addons like "A4KSubtitles" and "Opensubtitles" to function and work with the addon. NOTE: I am not a developer and dont know much about coding but I think that how these addons search for subtitles.

anyway BIG thanks again for this addon and all the hard works you guys did to revive Kaito and make it shine again is will appreciated.

**Comment by Gujal00** [comment]
As mentioned before there is no source that provides tmdb to anilist/mal id for anime shows. 
Even the best one out there gives tmdb to anime id for movies only
So until that happens player for tmdbhelper is not going to happen.

**Comment by Goldenfreddy0703** [comment]
Hey so great news, we have finally started working on tmdb helper this week, we just need to test, verify, merge, and release and we should have ourselves a very nice tmdb helper player.

This is all thanks to @CheapCyborg for working on this. He has been doing a great job and we hope to get this finished in a few days.

**Comment by psp2111-ADSLGATE** [comment]
@Goldenfreddy0703 @CheapCyborg @Gujal00 and the rest of Otaku team
THANK YOU SO MUCH

**Comment by mrgsi** [comment]
Now updated on the files list and installable zip file. Great work, this is a super bonus for everyone using the Helper.

**Comment by Goldenfreddy0703** [comment]
Awesome, thank you very much for adding those two json files!!!

**Comment by jaimsitecom** [comment]
This is great news. Is there an instruction on how to add otaku player onto my tmdb helper addon? Do i just update otaku addon ang it will be enabled? Or do i need to download something to make it work?

**Comment by jaimsitecom** [comment]
> @jaimsitecom You need to go to your TMDBHelper settings, go to the "Players section" and use this link: https://bit.ly/gplayers where it says something like "Update players from url", Make sure your Otaku is updated and you should be good to go!
> 
> Thanks to everyone and @mrgsi for getting the players added!

Noted. Thanks so much for the help!
