### ISSUE TITLE
Animixplay is shutting down.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Goldenfreddy0703/Otaku#45]
Hey everyone, we are very sad to hear Animixplay got shutdown but in a few days, we will be adding more stream links and very consistent episode meta in the future. We have been working with a team called Consumet for a few months and they have helped us significantly. They will be launching there own database very soon and we will be using there api to help you guys provide high quality anime for the future.  

- You guys will have very consistent episode meta.
- Torrents will be much easier to find 
- Artwork meta will also be very Consistent as well. 

Edit: @Gujal00 has found an alternative animixplay site that we can use for new animes so there is no need to disable Animix. 

Thank you to everyone in this announcement.

**Comment by Blockr22** [comment]
Thnx, really enjoying this addon for a while now.
Will love more features & optimizations.

**Comment by rollingmoai** [comment]
YugenAnime is a great alternative to Animixplay

#46

**Comment by Gujal00** [comment]
have recoded to use alternative animixplay site. Can look at Yugenanime later if needed as it seems to have the vrv link which animix already gets

**Comment by Goldenfreddy0703** [comment]
Hey guys, i have pushed a release for Otaku about the alternative animixplay site. From testing, the new animes work with it and it looks to be working perfectly fine with it. Now there is no need to disable Animix. 

Thank you
