### ISSUE TITLE
Add YugenAnime source

### ISSUE THREAD

**Issue by rollingmoai** [Goldenfreddy0703/Otaku#46]
Since Animixplay is shutting down, YugenAnime is regarded as the best alternative that can also scrape Gogo and VRV.

https://yugen.to/

**Comment by Goldenfreddy0703** [comment]
Hey, i didn't know a site like this existed and it uses anilist ids and is just like anilist, this would be perfect for our addon. Thank you

**Comment by Goldenfreddy0703** [comment]
Hey @rollingmoai , it looks like we might not need to use YuganAnime cause reason why is cause it uses gogo streams. In the future, we will be having a lot of embedded streams thanks to our new api. 

Im going to go ahead and close this but thank you for the suggestion.

**Comment by rollingmoai** [comment]
Hmm, seems like the Crunchyroll scraper is down on their site
