### ISSUE TITLE
Wrong episodes for demon slayer

### ISSUE THREAD

**Issue by adrenalinx4** [Goldenfreddy0703/Otaku#47]
Demon slayer entertainment arc shows the Mugen train arc

**Comment by Goldenfreddy0703** [comment]
Hey so yeah....episode meta needs to be worked on and we will be working very soon on that to give you guys very consistent episode meta in the future.

**Comment by adrenalinx4** [comment]
No pressure you guys are doing a wonderful job! just thought I would help by letting u guys know of any inconsistencies and again great work!
