### ISSUE TITLE
Anime lists not syncing 

### ISSUE THREAD

**Issue by fregapple** [Goldenfreddy0703/Otaku#48]
Hey!

I have tried both MAL and Anilist.

I can make the list on their websites, to which after authorising, they sync with Otaku and I can see what episode I am up to and such. However, if I watch an episode on Otaku, it won’t update the list on the website. I have waited for half a day for both, I have reauthed multiple times, changed the update list to various ones, turned off update list and then turned it back on. I have disabled each lost and re-enabled.

nothing seems to work!

I am using Kodi on my TV android app.

**Comment by Goldenfreddy0703** [comment]
Mmm, weird. There could be a possibility that this could be due to a widget issue if you were playing an anime that was on a skin widget. I will take a look at this soon.

**Comment by fregapple** [comment]
I was playing an anime on a widget that is for sure. 
Chainsaw Man infact.

I will try with another anime, within the Otaku addon itself too see if that does anything different.

**Comment by fregapple** [comment]
Okay to update.

IT is working, i see that the actually issue I am having is when I try and mark them as watched within Kodi, it doesn't recognize it. 

I have to either manually do it on anilist or start playing the video for it to be recognized.

Will there be support for marking as watched?

**Comment by Goldenfreddy0703** [comment]
> Will there be support for marking as watched?

I think there is support already for that cause we have a context menu that says "add to watchlist" or something.

**Comment by fregapple** [comment]
I'll check it out thank you
