### ISSUE TITLE
Hajime no Ippo: The Fighting - Wrong episodes

### ISSUE THREAD

**Issue by fregapple** [Goldenfreddy0703/Otaku#49]
The interface shows the correct episodes, but plays episodes from Hajime no Ippo: New Challenger.

If trying to watch later episodes EG. Ep 45, it comes up with nothing because it's searching the other season which doesn't have that many episodes.

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this but @Gujal00 is right, in the future, we will be adding alot of embeds soon and hopefully one of those embeds may have right episodes in the future.

**Comment by fregapple** [comment]
I have my real-debrid and it doesn't find anything. Only embedded.

And the embedded it does find, are not the first season.

**Comment by fregapple** [comment]
My issue wasn't that it couldn't find anything, but that when I played season 1 episode 1. It says it finds the video, but intact it's starts playing the next season episode 1 instead. While still thinking it is the first episode of season 1.

**Comment by fregapple** [comment]
I went to GoGoAnime, where it is pulling these embeds from. Perhaps a way we could fix this is to create a exclude list, that it checks before scraping and if it is on there It won't scrape from the named provided EG GoGoAnime, or change the title it is looking for. In case it needs to be more specific?

**Comment by Goldenfreddy0703** [comment]
> Shouldn't we at least fix the issue that it is finding the wrong episodes?

We already kinda have a fix in mind already that will be released very soon that's going to make episode meta and embeds very consistent where you will not have the wrong episodes. 

We also will be releasing new fresh embeds very soon that will use Gogo, Animepahe, Zoro, Enime so you guys can have a ton of embeds and they wont be wrong. 

We will have a fix very soon.

**Comment by fregapple** [comment]
Thankyou for your response. I look forward to it.

**Comment by Gujal00** [comment]
> I have my real-debrid and it doesn't find anything. Only embedded.
> 
The addon looks for cached files from debrid providers, looks like RD doesnt have anything for that show cached where as AllDebrid and Premiumize boith have them cached
