### ISSUE TITLE
Unable to auth anilist

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#5]
I'm unable to auth anilist. I put in the token and click authorize but nothing happens.

**Comment by Goldenfreddy0703** [comment]
Hey sorry iv'e been busy. We may still have that bug about whenever you login to something, you have to restart to addon. 

Try logging in and close kodi and open it back up and tell me if that did the trick for you.

**Comment by Liquidrag** [comment]
It won't let me log in. I entered the key and click authorize but it doesn't do anything, just stays on that screen. I was able to auth MAL and Kitsu.

**Comment by Goldenfreddy0703** [comment]
That's odd, let me try to log in

**Comment by Goldenfreddy0703** [comment]
Ok now i can see what you mean, let me see if @Gujal00 can fix that.

**Comment by Liquidrag** [comment]
Thank you. Is there a way to sync watched items to all 3 services?

**Comment by Goldenfreddy0703** [comment]
> Thank you. Is there a way to sync watched items to all 3 services?

I mean possibly, we just never considered that as a an option but could try it someday. 
Here is a workaround to sync watched items to all 3 services even simkl: https://malsync.moe/

**Comment by Liquidrag** [comment]
> > Thank you. Is there a way to sync watched items to all 3 services?
> 
> I mean possibly, we just never considered that as a an option but could try it someday. Here is a workaround to sync watched items to all 3 services even simkl: https://malsync.moe/

Thanks I’ll try that!

**Comment by Goldenfreddy0703** [comment]
Hey @Liquidrag , me and my team released an update to Otaku that fixed Anilist. Give that a try and tell us if that worked for you and big thanks to @umbrellaplug for providing a fix.

**Comment by Liquidrag** [comment]
> Hey @Liquidrag , me and my team released an update to Otaku that fixed Anilist. Give that a try and tell us if that worked for you and big thanks to @umbrellaplug for providing a fix.

It fixed it. Thank you, guys!

**Comment by Goldenfreddy0703** [comment]
Hey anytime, we are always glad to help. 😁
