### ISSUE TITLE
[REQUEST] subtitles turn on automatically for subs and off for dubs

### ISSUE THREAD

**Issue by icpryde** [Goldenfreddy0703/Otaku#50]
So I've been playing around with this to try and figure out if it's at all possible with subtitles, I like to watch dub most of the time but if only sub is available ill watch sub. But that means I have to then turn subtitles on so I can see them, but this means I have to go back and forth turning them on/off depending if its dub or sub.

I'm wondering if it's at all possible to have a setting where its something like "if default language is detected (dub) then subtitles off, if Japanese language detected subtitles on.

I know this works with regular shows/movies when using Seren because I can go into setting and have "forced only" subtitles selected so when a scene in the movie doesn't have English for example it will show the subtitles for only the none english parts.

I noticed with anime though it won't work because the subtitles in the cached torrents aren't labelled as "forced" and only as "English" or whatever languages are available. So I think something like what I mentioned above would need to be a setting.

Anyway I don't know anything about coding so not sure if this is just way to hard or if its an easy thing to add but it would be amazing to have!

**Comment by Goldenfreddy0703** [comment]
Umm, ok im not too sure what your asking but im sure @Gujal00 might know. If i remember correctly, you can go into Kodi's player settings and go to languages and you should see video and audio and maybe subtitle language, You can get them forced like if you follow the last optional step in the troubleshooting page.

**Comment by joezito129** [comment]
It depends on the torrent, for example some of the torrents have labeled the subtitles as forced
![Capture2](https://user-images.githubusercontent.com/60677138/213396970-34daef8b-5e88-4de4-a581-50444bf9c828.PNG)
and some label them as Japanese. 
![Capture](https://user-images.githubusercontent.com/60677138/213397272-333b6773-25da-43ea-a605-69e76f04f5af.PNG)

What your asking seems simple enough to implement but i think it would be better to have the addon detect which is the "Signs & Songs" and only switch to that one when playing dub audio.

**Comment by Goldenfreddy0703** [comment]
>  i think it would be better to have the addon detect which is the \"Signs & Songs\" and only switch to that one when playing dub audio.

You know, I think that is a really great idea to add cause sometimes when it comes to torrent, there is different languages and we are looking for dialog, I think there is a way and hopefully we can add that very soon once we fix the bugs on our consumet testing branch.

**Comment by joezito129** [comment]
unfortunately, I haven't found a way for kodi to detect the name of the subtitle, it can only detect the language.

**Comment by Goldenfreddy0703** [comment]
> unfortunately, I haven't found a way for kodi to detect the name of the subtitle, it can only detect the language.

Hopefully there might be something in the kodi wiki that could help us.

**Comment by Gujal00** [comment]
An addon can only control external subtitles, it has no control over subtitles included inside a MKV/MP4 container. Kodi FFMPEG is the one in control of that and that is controlled by the Kodi language and player settings. It cannot be influenced from within an addon

**Comment by Goldenfreddy0703** [comment]
> An addon can only control external subtitles, it has no control over subtitles included inside a MKV/MP4 container. Kodi FFMPEG is the one in control of that and that is controlled by the Kodi language and player settings. It cannot be influenced from within an addon

Awww i thought the kodi wiki or kodi 20 would have something that would help control that. That's too bad. Im going to close this issue but if something new comes up where we have the ability to control subtitles, I will open this issue back up.

**Comment by Goldenfreddy0703** [comment]
@icpryde news, i got that working but for jpn streams, there is no control over subtitles included inside a MKV/MP4 containers.

**Comment by icpryde** [comment]
@Goldenfreddy0703 oh interesting so if it notices the language is in japanese it will turn the subtitles on for the mkv files is that what you are saying?

**Comment by Goldenfreddy0703** [comment]
Yes and if it's English, It will turn off automatically.

**Comment by icpryde** [comment]
@Goldenfreddy0703 oh wow! so you actually did it! thats amazing man i can't wait to try it! that is kinda blowing my mind!

**Comment by Goldenfreddy0703** [comment]
Yes, took me two days to figure out but finally figured it out. Now I need to figure out issue #67. Idk how to fix it but we are getting there.

**Comment by ShibajiCh** [comment]
Hi @Goldenfreddy0703,

Is it possible to provide a toggle for this Subtitle On/Off feature under Otaku settings, because sometimes I'd like to use both the English audio along with English subtitles? Please let me know if this is possible or do I need to manually turn on the English subtitle along with English audio if the need be. Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Yes, will try working on it soon.

**Comment by ShibajiCh** [comment]
> Yes, will try working on it soon.

Thank you so much @Goldenfreddy0703 ! 🙂

**Comment by Goldenfreddy0703** [comment]
Hey btw, i added a new setting "Enable Automatic Subtitles for Dub Streams" in Preferences and made a release a while ago so hope this works.

**Comment by ShibajiCh** [comment]
> Hey btw, i added a new setting "Enable Automatic Subtitles for Dub Streams" in Preferences and made a release a while ago so hope this works.

Hi @Goldenfreddy0703,

Thank you so much! It's working perfectly! 🙂👍🏻

Thanks and Regards,
ShibajiCh.

**Comment by icpryde** [comment]
@Goldenfreddy0703 amazing bro! Can’t believe you figured it out thank you so much!

**Comment by Goldenfreddy0703** [comment]
> 

Hey thank you, this setting actually enables subtitles for both dub and sub, not just dub.
