### ISSUE TITLE
Issue with Real Debrid link Scraping

### ISSUE THREAD

**Issue by ShibajiCh** [Goldenfreddy0703/Otaku#53]
Hi @Goldenfreddy0703,

First of all thank you for this great anime add-on "Otaku"!

As per our discussion on Reddit, I'm reporting this issue here on GitHub. Majority of the times when I scrape an episode from any particular season of a TV Show, then even though the episode is cached on Real Debrid the links don't show up in the scraping results. However, sometimes the links show up correctly for that exact same episode. Other non-anime add-ons show up the same links in their results perfectly. This issue happens randomly so I'm not sure exactly what might be causing the issue. I've tried all the mentioned troubleshooting steps but still the issue is not resolved. This issue also occurs for Movies sometimes. Could you please look into the issue and kindly resolve it? I'm using an Nvidia Shield TV Pro 2019 with Kodi Nexus v20.0. Kindly let me know if you need any other details from me.

Thanks and Regards,
ShibajiCh.

**Comment by joezito129** [comment]
Could you specify on what show that you are not getting real-debrid links from.

**Comment by ShibajiCh** [comment]
> Could you specify on what show that you are not getting real-debrid links from.

Majority of them. For example, "One Piece". Earlier, at least I could see the Real Debrid links sometimes. Now, the Debrid links are almost not appearing at all. The other non-debrid links are showing up fine after scraping.

Thanks and Regards,
ShibajiCh.

**Comment by joezito129** [comment]
try changing line 140 of source_utils.py to 
                   )?                                   # end non-grouping pattern

**Comment by ShibajiCh** [comment]
> try changing line 140 of source_utils.py to )? # end non-grouping pattern

Hi @joezito129 ,

Thank you, but I'm afraid changing that line as per your above instructions didn't fix the issue.
I'm still not able to see any Real Debrid links after scraping.

Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry i have not gotten back on this issue but i do see what you mean and scrapping atm is kinda an issue due to our new consumet api with episode consistency. Seasons are no longer split i think due to it and i think that could be putting off scrapping, im not totally sure it could be for animes that have seasons, could be but in the future, we will improve scrapping. Not sure how but we will soon.

**Comment by ShibajiCh** [comment]
> Hey there, sorry i have not gotten back on this issue but i do see what you mean and scrapping atm is kinda an issue due to our new consumet api with episode consistency. Seasons are no longer split i think due to it and i think that could be putting off scrapping, im not totally sure it could be for animes that have seasons, could be but in the future, we will improve scrapping. Not sure how but we will soon.

Hi @Goldenfreddy0703,

Thank you for your reply! I shall wait for future updates regarding this issue. Hope that it gets resolved soon. Thanks again!

Regards,
ShibajiCh.

**Comment by Gujal00** [comment]
May be realdebrid doesn't have those episodes cached.
The nyaa scraper works fine with the consumet episode meta and finds many matches including 4K
![screenshot00000](https://user-images.githubusercontent.com/17394059/215008412-91992c6e-e953-4586-9fcb-5bece30c0c8c.png)

**Comment by ShibajiCh** [comment]
> May be realdebrid doesn't have those episodes cached. The nyaa scraper works fine with the consumet episode meta and finds many matches including 4K ![screenshot00000](https://user-images.githubusercontent.com/17394059/215008412-91992c6e-e953-4586-9fcb-5bece30c0c8c.png)

Hi @Gujal00,

Those episodes are cached in Real Debrid and are  showing up fine in Fen and other add-ons. They initially even showed up in Otaku, but currently they are not at all showing up in Otaku. May be the last few updates caused some issues. Not sure what.

Thanks and Regards,
ShibajiCh.

**Comment by joezito129** [comment]
I noticed i get a lot more sources when rescrape item
rescrape item results:
![Capture](https://user-images.githubusercontent.com/60677138/215097538-667abed5-5d15-4061-81d4-0a8945882457.PNG)

select source results:
![Capture_2](https://user-images.githubusercontent.com/60677138/215097552-17330b7d-4746-4199-aeed-391cc362a0f5.PNG)

**Comment by ShibajiCh** [comment]
> I noticed i get a lot more sources when rescrape item rescrape item results: ![Capture](https://user-images.githubusercontent.com/60677138/215097538-667abed5-5d15-4061-81d4-0a8945882457.PNG)
> 
> select source results: ![Capture_2](https://user-images.githubusercontent.com/60677138/215097552-17330b7d-4746-4199-aeed-391cc362a0f5.PNG)

Hi @joezito129,

Rescrape Item is not even working for me. It's giving empty results always. However, Source Select works fine, even though I'm not able to see any Real Debrid links.

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment]
@ShibajiCh Fen and others scrape many sites. Otaku only scrapes nyaa. So if you are not seeing realdebrid sources, most probably nyaa.si, the primary site is blocked by your ISP.
In settings-providers try enabling Nyaa Alt and then see if you can find episodes for One Piece

**Comment by ShibajiCh** [comment]
> @ShibajiCh Fen and others scrape many sites. Otaku only scrapes nyaa. So if you are not seeing realdebrid sources, most probably nyaa.si, the primary site is blocked by your ISP. In settings-providers try enabling `Nyaa Alt` and then see if you can find episodes for One Piece

Hi @Gujal00,

Thank you! I can understand that, but the problem is I already enabled Nyaa Alt. Also, without enabling Nyaa Alt I could still see Nyaa sources, so I don't think Nyaa is blocked by my ISP. I also tried changing different settings and also uninstalled and reinstalled the Otaku addon. The Real Debrid sources appear for a few scrapes after uninstalling and reinstalling the addon and also after changing a few settings like title language, etc. However, after that again the Real Debrid sources stop showing up and I can only see the other Free Sources. I've done a lot of R&D but couldn't find the issue. 🙁 Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @Gujal00,

I checked further and can confirm that you're partially correct. I've enabled Nyaa Alt and now Real Debrid links are appearing for some videos. It seems all the Real Debrid links are from Nyaa. However, they are really a hit or miss, because sometimes they appear and sometimes not, even for the same Movies or TV Shows. May be Nyaa is blocked by my ISP but at least Nyaa Alt should work everytime, right? Why are the Real Debrid links appearing sometimes and not at other times, even for the same Movie or TV Show? What might be the issue? Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by joezito129** [comment]
Are you able to visit the nyaa.si site on your browser?

**Comment by ShibajiCh** [comment]
> Are you able to visit the nyaa.si site on your browser?

Hi @joezito129,

I checked and found out that Nyaa.si is blocked by my ISP, but Nyaa Alt should work everytime, right? It's working sometimes and sometimes not, even for the same Movie or TV Show. Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment]
@ShibajiCh 

>It seems all the Real Debrid links are from Nyaa

Realdebrid is used only for torrents and torrents only come from Nyaa
nyaa is one of the inconsistent sites when it comes to searching, so yes, the results could be different each time you search for, especially for Anime like One Piece which has over 1000+ episodes and 40+ specials. It is what it is and nothing can be done about it. As the embeds work and they are also HD, just watch that
this is the search for Episode 1 of one piece, see what you get in your browser
`https://nyaa.iss.ink/?f=0&c=1_0&q=(ONE+PIECE)|(ONE+PIECE)+%22-%2001%22&s=downloads&o=desc`

**Comment by ShibajiCh** [comment]
> @ShibajiCh
> 
> > It seems all the Real Debrid links are from Nyaa
> 
> Realdebrid is used only for torrents and torrents only come from Nyaa nyaa is one of the inconsistent sites when it comes to searching, so yes, the results could be different each time you search for, especially for Anime like One Piece which has over 1000+ episodes and 40+ specials. It is what it is and nothing can be done about it. As the embeds work and they are also HD, just watch that this is the search for Episode 1 of one piece, see what you get in your browser `https://nyaa.iss.ink/?f=0&c=1_0&q=(ONE+PIECE)|(ONE+PIECE)+%22-%2001%22&s=downloads&o=desc`

Hi @Gujal00,

Thank you for the detailed explanation! Nyaa is blocked by my ISP unless I'm using a VPN. Anyways, Nyaa Alt is working sometimes and sometimes not, so it's a hit or miss. I guess I've to watch the free sources now or need to use a VPN if I want to watch the 4K Real Debrid links. Nevertheless, thanks for all your help!

Regards,
ShibajiCh.
