### ISSUE TITLE
Episode Aired date not showing in Next Up

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#54]
I just noticed that episode aired date is not showing in Next Up, whether from widget or addon directly. It does show episode airdate  in sections like Airing Anime or Current in addon. I tested in both Auramod and Arctic Horizon 2 on Kodi 20.

I also noticed that clearlogo is inconsistent at the episode level in sections like Airing Anime or Current. Take the below example, clearlogo is there at show level and in Next Up, but when you go into the show to browse episodes, the clearlogo dissappears. This doesn't happen on every show, but you can see it in the show below and also for example in "Ningen Fushin: Adventurers Who Don’t Believe in Humanity Will Save the World" among others:

From Next Up:
![screenshot00001](https://user-images.githubusercontent.com/13154733/214341190-ad320097-87de-4a5e-a55a-ff4fc1d84fde.png)

From Current:
![screenshot00000](https://user-images.githubusercontent.com/13154733/214341281-4ffe2a29-e271-41cc-a994-7ea760ae460c.png)

**Comment by Goldenfreddy0703** [comment]
Sometimes episodes don't really contain air dates due to lack of date. Hopefully there will be more aidates very soon

**Comment by meesterexx** [comment]
But it's the same example episode in the screenshots and it shows the airdate in other views. I'm confused by your reply.
No airdates for any episodes show at all in Next Up. Airdates show fine in other sections of the addon _for the same episodes_. It looks like the Next Up section is simply not parsing airdates at all.

**Comment by meesterexx** [comment]
Hey thanks, much appreciated!

**Comment by joezito129** [comment]
I made a pull request that should fix the issue.

**Comment by Goldenfreddy0703** [comment]
Heyyy thank you for making a pr, will make a new release in a few that should make airdates show up in the next up category.

**Comment by meesterexx** [comment]
Just tried the update. Looks like it's working here except for things that just aired today/last night. I guess those will fill in as the online metadata sources get updated.

Thank you @joezito129 and @Goldenfreddy0703 !

**Comment by Goldenfreddy0703** [comment]
Hey anytime, im going to go ahead and close this issue.
