### ISSUE TITLE
Zoro scraping time

### ISSUE THREAD

**Issue by fregapple** [Goldenfreddy0703/Otaku#56]
Nice you have brought some extra providers into the mix. Zoro is usually my go to. 

Not sure if really an issue, but When scraping however, zoro takes up majority of the time to scrape. 
Onwards of 10 seconds or longer. Where it is near instant for the other ones.

I'll test this on my pc later today to see if zoro scrapes faster than the telly.

**Comment by Goldenfreddy0703** [comment]
Yeah Zoro may take time to scrap cause reason why is cause of our new api and how we get the stream, oh btw today zoro had a bit of trouble so some of the people of consumet are fixing that.

**Comment by Gujal00** [comment]
@fregapple Is this still happening, a fix was pushed in the last release

**Comment by fregapple** [comment]
I'll give it a look tonight

**Comment by fregapple** [comment]
All good now
