### ISSUE TITLE
Otaku Crashing Kodi

### ISSUE THREAD

**Issue by ibunka2023** [Goldenfreddy0703/Otaku#57]
Otaku has been crashing Kodi for me ever since upgrading to v20. I uninstalled the add-on and reinstalled, and the issue went away. After changing the episode title format to the English "(Attack on Titan)" example, after clicking on any page that displays a list of anime episodes **under the TV section** (Trending This Season as an example under the TV section), the app crashes when loading the names of different animes and their ratings. The issue doesn't exist if I switch the titles back to Japanese, OR if I am looking under movies. It is only TV Show related. Possibly a bad character encode issue after being translated?

**Comment by Gujal00** [comment]
What platform are you running it on?
Kodi v20 has many issues with encoding depending on platform as Team Kodi is now using different Python versions on different platforms.
It works fine on Kodiv19.5 on all platforms and on Kodiv20 CoreElec

**Comment by ibunka2023** [comment]
NVIDIA shield 2019 pro.

**Comment by Gujal00** [comment]
You have to rollback to Kodi 19.5. The font handling in Kodi 20 is new and seems to be crashing Kodi when encountering special charaters, An addon such as Otaku written in Python cannot crash kodi. Wait for Kodi 20.1
```
https://forum.kodi.tv/showthread.php?tid=371346&pid=3136939#pid3136939
```

**Comment by Liquidrag** [comment]
I had crashing issues too and found if I had a4ksubs disabled, it fixed the issue.

**Comment by Gujal00** [comment]
There is fundamental bug with font rendering in Kodi 20 and above
There has been a PR raised for the master branch (Kodi 21 nightly)
`https://github.com/xbmc/xbmc/pull/22659`
If that gets merged and then gets ported to Kodi 20, then it should fix these random crashes of Kodi

**Comment by trekker77** [comment]
Simply changing 'Title Language' to English (Attack on Titan) worked for me.

**Comment by Goldenfreddy0703** [comment]
Hey so im going to close this issue sense its related to the Issues #69 

Once Kodi makes a public release of 21, hopefully all those issue might go away, who knows.
