### ISSUE TITLE
Rescrape Item Issue and TV Show Otaku Error

### ISSUE THREAD

**Issue by ShibajiCh** [Goldenfreddy0703/Otaku#59]
Hi @Goldenfreddy0703 and @Gujal00,

The Rescrape Item function is always returning empty results after a successful scrape.

Also, many shows like "High School DxD" (All Seasons), etc. are not opening Episodes list, and returning an "Otaku" error notification.

Please check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment]
Fixed "Otaku Error" when trying to open Episode List in https://github.com/Goldenfreddy0703/Otaku/commit/bad6daa4039c95b6f3098654e201301de16549dd

Rescrape is only for torrents and if nyaa is not working properly you will get empty

**Comment by ShibajiCh** [comment]
Hi @Gujal00,

Thank you for fixing the TV Show issue! I noticed that you've edited your above comment about the Nyaa torrent source only Rescraping for an item. So is there any plan to add other sources Rescraping feature as well? Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment]
Rescrape is only for nyaa as the the magnet hashes are stored in a database and reused. Rescrap ignores the database and scrapes nyaa again.
The embed sources are always scraped and rescrape does not apply

**Comment by ShibajiCh** [comment]
> Rescrape is only for nyaa as the the magnet hashes are stored in a database and reused. Rescrape ignores the database and scrapes nyaa again. The embed sources are always scraped and rescrape does not apply

Hi @Gujal00,

Thank you for the information!

Thanks and Regards,
ShibajiCh.
