### ISSUE TITLE
Proper support of Landscape fanart scaling in widgets and views

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#6]
This is actually an issue that's been in kaito for as long as I can remember, but since otaku is getting some good and needed work, I thought I would post it here to see if it's on the roadmap. 

1. When I use otaku for widgets with any kind of landscape art style it stretches poster art to fill landscape proportion
2. When I use it for addon views with any kind of landscape art style it crops off part of the art

I've also noticed that fanart in general seems lower resolution in otaku than in other addons like fen or tmdbhelper. 

Here are some screenshots to show what happens. These are from auramod, but it does it in other skins like AH2.

Skin search widget, landscapeposter style, art stretched:
![otakuL1](https://user-images.githubusercontent.com/13154733/186460352-7685e112-33de-4ab4-9b4b-20159ed39b1d.png)

home screen widget, landscapewide style, art stretched:
![screenshot00001](https://user-images.githubusercontent.com/13154733/186461159-d1431f22-a4c6-4c21-aaa4-25348686fc2a.png)

addon view, landscape showcase, art cropped:
![screenshot00000](https://user-images.githubusercontent.com/13154733/186460722-4ddcf2dc-e826-460a-96ba-5b3146c722c4.png)

**Comment by Goldenfreddy0703** [comment]
Ooo..ok i can see what you mean, in the future. We are probably going implant Fanart tv for these especially for landscape art but i will see what we can do about that.

**Comment by meesterexx** [comment]
Sounds good, thanks. If you need someone to beta test before release, let me know, I'd be happy to help.

**Comment by Gujal00** [comment]
The main issue is meta for anime comes from anilist or mal and both sites do not host landscape (background) art. The only art available is poster and episode thumbnails, and in some cases only poster.
Cannot compare this with addons using tmdb/fanart because tmdb/fanart are not anime-centric and will not have art for many anime

**Comment by Goldenfreddy0703** [comment]
Yesterday I was looking at the api's for anime databases and I came across kitsu becouse they have cover art for anime for landscape but it only takes 100 request per hour sadly.

**Comment by meesterexx** [comment]
> Yesterday I was looking at the api's for anime databases and I came across kitsu because they have cover art for anime for landscape but it only takes 100 request per hour sadly.

Interesting. The Stremio Kitsu addon is using it. Their user base would surely blow through the 100 requests an hour: https://github.com/TheBeastLT/stremio-kitsu-anime

This looks interesting. Maybe they're doing something like this: https://github.com/henryhomes/stremio-kitsu
"How can this add-on help other anime add-ons? It's simple, just like Stremio's Cinemeta which creates movie / series pages based on IMDB ID, this add-on creates anime pages based on Kitsu ID."

**Comment by Goldenfreddy0703** [comment]
Interesting, may want to look into that more. Im surprised and forgot that there was a kitsu addon for stremio.

**Comment by meesterexx** [comment]
Yeah, they're definitely pulling in some nice fanart. TBH, the new stremio version for Android TV is pretty nice & clean.
Here's 2 fanart from the poster row below:

![poster](https://user-images.githubusercontent.com/13154733/186910949-f230855a-7dd5-4959-abc6-d8f0f994d247.png)

![fanart](https://user-images.githubusercontent.com/13154733/186911156-cb9cdcb3-a848-444d-8e5a-d3349072fe9f.png)

![fanart2](https://user-images.githubusercontent.com/13154733/186911168-f56bbc1b-1b08-4c5a-94ed-6fa6d1653a05.png)

**Comment by meesterexx** [comment]
I just noticed the latest cloudstream beta also uses kitsu. The cs user base is huge , so there must be some way around the limit:

![cs](https://user-images.githubusercontent.com/13154733/186929835-597fa7c8-2f29-4f42-bdc7-1d9e5b124872.png)

**Comment by Goldenfreddy0703** [comment]
You know, your right. It is possible, we just need @Gujal00 go look at this sometime.

**Comment by Goldenfreddy0703** [comment]
Heyyy Good news, we know this issue is like 19 days old but i found out we can do an unlimited amount of request with Kitsu's api and add cover images to each anime series without having fanart tv to help us, we just need to make sure not to overuse there api and images are handled by there CDN, so it doesn't strain Kitsu's servers so someday, we should be able to get landscape titles for our anime and all.

**Comment by meesterexx** [comment]
Great news and thanks for looking into further!

**Comment by Gujal00** [comment]
@meesterexx check with v0.2.1 and report back. Thanks

**Comment by meesterexx** [comment]
I'm not seeing any difference. Upgraded to 0.21, cleared addon cache, went to Trending This Season, Landscape art is still cropped poster, fanart is crop of top of poster. Is there something I need to change?:

![screenshot00001](https://user-images.githubusercontent.com/13154733/192106243-f263cc66-da7d-457b-9243-8135c787f468.png)

![screenshot00000](https://user-images.githubusercontent.com/13154733/192106256-41e9f619-a5ae-46d0-b8ac-b4ffd3004c39.png)

**Comment by meesterexx** [comment]
Forgot to add, same in Arctic horizon 2 as well.

**Comment by Gujal00** [comment]
@meesterexx yes, the landscrape art is not scraped to start with. but as you keep going in and out of shows, it gets scraped and stored in the database for use next time, so over time you would have slowly built your landscape art.
This is done to keep the speed of opening menus as fast as possible and not slowdown as kaito beta did.

**Comment by meesterexx** [comment]
Ok, I understand now thanks, and the landscape art looks great! But the poster changes after scrape of landscape and appears to be the wrong cropping. See before and after going into title scrape below:

Before going into title:
![screenshot00000](https://user-images.githubusercontent.com/13154733/192152731-82389bc5-bd33-4f1a-bd35-2d5424f8a59b.png)

After going into title:
![screenshot00001](https://user-images.githubusercontent.com/13154733/192152745-517a88ce-5ce1-4c56-8aa8-dd84f22ab1fd.png)

![screenshot00002](https://user-images.githubusercontent.com/13154733/192152874-4d3bcb02-c2bb-420a-8d9a-80b5f8355c72.png)

**Comment by Gujal00** [comment]
Okay seems to be bug, the original poster is getting replaced with tmdb poster. Will check it out, Thanks for reporting

**Comment by Goldenfreddy0703** [comment]
I was thinking similer about that and made a suggestion to have an experimental settings option for that but loading fanart for each anime series takes 4 protocols which could possibly slow down the loading speed and if we added that, it could probably turn out to be slow like Kaito beta. 

I think having a context menu option to load all fanart for all anime in a single page would be a great idea cause if a user had Otaku landscape widgets for his or her skin then that context menu option would be a very good idea. 👍

**Comment by meesterexx** [comment]
BTW, how can I scrape fanart for movies, is there a way to do this? Otaku is not picking it up, just cropping the poster art. I tried in both AH2 and auramod, and from the screenshots below (from Top 100 Anime),  I can use the TMDBHelper context item (when in Otaku) to manage and select artwork, but it doesn't apply it.

Is there a way that Otaku could use the TMDBHelper art selection if it doesn't find fanart itself? Though if TMDBHelper is picking up the fanart from TMDB, it seems Otaku should be able to.

![screenshot00001](https://user-images.githubusercontent.com/13154733/193045834-b35513c9-774f-4eec-8ba1-76c03c5cb25a.png)

![screenshot00002](https://user-images.githubusercontent.com/13154733/193045867-7b4304f1-54b3-4eef-b5cf-2270d937d758.png)

![screenshot00003](https://user-images.githubusercontent.com/13154733/193046280-d107fc8c-0bf9-4dd1-9a32-189b11252df0.png)

![screenshot00004](https://user-images.githubusercontent.com/13154733/193049420-4ee3509f-c850-4f5f-b75e-ea392d1c3e40.png)

![screenshot00005](https://user-images.githubusercontent.com/13154733/193049453-0f081317-57d8-4051-8f71-ed2377a901d4.png)

**Comment by Goldenfreddy0703** [comment]
Tmdb helper context menu is not compatible with Otaku. For Movies, you sometimes have to click them and they would play in order to generate the fanart and stuff.

**Comment by Gujal00** [comment]
otaku does use tmdb if it cannot find art from fanart.
however Anime movies are a mystery, they are classified as specials if they are part of a tv series.
The artwork call to both fanart and tmdb has to specify whether it is a movie or a tv and that is impossible to guess for anime tv show based movies if they are classified as special or movie
Also tmdb does not have landscape posters, they only have backdrops, logo and poster

**Comment by Goldenfreddy0703** [comment]
Heyyy @meesterexx , we added fanart and landscape to anime now so this should cover proper support of Landscape fanart scaling in widgets and views. 

Try out our latest release and see if that helps you out.

**Comment by meesterexx** [comment]
Wow, looks amazing! This fixed the movie issue. Thank you both for digging into the issue and getting it implemented!

**Comment by Goldenfreddy0703** [comment]
Hey anytime, this is all thx to @Gujal00 

I will be closing this issue but if you have any problems or bugs or need this reopened, let us know and we will do our best.
