### ISSUE TITLE
Request for a scraper timeout similar to other addons.

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#60]
Request for a scraper timeout similar to other addons.

**Comment by joezito129** [comment]
I made a pull request for this.
Please let me know if this is what you are looking for.

**Comment by Liquidrag** [comment]
Sorry idk what pull requests are.

**Comment by Goldenfreddy0703** [comment]
Hey @joezito129 I never thought about adding a timeout setting, thank you. I will test it out once I'm done eating.

**Comment by Goldenfreddy0703** [comment]
@Liquidrag hey, a release should be out in 10 min so give it a try and tell us what you think.

**Comment by Liquidrag** [comment]
@Goldenfreddy0703 works perfectly! Thank you guys for this great addon!

**Comment by Goldenfreddy0703** [comment]
Hey anytime but big thanks to @joezito129 for making the pr.
