### ISSUE TITLE
Request for 2 lists

### ISSUE THREAD

**Issue by ShibajiCh** [Goldenfreddy0703/Otaku#65]
Hi @Goldenfreddy0703,

Is it possible to create 2 lists one for All Time Trending and one for All Time Popular with both Movies and TV Shows Combined, and sorted by Random? I want to create 2 widgets with them.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
When you say list do you mean your watchlist. If so that's not possible cause watchlist can't be sorted all time tranding nor all time popular.

**Comment by ShibajiCh** [comment]
Hi @Goldenfreddy0703,

No, by list ai meant normal list to be fetched from Anilist website similar to the existing ones like All Time Trending Movies/TV Shows. However, for these 2 lists I want them to be one for All Time Trending and one for All Time Popular with both Movies and TV Shows Combined in them, and sorted by Random. Is that possible?

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
You realize they are already in the addon. They can be either in the trending category or popular catagory Or you could go the menu category in the addons settings and enable the menu items you want, just make sure to restart kodi.

**Comment by Goldenfreddy0703** [comment]
They can't be random sadly cause anilist does not provide that.

**Comment by ShibajiCh** [comment]
Hi @Goldenfreddy0703,

Oh okay, but how to make them combined, that is include both Movies and TV Shows under Trending or Popular lists instead of only Movies/TV Shows like I'm currently seeing? Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
They are already combined, the menus outside of the Movie and TV shows menu are the combined list anime

**Comment by ShibajiCh** [comment]
Hi @Goldenfreddy0703,

Yes, I figured that out now. Actually the TV Shows are more in comparison to Movies so all I was seeing were TV Shows. Now I checked inside the lists and found out that they were combined. Thanks for all the help! You may close this ticket. Any updates regarding my other request about the Playing Next Dialog issue under the closed ticket? Did you get time to test it?

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Nope, cause your kodi is wack from the start. lol

**Comment by ShibajiCh** [comment]
> Nope, cause your kodi is wack from the start. lol

Lol! 🙂 @Goldenfreddy0703 I've shared my updated Kodi log in the other ticket. Kindly check and advise.

Thanks and Regards,
ShibajiCh.
