### ISSUE TITLE
Request: Easy News and A dubbed section?

### ISSUE THREAD

**Issue by ProtoTypeRepo** [Goldenfreddy0703/Otaku#66]
Hey, would it be possible to add "Easy News" as a premium service in the Accounts section? I've been told they have a pretty good anime selection!

Also, I don't know the best way to do this, but would it at all be possible to create a Dubbed section? Like a few categories like "Recently released dubs", "Popular dubs", "Brand new dubs" or anything that would make finding and watching the dub a little easier? An example is say I want to check in on One Piece, there isn't a real way for me to know a dubbed episode has been released unless I just search for sources and see if there's a dubbed version.

Thank you though! I'm a big fan of this addon!

**Comment by Goldenfreddy0703** [comment]
Ok good question, we can probably add easynews but will take some time.

About the dub section, we did have a setting where you could separate dubs and subs but it stopped working a long time ago sadly so we are still trying to figure out a way to fix that in the future.

**Comment by ProtoTypeRepo** [comment]
Okay thank you so much! I know it's an old addon and maybe depreciated code, but there was this addon called 9anime a while back that did the dub/sub thing perfectly. They had this "recently released dub" section that you could make a widget out of and you could very easily see new releases. I don't even need that much though, I would be happy if there were just a way to only get results back with English audio, maybe just a toggle in the settings that filters anything that's not English or at least dual audio?

**Comment by Goldenfreddy0703** [comment]
I remember 9anime, reason why it was depreciated was cause 9anime was very strict and they kept changing there code and making it harder for use to use there service. 9anime is the worst. 

> I would be happy if there were just a way to only get results back with English audio, maybe just a toggle in the settings that filters anything that's not English or at least dual audio?

There is a way, if you look in the troubleshooting steps around the sub or dub area you will find the options on how you can watch dubbed anime. 

Here are the Troubleshooting steps: https://github.com/Goldenfreddy0703/Otaku/issues/15

**Comment by Goldenfreddy0703** [comment]
Here is also this:
![image](https://user-images.githubusercontent.com/62456796/216835963-d6b85fa9-709d-4372-acc2-b03a2570a96e.png)

**Comment by ProtoTypeRepo** [comment]
Okay this actually works really well, thank you! The original addon had a similar function but it never really worked well for me. No matter what setting I put it would always play the wrong episode. I'm not sure if it was a provider issue or what. But this is working very well!

On a side note, I've noticed with a lot of dubbed files, there are alternate subtitle options, one of which only has subtitles if there's Japanese text on the screen. I know how to enable subtitles in general, but I have no idea how to enable a specific subtitle set (or if that's even possible?) Sorry if I should have made a new topic to ask this.

Also, you can mark this closed in general, or just maybe make a note of the request to have a "recent dubbed releases" section. And thank you so much!

**Comment by Goldenfreddy0703** [comment]
There is a way you can enable specific subtitles, you probably have to go to subtitle settings but in not too sure.

Btw im actually going to leave this open cause i have found a list of dubs that will help with having a dub section so in the future, we will have a dub setting for anime.

**Comment by ProtoTypeRepo** [comment]
That's amazing! I appreciate that so much! If you need anything please feel free to message me. I'm mostly only able to provide graphics, but I do have a few contacts if you ever run into real issues! 

If you don't mind me asking, you mentioned a list, would it if anything to do with the trackers (ie my anime list) or would it have to do with the specific providers? I have no real valid reason to know this, just my own curiosity. Thank you!

**Comment by Goldenfreddy0703** [comment]
Ok so I'm not sure about your question but I will show you the list. This list shows all the dub animes from mal that get updated very often, thanks to a github project called Mal Dubs. We can use that list as our advantage to help filter only dub anime so that way, you guys can have dub anime.

**Comment by ProtoTypeRepo** [comment]
Thank you so much! You have no idea how much I appreciate this!

**Comment by Goldenfreddy0703** [comment]
Hey anytime, ok so i just pushed a release that should fix the separate subs and dubs option. When you enable that, you will notice that there are two animes in each menu, that will indicate that one is dub and the other is sub. In the future, we will be improving on that option but for now, we will leave it as it is.

**Comment by ProtoTypeRepo** [comment]
I don't even know if this is an option, but perhaps another (hopefully)
quick thing, in the "genres/tags" section, could there just be a dub item
added? That would just list titles with a dub?

The separate dubs/subs seems to be working perfectly though! It'll make
keeping up with the dub releases a billion times easier and I appreciate
this so much! Thank you!!

**Comment by Goldenfreddy0703** [comment]
Oh that's what im already working on in another branch, still trying to figure that out. I'm working on improving that option where you can select either sub, dub, or both. The sub and both are working, I just need to figure out how to just get dubs.

**Comment by joezito129** [comment]
> Okay this actually works really well, thank you! The original addon had a similar function but it never really worked well for me. No matter what setting I put it would always play the wrong episode. I'm not sure if it was a provider issue or what. But this is working very well!
> 
> On a side note, I've noticed with a lot of dubbed files, there are alternate subtitle options, one of which only has subtitles if there's Japanese text on the screen. I know how to enable subtitles in general, but I have no idea how to enable a specific subtitle set (or if that's even possible?) Sorry if I should have made a new topic to ask this.
> 
> Also, you can mark this closed in general, or just maybe make a note of the request to have a "recent dubbed releases" section. And thank you so much!

@ProtoTypeRepo so we kinda already had a discussion about choosing the subtitles that have Japanese text on issue #50.
Unfortunately Im not sure there is a way to do that.

**Comment by Goldenfreddy0703** [comment]
@ProtoTypeRepo Good News!!!!

We added a Dubbed Section, well actually a dub filter. 

![image](https://user-images.githubusercontent.com/62456796/218340136-8c140788-fc61-4576-8df3-67344e8c08ca.png)
Enabled Filter Subs and Dubs and set your filter to Dub and every anime you see will be Dub.

**Comment by Goldenfreddy0703** [comment]
In the Future we will add Easy News. 

Will take a long time tho so im closing this issue. 

Anyway have a great day!!!!

**Comment by ProtoTypeRepo** [comment]
Thank you so much! The new dub section works perfectly!!

**Comment by Goldenfreddy0703** [comment]
Glad to hear that. Big thanks to @joezito129 for adding this future. This has been an issue for a long time and alot of dub people wanted this but we couldn't find a list but thanks to Mal Dubs, we did and we got that feature now working. 

Again big thanks to @joezito129
