### ISSUE TITLE
Option to hide change log file when Otaku updates

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#70]
Hi, I liked not having the change log pop up after otaku updates but instead liked going into settings to check it. Would it be possible to add an option to disable it?

**Comment by Goldenfreddy0703** [comment]
Umm yes, i can but whenever Otaku updates, clearing cache and clear torrent cache always helps so that most people don't have issues.

**Comment by Liquidrag** [comment]
> Umm yes, i can but whenever Otaku updates, clearing cache and clear torrent cache always helps so that most people don't have issues.

Ok so the popup clears both cache too? would it be possible to implement that process in the background?

**Comment by Goldenfreddy0703** [comment]
I think so yes

**Comment by Goldenfreddy0703** [comment]
Hey sorry I never got back to you but we added that setting for you yesterday. I'm going to close this but if you have any issues with it, pls let us know and we will reopen this.

**Comment by Liquidrag** [comment]
Thank you I appreciate it.

**Comment by Goldenfreddy0703** [comment]
Anytime!!!
