### ISSUE TITLE
NextUp Suggestion

### ISSUE THREAD

**Issue by Guacan0le** [Goldenfreddy0703/Otaku#71]
I’m not really sure this is an issue, but maybe this is a thing and mine just isn’t working correctly. 

Is it possible, when using NextUp as a widget, to display the next episodes name and information instead of just the information for the series as a whole?

**Comment by ShibajiCh** [comment]
Yes, this will be really helpful.

**Comment by Goldenfreddy0703** [comment]
> I’m not really sure this is an issue, but maybe this is a thing and mine just isn’t working correctly.
> 
> Is it possible, when using NextUp as a widget, to display the next episodes name and information instead of just the information for the series as a whole?

We will probably see but im not too sure, widgets have been long lasting issue with Otaku due to playlist but maybe we can change the Next Up info to display the next episodes name and information instead of just the information inside Otaku and it will appear in the widget. 

We will see

**Comment by ShibajiCh** [comment]
> > I’m not really sure this is an issue, but maybe this is a thing and mine just isn’t working correctly.
> > Is it possible, when using NextUp as a widget, to display the next episodes name and information instead of just the information for the series as a whole?
> 
> We will probably see but im not too sure, widgets have been long lasting issue with Otaku due to playlist but maybe we can change the Next Up info to display the next episodes name and information instead of just the information inside Otaku and it will appear in the widget.
> 
> We will see

Fine @Goldenfreddy0703. Thank you for looking into this!

**Comment by Guacan0le** [comment]
@Goldenfreddy0703 Thank you for the reply. I’ll keep a lookout for it. If it doesn’t happen it’s no big deal. Just thought it would be neat.

**Comment by Goldenfreddy0703** [comment]
Hey @joezito129, I don't know i code this suggestion but i thought you might know so if you could figure this out and make a pr, that would be great. If not then its totally fine.

**Comment by joezito129** [comment]
I can take a look at it when i get off work.

**Comment by Goldenfreddy0703** [comment]
> I can take a look at it when i get off work.

Thank you very much

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at this, sadly we may not be able to fulfill your suggestion cause i think we need a database to sync episode meta with the next up in order to get it to display the next episodes name and information. We are clueless on how to do that and tbh @jkaw is the only person who could probably figure that out sense he made the watchlist sync in Kaito Beta in the past. 

Hopefully in the future, there would be a contributor or person who could figure this out in the future.
