### ISSUE TITLE
Scrapers mismatched from actual content.

### ISSUE THREAD

**Issue by sirensongss** [Goldenfreddy0703/Otaku#72]
this issue came up in the second most recent update, when i try to watch Dragon Ball, it will play an episode from other series with Dragon Ball in the title, rather than dragon ball itself. its seemingly random if the program actually plays the episode I've selected, or some random other source.

**Comment by Goldenfreddy0703** [comment]
Scrapping needs to be worked, use embeds by changing your sorting option to embeds and that should help you watch the actual content. 

![image](https://user-images.githubusercontent.com/62456796/217714211-6d379817-91a5-4730-b606-7e9ff2be1324.png)

Im going to go ahead and close this issue, in the future, we will work on scrapping.

**Comment by Goldenfreddy0703** [comment]
Btw, torrents and embeds are kinda the same, you won't even notice the difference between the quality.

**Comment by sirensongss** [comment]
great to know, thanks for the quick response! sorry if it was redundant i figured it was better posted here than on /r/addonsforkodi

**Comment by Goldenfreddy0703** [comment]
> great to know, thanks for the quick response! sorry if it was redundant i figured it was better posted here than on /r/addonsforkodi

No your fine and anytime!!!
