### ISSUE TITLE
"See related Anime" 

### ISSUE THREAD

**Issue by ttilta** [Goldenfreddy0703/Otaku#75]
Unfortunately, most anime titles don't list each season as seasons, but instead as new titles all together. Would it be possible to add a "See related Anime" option that would guide you to a list of anime related to the anime you are reviewing. Ideally this would return all seasons of the anime, along with any associated movies, OVAs, etc.

**Comment by Goldenfreddy0703** [comment]
Funny story, that's already on our todo list. For now, we are just fixing a ton of bugs and new features that were recently added.

**Comment by Goldenfreddy0703** [comment]
Hey @ttilta good news, we have made a release that lets you find recommended and related anime through the context menu.

Huge thanks to @Gujal00 for making this possible.
