### ISSUE TITLE
Github is having a caching issue which is why repo is not getting update, it will resolve itself very soon. 

### ISSUE THREAD

**Issue by AakashC2020** [Goldenfreddy0703/Otaku#76]
Hi @Goldenfreddy0703 / @Gujal00,

Is there any issue with Kodi GitHub Repos at present. Since yesterday majority of my addons are not updating to the latest versions? For example, yesterday Fen addon didn't update to the latest version 3.0.42. Today I could see the latest version in one of my Kodi profiles but not in the other one. Also, I noticed that Otaku addon updated to v0.3.22 today but in the repo it's still showing as v0.3.21. I manually checked for updates in Kodi on my Nvidia Shield TV Pro and also installed a fresh version of Kodi on my android mobile, but the issue remains the same on both the devices. Kindly advise if any of you are facing the same issue like me.

Here's my Kodi log:

https://paste.kodi.tv/xehiliyoli

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Yeah im not sure either, Glad you noticed as well, i had trouble with my repo yesterday and i was not sure why.

**Comment by ShibajiCh** [comment]
Hi @Goldenfreddy0703,

Hope this issue gets resolved soon. 🙁

Thanks and Regards,
ShibajiCh.
