### ISSUE TITLE
Auto subtitles stopped working on version .23

### ISSUE THREAD

**Issue by icpryde** [Goldenfreddy0703/Otaku#77]
I noticed after the latest update of .23 the auto subtitles turning on stopped working as it was working fine in version .21 and .22

**Comment by Goldenfreddy0703** [comment]
I will take a look at that and see.

**Comment by icpryde** [comment]
dropped back to version .21 and its working again so i'd avoid .23 for now

**Comment by Goldenfreddy0703** [comment]
Hey so from doing some testing, subtitles are working correctly for me, Its possible that you might have messed with these settings in the past or maybe the first stream you tried was different of something. Will looks further into this but the code was not changed at all for subtitles. 

 ![paste (2)](https://user-images.githubusercontent.com/62456796/218344064-7298707f-f9c7-4c29-974a-d4713ae89308.png)

**Comment by AakashC2020** [comment]
Hi @Goldenfreddy0703,

I think @icpryde is using Dub stream and the newly added auto subtitle on setting for Dubs is turned off for him. I guess he needs to turn that setting on in Otaku.

**Comment by Goldenfreddy0703** [comment]
Yeah that's what I thought too. We will wait for a reply from him. That's why I labeled this issue invalid.

**Comment by AakashC2020** [comment]
> Yeah that's what I thought too. We will wait for a reply from him. That's why I labeled this issue invalid.

Okay @Goldenfreddy0703. 👍🏻

**Comment by icpryde** [comment]
@AakashC2020 but if I turn that on then it will only see dub and not sub?

**Comment by Goldenfreddy0703** [comment]
Subtitles should automatically turn on when its sub. Maybe you have to turn them on manually on a sub stream then try another stream to know if they are on or not.

**Comment by icpryde** [comment]
<img width="871" alt="Screenshot 2023-02-13 at 2 44 48 PM" src="https://user-images.githubusercontent.com/29389746/218559882-4ce696a2-f6dc-4652-a886-33b318f4db39.png">
<img width="846" alt="Screenshot 2023-02-13 at 2 45 12 PM" src="https://user-images.githubusercontent.com/29389746/218559886-ea94d627-c638-4d06-bc9c-544328805b0f.png">
<img width="732" alt="Screenshot 2023-02-13 at 2 45 59 PM" src="https://user-images.githubusercontent.com/29389746/218559888-19274a2e-f120-4b92-a2e6-8e932abf39ac.png">

I installed the latest version again @AakashC2020 and as soon as I do it stopped working again if I stay on .22 it works as its supposed too.

I even tried turning it on manually then starting the next episode and its off again as seen here.

<img width="1081" alt="Screenshot 2023-02-13 at 2 47 00 PM" src="https://user-images.githubusercontent.com/29389746/218560068-3b34b3d1-e5ad-4d0c-8b16-1d547729d8c9.png">

**Comment by Goldenfreddy0703** [comment]
Oh well no wonder, your preferred subtitle language is set to forced only. Set that to media default and check and see if it's working now.

**Comment by icpryde** [comment]
@Goldenfreddy0703 forced only is for english stuff that has periodic moments in other languages to pop up the subtitles for so that is a must to staying as forced only and that was working on .21 and .22 with forced only.

**Comment by Goldenfreddy0703** [comment]
Well just try it real quick and see what the result is. I would be surprised if it works tor you.

**Comment by icpryde** [comment]
@Goldenfreddy0703 just tried it i set subtitles to original language and started the episode and subtitles still didn't turn on automatically

**Comment by icpryde** [comment]
heres a log file, not sure if this is helpful at all

https://paste.kodi.tv/qaroxowezi

**Comment by Goldenfreddy0703** [comment]
Hey by anychance, autowidget can cause problems with Otaku, your not using Otaku widgets with Otaku, are you?

**Comment by Goldenfreddy0703** [comment]
Hey @joezito129 , can you look at his log when you are not busy? Apparently this new update caused subtitles not work for him and its related to a mac issue from looking at this log and device. Surprising its not an nvidia or firestick issue

**Comment by icpryde** [comment]
interesting, I wasn't using autowidget with Otaku but simply had it installed but I actually just uninstalled it cause I wasn't using it for anything anyway and sure enough.....its working now when subtitles set to "original language within kodi settings.

I just tested it as well with "forced only" subtitles like I had before and its still not working under that setting.

So autowidget definitely caused issues as it wasn't working at all but still an issue not working with "forced only" subtitles so please if it could work with that as it did in version .21 that would be great as for none anime stuff i used forced only for none english parts in some series/movies instead of the other option means you have to have subtitles for everything or nothing.

**Comment by icpryde** [comment]
- so in other words auto widget definitely an issue for otaku
- subtitles only work right now under "original language"
- if you can make it work with "forced only" as well that would be great as it did on version .21

**Comment by icpryde** [comment]
@

> Hey @joezito129 , can you look at his log when you are not busy? Apparently this new update caused subtitles not work for him and its related to a mac issue from looking at this log and device. Surprising its not an nvidia or firestick issue

@Goldenfreddy0703 this same issue happens on windows and nvidia shield i tested it on all 3 devices so its not just mac

**Comment by Goldenfreddy0703** [comment]
> @
> 
> > Hey @joezito129 , can you look at his log when you are not busy? Apparently this new update caused subtitles not work for him and its related to a mac issue from looking at this log and device. Surprising its not an nvidia or firestick issue
> 
> @Goldenfreddy0703 this same issue happens on windows and nvidia shield i tested it on all 3 devices so its not just mac

Oh right i forgot about that. Ok well what if you set your subtitles to english instead of forced only so that way you can still used subtitles but they are always in english. Forced subtitles recognizes and respects the forced flag for showing subtitles (even if subtitles are turned off by default, the forced flag will trigger them being turned on).

**Comment by icpryde** [comment]
> > @
> > > Hey @joezito129 , can you look at his log when you are not busy? Apparently this new update caused subtitles not work for him and its related to a mac issue from looking at this log and device. Surprising its not an nvidia or firestick issue
> > 
> > 
> > @Goldenfreddy0703 this same issue happens on windows and nvidia shield i tested it on all 3 devices so its not just mac
> 
> Oh right i forgot about that. Ok well what if you set your subtitles to english instead of forced only so that way you can still used subtitles but they are always in english. Forced subtitles recognizes and respects the forced flag for showing subtitles (even if subtitles are turned off by default, the forced flag will trigger them being turned on).

that won't the way its intended unless I'm unaware of something, forced is for shows like Narcos where its an english show but with a lot of spanish so the subtitles will only show for the spanish parts with english subtitles.

Would this still work that way if you set subtitles to "english"? i don't believe it will work that way I believe if you set to english it will have subtitles on for everything even the english parts which defeats the purpose of "forced only".

This worked as intended on version .21 where i could have forced only and subtitles turn on for when i was watching sub with anime it was perfect.

**Comment by Goldenfreddy0703** [comment]
> Would this still work that way if you set subtitles to "english"? i don't believe it will work that way I believe if you set to english it will have subtitles on for everything even the english parts which defeats the purpose of "forced only".

It would still work but it will have subtitles on for everything even the english parts which defeats the purpose of "forced only".

> just dropping another log file https://paste.kodi.tv/qopesekobu

Ok from looking at your look all the errors are gone now with Otaku which is surprising

**Comment by icpryde** [comment]
heres another log file after i played an episode without the subtitles turning on with forced only set https://paste.kodi.tv/wadojixuki

not sure what the error would be though? the previous error was just because of autowidget which i uninstalled.

**Comment by Goldenfreddy0703** [comment]
Ok still no errors but sense autowidget was removed, try setting you proffered subtitle language to original language again and see what happens.

**Comment by Goldenfreddy0703** [comment]
> but ya i'll stick to version .21 until it can work like it did

Wait what about version .22, is version .22 working for you as well?

**Comment by icpryde** [comment]
@Goldenfreddy0703 yes it works under preferred subtitle language which we already established but not under forced which is the issue.

i don't have a copy of .22 so can't test on that one i was just lucky enough to have .21 that i could fall back on.

**Comment by Goldenfreddy0703** [comment]
Ok so the issue could remain I'm .22 then

**Comment by icpryde** [comment]
maybe but i don't think so since pretty sure .22 was working just fine and didn't notice the issue until you introduced that sub/dub feature that made it stop responding the way it was before.

**Comment by Goldenfreddy0703** [comment]
Here is a copy. 

https://github.com/Goldenfreddy0703/repository.hooty/raw/master/repo/zips/plugin.video.otaku/plugin.video.otaku-0.3.22.zip

**Comment by icpryde** [comment]
ok I tested .22 and it stops working with that version too, so it only works on .21 with forced only in settings. 

made a video showing it on .21 then on .22

https://streamable.com/dh7ygs

**Comment by Goldenfreddy0703** [comment]
No wonder, ok i can release a fix for that. Thanks for pointing that out.

**Comment by Goldenfreddy0703** [comment]
Ok so fix should be released and hopefully they should work again for you. Next time, make sure to test previous versions like .22 so that we know that they are working fine.

**Comment by Goldenfreddy0703** [comment]
Ok Test it now @icpryde and tell me if it is working for you now.

**Comment by icpryde** [comment]
@Goldenfreddy0703 BOOOOM tried .24 and its working wooooooooo! thank you!!!!

**Comment by Goldenfreddy0703** [comment]
Ok good thank you, now im closing this.

**Comment by Goldenfreddy0703** [comment]
@icpryde hey sorry for bothering, have a request for you. Test the subtitles again and see if there working property. Made some improvements but want to make sure there working for you. Thank you
