### ISSUE TITLE
Add mark as watched with said % in Settings

### ISSUE THREAD

**Issue by Blockr22** [Goldenfreddy0703/Otaku#78]
I want this option in the settings that i can change the percent when would i like otaku to mark it watched like we have in fen.
Right now if the anime is almost ended & i stop it. It is showing me still in progress & i have to clear progress to mark it as watched.

**Comment by Goldenfreddy0703** [comment]
Ooooo interesting setting, ok will probably add that very soon maybe.

**Comment by Blockr22** [comment]
Thnx

**Comment by Gujal00** [comment]
This is a fine tuned setting, on shows that on average of 24 minutes, with a generally 1-2 minute end credits, with it hardcoded at 80% now if you watch at least 18 minutes, it will mark as watched. I dont see any reason to change this

**Comment by Blockr22** [comment]
Then, its not working as intended. Anilist shows i have watched it when i stop it at the end of any anime but otaku says its in progress

**Comment by Gujal00** [comment]
I use Anilist account authorised in Otaku and it works correctly on both Kodi 19.5 on Windows and Kodi 20 nightly on CoreElec.

**Comment by Goldenfreddy0703** [comment]
> Then, its not working as intended. Anilist shows i have watched it when i stop it at the end of any anime but otaku says its in progress

Would you mind sending us a change log sense you said its not working as its intended to do?

**Comment by joezito129** [comment]
you need to change your advancedsettings.xml:
![Capture](https://user-images.githubusercontent.com/60677138/218617848-4199a215-fdcf-4f77-8d1c-5da24cb213c2.PNG)

Kodi only marks it as watched if you watch 90% of the video but in our addon it marks it at 80% you need to change you advancedsettings.xml to set it to 80%.

**Comment by joezito129** [comment]
Please take a look at this:
https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points

**Comment by Blockr22** [comment]
Thnx, will have a look at it
