### ISSUE TITLE
Resuming doesn’t work

### ISSUE THREAD

**Issue by Blockr22** [Goldenfreddy0703/Otaku#79]
Using latest everything.
1. Otaku with next up & current from Anilist
2. On AH2 Skin on homescreen
3. Using shield 2017 & kodi 20 nexus

Not even asking to resume when playing from next up screen from home screen of AH2 but it does when playing from current menu from homescreen of AH2

**Comment by Goldenfreddy0703** [comment]
That's cause there is a bug with widgets that evolves Playlist stuff that we have to fix in the near future. Closing this issue sense it eas kind a duplicate to the Nvidia issues and the Play next for widgets issue.

**Comment by Blockr22** [comment]
Thnx but I don’t see anything mentioning resuming bug in that ticket

**Comment by Goldenfreddy0703** [comment]
True but could be an issue with indicators maybe sense it was on widget. We will look into this tho.

**Comment by Blockr22** [comment]
Kk, thnx
