### ISSUE TITLE
Can't find watchlist

### ISSUE THREAD

**Issue by watar** [Goldenfreddy0703/Otaku#81]
I can't seem to find the Watchlist in the menus. I have no problem authorizing my acoounts in Settings but I can't find the lists in the addon menus after that, most likely an user error but can't for the life of me find it...
Tried both with MAL and Anilist.

**Comment by watar** [comment]
and I've tried the troubleshooting in https://github.com/Goldenfreddy0703/Otaku/issues/15

**Comment by Goldenfreddy0703** [comment]
Try authorizing one by one and restart kodi and see if that works.

**Comment by Goldenfreddy0703** [comment]
> Unrelated but, @Goldenfreddy0703 , I was watching an anime, I thought it would update and show up in my trakt account, but it didn't.
> Is it possible to sync what I'm watching in trakt?

Ok I hered this multiple times and there is no way sync it with trakt cause trakt has a way different database then Anilist, Kitsu, or Mal. 

There is no way to sync anime with trakt unless simkl can do something about it.

**Comment by rahaaatul** [comment]
That's a bummer! :( 

A request: Can you give an option to load x amount of pages and hide the next page button for widgets?
 
![screenshot00001](https://user-images.githubusercontent.com/86149861/218575548-ecda8958-f180-4c63-914e-de58325d455f.png)

**Comment by Goldenfreddy0703** [comment]
Ok sadly no but I can take a look to see if there is a way to hide the next for widgets. It may require separate Playlist but again. Not sure

**Comment by Goldenfreddy0703** [comment]
Hey @watar , did that watchlist thing work for you by authenticating them one by one?

**Comment by rahaaatul** [comment]
Sorry for bothering you again @Goldenfreddy0703 but is there a way to change view for all episode menu, instead of individually changing one by one? I changed one of my local anime's episode view, and it changed for every anime. But for Otaku it's not doing the same thing.

https://user-images.githubusercontent.com/86149861/218710133-9823cffc-bd2f-425b-be7c-b0b9c3503eca.mp4

And is there a dedicated space for asking questions related to Otaku? Thank you for being patient with me.

**Comment by Goldenfreddy0703** [comment]
Ok sadly no but there is a possibility you skin has a setting to lock veiws maybe.

**Comment by rahaaatul** [comment]
> Ok sadly no but there is a possibility you skin has a setting to lock veiws maybe.

I'm using **Arctic Zephyr Reloaded** v1,1,72 , I didn't find lock view here...

**Comment by Goldenfreddy0703** [comment]
Ok that's good to hear.

**Comment by watar** [comment]
> Hey @watar , did that watchlist thing work for you by authenticating them one by one?
> 

I wiped all add-on data, re-authorized it and then restarted kodi. Then it worked. 

Thx for the help.

**Comment by Goldenfreddy0703** [comment]
Hey anytime!!!!
