### ISSUE TITLE
Show missing in MyAnimeList but showing in Anilist

### ISSUE THREAD

**Issue by DaisyF8** [Goldenfreddy0703/Otaku#83]
The show [Futoku no Guild](https://myanimelist.net/anime/51212/Futoku_no_Guild) seems to be invisible in MyAnimelist, no matter if it's in Currently Watching, Plan to Watch, ...  Anilist doesn't have this problem.  Strange huh.

Is it the same for you ?

**Comment by Goldenfreddy0703** [comment]
Not sure sense mal is not my watchlist, I can check soon tho.

**Comment by Goldenfreddy0703** [comment]
Hey so i took a look today and it is showing for me but the Mal title is actually called [Futoku no Guild](https://myanimelist.net/anime.php?id=51212)

Its possible that you watchlist to update is on Anilist i think in your watchlist settings or you may need to reauthenticate Mal again maybe. 

Im going to close this but if you still encounter issues, will take look at that more.

**Comment by DaisyF8** [comment]
I installed a new Kodi and Otaku. Same problem, both on Android.

So I am using MAL as watchlist (not anilist), and yes that title (same as I wrote and linked right?).

On the  primary device I allready re-authed MAL today, and previously also did the three steps to troubleshoot (clear cache, torrent cache and rebuild).

**Comment by DaisyF8** [comment]
I just noticed that when watching episodes Otaku does update these episodes in Mal.  So everything is working except showing the Show in Next Up or Currently Watching.

When I search for "Futokku No Guild" the show gets found and the watched episodes are marked Watched.

**Comment by Goldenfreddy0703** [comment]
Yeah that is a bit weird but Watchlist can be different sometimes, maybe we will look into this maybe.

**Comment by DaisyF8** [comment]
Don't  worry... Mine is but a small problem.  And it's really also only with that show so the impact is small.

Thanks for looking into it.
