### ISSUE TITLE
Movie Category

### ISSUE THREAD

**Issue by Guacan0le** [Goldenfreddy0703/Otaku#84]
The menu items in “Movies” is mixed up. I have to select “Trending Last Year” to show recent movies.

**Comment by Goldenfreddy0703** [comment]
I'm sorry but what do you mean?

**Comment by Goldenfreddy0703** [comment]
Hey @Guacan0le its been about 5 days now. Would you mind telling me what you mean?

**Comment by Goldenfreddy0703** [comment]
Hey @Guacan0le sense you have not responded in about a week, im closing this issue,
