### ISSUE TITLE
Error message for World Trigger episodes

### ISSUE THREAD

**Issue by rogermae** [Goldenfreddy0703/Otaku#85]
See the photo.
![20230222_141539](https://user-images.githubusercontent.com/36041288/220736506-91bc0c75-6cc1-4bd9-a2af-4de948d402b4.jpg)

**Comment by rogermae** [comment]
I removed and reinstalled the addon. All's well now.

**Comment by Goldenfreddy0703** [comment]
Ahh ok, i was gonna say follow my troubleshooting steps, glad that worked out for you.
