### ISSUE TITLE
Crashing when trying to watch a particular anime

### ISSUE THREAD

**Issue by EXTIINCT** [Goldenfreddy0703/Otaku#86]
So, to start off, I can watch most things fine. I can watch TV and movies through Fen, I can watch other anime through Otaku with no issues.

It's just I'm having issues with one particular anime, Higurashi no Naku Koro ni Gou. Every time I tried to watch it, it looks for sources, then that all goes away like normal except instead of playing the episode like normal it just hard crashes to desktop.

I have AllDebrid authorized.

[kodi.log](https://github.com/Goldenfreddy0703/Otaku/files/10811234/kodi.log)

**Comment by Goldenfreddy0703** [comment]
Oh i did forget, there is a small possibility you may want to reinstall inputstream adaptive just incase sense otaku uses it for embeds.

**Comment by EXTIINCT** [comment]
Huh, well I did the clear, rebuild and reinstalled inputstream adaptive and it's working now so 🤷‍♂️...

Thanks!

**Comment by Goldenfreddy0703** [comment]
Anytime!!!
