### ISSUE TITLE
Episodes not showing/blank screen

### ISSUE THREAD

**Issue by ahmedashed** [Goldenfreddy0703/Otaku#87]
Hi All,

Many thanks for this wonderful addon, there is no scraper like it when it works. However I seem to have encountered bug that I do not think has been mentioned or has not already been fixed. 

Steps to recreate bug:
Open Otaku
Click Search
Fire Force
Brings a list of result
Select fire force season 1
Loads for a while, nothing happens
Select again
Loads but this time shows a blank page
Go back and select again
Loads for a while but this time 3 things can happen
sometimes it will show otaku error check log OR
It will show a blank page OR
It will load

I tried the same with season 2, it is the same but it actually never loads

I am on a shield pro with Kodi v20,

What I already tried:
Cleared cache
Torrent cache
Rebuild database
Wipe addon data

Then now I have uninstalled and reinstalled addon and the same bug still shows

I have attached a kodi log, hope it helps
[kodi.log](https://github.com/Goldenfreddy0703/Otaku/files/10817074/kodi.log)

Thanks in advance for your assistance and I apologise in advance if the solution is simple.

**Comment by Goldenfreddy0703** [comment]
Ok I said this to the same person but try reinstalling input stream adaptive if your using embeds.

**Comment by Goldenfreddy0703** [comment]
Actually it could be due to the high traffic on the api side of consumet. Will be resolved eventually, just needs time for fixing very soon.

**Comment by ahmedashed** [comment]
> Ok I said this to the same person but try reinstalling input stream adaptive if your using embeds. 

But I'm not even getting to scrape the episodes. This is purely not even loading the season episodes. Regardless, I'm not using embeds, I was logged in to my debrid.

**Comment by Goldenfreddy0703** [comment]
Yeah, could be due to high amount of traffic from the consumet api

**Comment by slemus992** [comment]
I'm having the same issue using a shield and I tried reinstalling "input stream adaptive" and nothing 🥺 hope it gets fixed soon. Love the addon btw! Best one for anime!

**Comment by Goldenfreddy0703** [comment]
It will eventually, i wish we had that fallback simkl api ready incase something like this happened. Consumet should be back up very soon.

**Comment by Goldenfreddy0703** [comment]
Hey guys api is up, just make sure to do this step incase you guys have any more errors. 

https://github.com/Goldenfreddy0703/Otaku/wiki/Metadata-Scrapping-Features
