### ISSUE TITLE
Disable scraping screen fanart

### ISSUE THREAD

**Issue by Joshuao95** [Goldenfreddy0703/Otaku#88]
Hello!

I'd like to disable the fanart that is shown during the scraping phase (i.e: the screen after you click an episode but before it plays).

Happy to submit a PR if you can point me towards:
- where the scraping screen art generation is in the code.
- where I can add the toggle option

Thanks!

**Comment by Goldenfreddy0703** [comment]
Hey so sadly i kinda forgot but will try to look at this tomorrow maybe.

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry i never got to you sooner, you can make a pr if you like and i will try to point you where the scraping screen art generation is in the code. I will also point you to the Source Select Screen as well sense its part of scrapping

- Scrapping Screen is in the plugin.video.otaku\resources\skins\Default\1080i\resolver.xml
- Source Select Screen is in the plugin.video.otaku\resources\skins\Default\1080i\source_select.xml
- For Options, you can add the toggle option maybe under line 22 where "general.icons" is located. 
- For Options, only thing i ask is not to use "labelenum" as your type in the options unless your using regular Values.
- For Strings, feel free to add any labels you need, just make sure to add them around the lines of 726

Sorry i was very busy but i would be happy to accept your pr.

**Comment by Joshuao95** [comment]
Cheers, will take a look and make the PR when I get the time :+1:

**Comment by Goldenfreddy0703** [comment]
Hey so i might have told you the wrong files by mistake but i went ahead and made a setting that Disables scraping screen fanart and that Disables scraping screen clearlogo as well. 

Test this whenever you have time and im going to go ahead and close this issue. 
Thank you
