### ISSUE TITLE
Not showing results/all results when scraping

### ISSUE THREAD

**Issue by ahmedashed** [Goldenfreddy0703/Otaku#89]
Hi again, sorry for another bug/glitch report in a few days. It is only because I use this addon very often :)

So essentially scraping seems to have a weird issue where it showing no results or very few results compared to the cached number on scrape. 

I do not use embeds and have disabled them. I only use real-debrid. 
The behaviour would range from only showing one result when it says like 9 cached or showing no results. I have pictures below of different scenarios. 

I have already tried clearing cache, torrent cache, rebuilding database and I honestly do not want to reinstall the addon again for the second time in past few days. 

The pictures show what I mean and I have attached a log. Yes my real-debrid account works and scraping on other addons work. I am on nvidia shield pro with kodi v20 nexus.

I am in the UK where nyaa is not blocked on my ISP and this didn't used to happen.

MHA season 6, the second till most recent ep showed blank
![IMG20230225185622](https://user-images.githubusercontent.com/63984654/221375395-fc31f8df-82b6-4a20-bf11-0467f9d798d5.jpg)

MHA season 5 showed 9 cached and only 4 showed
![IMG20230225185653](https://user-images.githubusercontent.com/63984654/221375397-cf5cb8e0-ec19-4091-a152-a2125f7dcf2e.jpg)

Vinland season 2 only showed one result in 720p
![IMG20230225185914](https://user-images.githubusercontent.com/63984654/221375398-0fe5328a-87f9-420a-964e-76369365984f.jpg)

[kodi.log](https://github.com/Goldenfreddy0703/Otaku/files/10832076/kodi.log)

Many thanks for all your assistance.

**Comment by Gujal00** [comment]
Looks like you have configured searching for dubbed sources only. So only Dual Audio would show up in nyaa scrape results.
Remove the filter and it will show all results

**Comment by Goldenfreddy0703** [comment]
That's was i noticed as well, was looking at the issue just now and noticed that just now.
![image](https://user-images.githubusercontent.com/62456796/221385097-e24d33b8-0a7a-46f9-a6e5-302e37f66f2b.png)

**Comment by ahmedashed** [comment]
Oh I see, so when the preferred source in the settings means the only source. Thanks I have set it to both now, should hopefully work.

Also what does tertiary sort dub preference mean? Does it make a difference if I select the dual audio setting as English?

**Comment by Goldenfreddy0703** [comment]
Hey sorry i was afk, tertiary sort dub preference is when the dub sources are ontop. Its only useful when you have your preferred source set to both.

**Comment by ahmedashed** [comment]
Yes I think that's best for me, I have set it to both but I prefer dub when it's available, thanks to both of you for sorting it out

**Comment by Goldenfreddy0703** [comment]
Anytime!!!
