### ISSUE TITLE
Missing poster/art in the "Airing Dubbed Anime" section

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#9]
Like the title says. I'm using Arctic Horizon 2.

![Screen Shot 2022-08-25 at 10 38 21 AM](https://user-images.githubusercontent.com/43726430/186764002-86533b57-f7fc-4b85-8e5e-3c027dbf6439.png)
<img width="2560" alt="Screen Shot 2022-08-25 at 10 38 13 AM" src="https://user-images.githubusercontent.com/43726430/186764007-46cab0c2-9ac5-4f8b-979c-255d5658e193.png">

**Comment by Gujal00** [comment]
Airing dubbed anime is currently just a list of titles and has no art associated. Adding art to the list means scraping for each item art fro anilist/mal and will affect performance as there are over 200 items in the list. It is known issue and is already mentioned on the Readme of this repository under ToDo

**Comment by Liquidrag** [comment]
> Airing dubbed anime is currently just a list of titles and has no art associated. Adding art to the list means scraping for each item art fro anilist/mal and will affect performance as there are over 200 items in the list. It is known issue and is already mentioned on the Readme of this repository under ToDo

Thank you. I'm sorry I missed it in the Readme.
