### ISSUE TITLE
Request: Option to hide episode synopsis

### ISSUE THREAD

**Issue by Andrewskiz** [Goldenfreddy0703/Otaku#90]
Often times the episode synopsis contains spoilers, it would be great if there was an option to hide this. Or maybe there is and I just missed it?

**Comment by Goldenfreddy0703** [comment]
Honestly I don't really think having an option for that is necessary cause other addons like seren or fen don't even have an option like that. I think it would be pointless to have that option.

**Comment by Goldenfreddy0703** [comment]
Hey so this may sound surprising but our next release will have this option thanks to @joezito129

**Comment by Goldenfreddy0703** [comment]
Hey so good news, next release im releasing in a few min should have an option to hide spoilers. 
Big thanks to @joezito129 for adding it. 
Im gioing to close this again.
