### ISSUE TITLE
Can't connect to repository?

### ISSUE THREAD

**Issue by Khaleesi-Kai** [Goldenfreddy0703/Otaku#91]
Hey there,

Trying to install the Otaku addon from the Hooty Repository. When I install from the zip file, the Hooty repository appears to install, but when I attempt to open it to locate the Otaku addon, I get an error saying "Cannot connect to repository." Is there a new location to download the repository from or..??

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry I didn't get to you sooner. If your using kodi 20, kodi has this weird glitch where some repos can't connect. To bypass this, restart kodi and open it back up but when you open it, make sure to go to install to repo as fast as you can navigate and click my repo and you should be able to connect.

**Comment by Goldenfreddy0703** [comment]
Hey @Khaleesi-Kai , were you ever able to connect to my repo?

**Comment by Khaleesi-Kai** [comment]
Hey thanks for getting back to me! I actually installed it manually using
the 3 separate files provided and it works !!

Is there a way to adjust settings so that dubbed show separately from subs?
ARE dubs available? Trying to search for a way to do this but only finding
subs thus far.

**Comment by Goldenfreddy0703** [comment]
Hey so look at the troubleshooting steps on filtering topic and subs and dubs topic and that should help you with the addon and all. 

https://github.com/Goldenfreddy0703/Otaku/issues/15

**Comment by Khaleesi-Kai** [comment]
Thanks…I’ve tried following the steps for adjusting the settings in Kodi
and in the Otaku addon but so far the most I’ve gotten is filtered lists
that do show Dubs and Subs, but when I play the Dubs, they are pretty much
the same files as the subs - Japanese audio and subtitles. Done this for
more than one series and it’s the same issue. Will keep trying - maybe I’m
missing a step…

**Comment by Goldenfreddy0703** [comment]
I should have given you the wiki page, try this step and this should help you out, 
https://github.com/Goldenfreddy0703/Otaku/wiki/Sub-or-Dubs

**Comment by Khaleesi-Kai** [comment]
Much appreciated - and okay so I WAS following those steps but here's where
my problems came up:

I initially set the Preferred Source to "both" because some shows don't
have Dubbed episodes available yet and for those I'm good to watch the
subs. Setting it to "Eng" works in that it definitely gives me the dubs,
but it is a strict filter that also now keeps the subs from showing up.

My first attempt where I used "Both" as my Preferred Source kinda gave me
what I wanted, which was results that were differentiated by either (Dub)
or (Sub) in the titles. BUT the trouble there was that the playback for ALL
of them was subbed and there was no English at all.

I was hoping to get both options in my search results, with the respective
playback language ("Dub" giving me english, "Sub" giving me jpn with
subtitles) without having to go back and forth in the settings. Even if
there was a way to set it up that if no dubbed playback exists, the default
would be the subbed playback, this would be fine.

What am I doing wrong? Or is there no way to do this?

Thanks for all your help thus far - you're by far THE best and most
responsive developer I have met! :D

**Comment by Goldenfreddy0703** [comment]
Oh if it helps, if you have both selected, make sure to turn on territory dub preferences on so that way you can have dubs as the top results and subs on the bottom.

**Comment by Khaleesi-Kai** [comment]
YES!! Finally got it to work as I hoped. Thanks for all your help. You are awesome!!
