### ISSUE TITLE
New torrent site request

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#92]
Hi, just wanted to share a site that in my opinion is way better than nyaa and even have some of their torrents which is a win win, hopefully it can be added to have even more high quality torrent sources when scraping. 👍

Here's the site; https://animetosho.org

Give it a look and see if it can be added, if not it's all good! Just wanted to share it anyways in hopes of making Otaku even a better place for anime content overall. 🙂

Cheers, and keep the great work!

Love this add-on. 😃

**Comment by Goldenfreddy0703** [comment]
From looking at the site, it does look well organized and supports Nyaa and Anidex. Maybe we could add something like this in the future.

**Comment by Nuklear92** [comment]
> From looking at the site, it does look well organized and supports Nyaa and Anidex. Maybe we could add something like this in the future. 

Awesome! Thanks, definitely looking forward to this. 😃

**Comment by HughMungis** [comment]
I'm 90% sure that animetosho is a scraper for Nyaa in case it gets taken down.

**Comment by Goldenfreddy0703** [comment]
> I'm 90% sure that animetosho is a scraper for Nyaa in case it gets taken down.

I mean kinda but not really. Animetosho is its own torrent site i think cause it adds torrents from either [TokyoTosho](https://tokyotosho.info/?cat=1), [Nyaa](https://nyaa.si/?c=1_2) or [AniDex](https://anidex.info/?id=1) which is like 3 torrent sites in one that would give you more options and they have an api for it so there is a possibility we could add this. Hopefully it will be easy to do.

**Comment by Goldenfreddy0703** [comment]
Whoops my fault, leaving this open sense it looks like a good torrent site.

**Comment by Gujal00** [comment]
tokyotosho and aniudex just reindex nyaa torrents, so bring nothing new. Everything else on Animetosho are download from filelockers or NZB which cant be streamed. No incentive to add Animetosho to a streaming addon

**Comment by Goldenfreddy0703** [comment]
awww i thought tokyotosho and aniudex would be very useful sense they are torrent sites as well. What about horriblesubs, is that still a thing or did that shutdown years ago?

**Comment by Goldenfreddy0703** [comment]
Hey so I'm going to close this for now but if you guys think of other sites that are not indexing from nyaa, feel free to suggest them here and I may reopen this issue back up again. 

Thank you for the suggestions tho.
We plan to plan to improve scrapping in the future.
