### ISSUE TITLE
Wrong Episodes Automatically Chosen

### ISSUE THREAD

**Issue by AnthonyA1223** [Goldenfreddy0703/Otaku#93]
Hello, for the past few days Otaku has been consistently choosing the wrong episodes to play, examples include:

1. My Hero academia season 6 consistently chooses the wrong episode when around episode 10.
2. Classroom of the elite season 1 episode 1 but actually chooses season 2 episode 2

I've had this issue on two different devices running android TV and Kodi v20 nexus, using two different MAL accounts and two Real Debrid as a provider.

**Comment by Goldenfreddy0703** [comment]
Funny story, someone actually mentioned that as well and reason why is cause nyaa scrapping is kinda a mess, i suggest using embeds cause you will not notice the difference between the embed and torrent file. 

Btw 9anime or gogohd are the best embeds you can enable in provider settings.
