### ISSUE TITLE
Enable Easynews?

### ISSUE THREAD

**Issue by Sparda333** [Goldenfreddy0703/Otaku#95]
I can't find where to enable Easynews.

**Comment by Goldenfreddy0703** [comment]
Well that's cause we don't have Easynews. 😅

**Comment by Sparda333** [comment]
It was mentioned in a update not long ago I thought you added it?

**Comment by Goldenfreddy0703** [comment]
On our last post, we made a dubs filter but we aren't sure if we should add Easynews in the future. We need a contributor to add it or if @Gujal00 can add it someday.

**Comment by Sparda333** [comment]
AHH ok thanks hope you do.
