### ISSUE TITLE
keeps skipping to next episode  after  3 minutes 

### ISSUE THREAD

**Issue by JamesCaywood** [Goldenfreddy0703/Otaku#98]
hmm am on android  kodi 20 and some reason  it keeps skipping over  to the next episode  after every 3 minutes what it seems no matter what show i watch here my log 

https://paste.kodi.tv/ixoyofalum

**Comment by Goldenfreddy0703** [comment]
Ok try reinstalling inputsteam adaptive. I heard most of the errors are caused by this.

**Comment by JamesCaywood** [comment]
hmm seems like it still does it 

https://paste.kodi.tv/gosecovefe

**Comment by Goldenfreddy0703** [comment]
Ok you wouldn't by anychance be using a VPN or using Verizon, are you?

**Comment by JamesCaywood** [comment]
yes sir am using nordvpn? is that the problem? I never had this problem before  I dont have Verizon carrier  but am using the home internet  with nordvpn

**Comment by JamesCaywood** [comment]
ahhh lord i guess it was the nordvpn  I cant use vpn?? never did this before on different apps

**Comment by Goldenfreddy0703** [comment]
Hey sorry I never replied to you. NordVPN is kinda dumb with real debrid so that's why you were having problems. Good thing we found the issue and glad you got it resolved.
