### ISSUE TITLE
Otaku crash for 9anime source

### ISSUE THREAD

**Issue by Dappakid13** [Goldenfreddy0703/Otaku#99]
I have  had a issue with otaku recently on my nvidia shield tv. It used to crash as soon as I play a gogohd or 9anime embed but after days of testing and doing several fresh install of kodi and I still noticed the issue most time, this only happens on my nvidia shield 2017 (crash occurs within the first 3 seconds of the video playback). Any idea what it could be? Not really seeing anything in the logs, not see a debug log for otaku  either.

**Comment by Goldenfreddy0703** [comment]
This could have something to due with issue #69

**Comment by Goldenfreddy0703** [comment]
Do all troubleshooting steps on #15 and see if that helps.

**Comment by Dappakid13** [comment]
I tried and checked #15 and #69 but the issue was the same. Did a fresh installs and it was the same. I downloaded kodinerds nexus build and it works perfectly with the same build on both.

**Comment by Goldenfreddy0703** [comment]
Oh then it was probably either kodi 20 itself or reinstalling inputstream adaptive.
